package dev.jordond.filmstrip.sample

import kotlin.time.Duration
import kotlin.time.Duration.Companion.milliseconds

private const val HOST = "https://filmstrip-media.jordond.dev"

/**
 * One clip the sample can fetch instead of asking for a file.
 *
 * @property name What the clip is, short enough for a list row.
 * @property detail What makes it worth testing: the codec, the container, the awkward shape.
 * @property file The clip's name on the host the corpus is published to.
 * @property bytes How big the download is, so a row can say so before it starts one.
 * @property duration How long the clip plays.
 * @property attribution Who made the footage, where a licence asks for it to be said.
 */
public class SamplePreset(
  public val name: String,
  public val detail: String,
  public val file: String,
  public val bytes: Long,
  public val duration: Duration,
  public val attribution: String? = null,
) {
  /**
   * Where the clip is downloaded from.
   */
  public val url: String get() = "$HOST/$file"

  /**
   * The name the download is cached under.
   */
  public val fileName: String get() = file
}

/**
 * The clips a bug report can point at.
 *
 * Each one is here for something a backend has to get right: a container it may not read, a
 * rotation that has to survive a crop, audio that stops before the video does, a frame past what a
 * phone will encode. Most are generated by ffmpeg from its own test sources, so they belong to
 * nobody and rebuild identically. See `sample/media` for the recipes and for where the two pieces
 * of real footage came from.
 */
public val samplePresets: List<SamplePreset> = listOf(
  SamplePreset(
    name = "720p H.264",
    detail = "H.264 video and AAC audio in MP4. The ordinary case.",
    file = "h264-720p-aac.mp4",
    bytes = 4_059_755,
    duration = 10_000.milliseconds,
  ),
  SamplePreset(
    name = "720p, no audio track",
    detail = "The same clip with the audio stream left out entirely.",
    file = "h264-720p-silent.mp4",
    bytes = 1_938_626,
    duration = 5_000.milliseconds,
  ),
  SamplePreset(
    name = "1080p H.265",
    detail = "H.265 video and AAC audio in MP4.",
    file = "hevc-1080p-aac.mp4",
    bytes = 6_338_248,
    duration = 8_000.milliseconds,
  ),
  SamplePreset(
    name = "Portrait",
    detail = "Taller than it is wide, with no rotation in the metadata.",
    file = "h264-portrait.mp4",
    bytes = 2_544_165,
    duration = 6_000.milliseconds,
  ),
  SamplePreset(
    name = "Portrait, rotated 90 degrees",
    detail = "Landscape frames with a display matrix, which crop and scale have to honour.",
    file = "h264-portrait-rotated.mp4",
    bytes = 2_416_698,
    duration = 6_000.milliseconds,
  ),
  SamplePreset(
    name = "Audio shorter than video",
    detail = "Three seconds of audio under eight seconds of video.",
    file = "h264-short-audio.mp4",
    bytes = 3_180_919,
    duration = 8_000.milliseconds,
  ),
  SamplePreset(
    name = "Mono at 44.1 kHz",
    detail = "One channel at a rate the output usually is not, so the audio has to be resampled.",
    file = "h264-mono-44100.mp4",
    bytes = 2_003_276,
    duration = 5_000.milliseconds,
  ),
  SamplePreset(
    name = "Non-square pixels",
    detail = "720x480 stored, 16:9 displayed. The pixel aspect ratio is the whole point.",
    file = "h264-anamorphic.mp4",
    bytes = 800_481,
    duration = 5_000.milliseconds,
  ),
  SamplePreset(
    name = "Tears of Steel",
    detail = "Real footage: grain, motion and shadow, which no test pattern has.",
    file = "tears-of-steel-720p.mp4",
    bytes = 1_955_808,
    duration = 10_000.milliseconds,
    attribution = "(CC) Blender Foundation, CC BY 3.0",
  ),
  SamplePreset(
    name = "Orion looking back at Earth",
    detail = "Real footage, shot in space and lit like nothing on the ground.",
    file = "nasa-orion-earth.mp4",
    bytes = 1_055_625,
    duration = 10_000.milliseconds,
    attribution = "NASA, public domain",
  ),
  SamplePreset(
    name = "AVC in Matroska",
    detail = "The 720p clip remuxed into MKV, a container not every backend reads.",
    file = "h264-aac.mkv",
    bytes = 4_054_088,
    duration = 10_021.milliseconds,
  ),
  SamplePreset(
    name = "VP9 and Opus in WebM",
    detail = "The pair the browser is happiest with and the phones often are not.",
    file = "vp9-opus.webm",
    bytes = 3_142_415,
    duration = 6_008.milliseconds,
  ),
  SamplePreset(
    name = "AV1",
    detail = "AV1 in MP4, which older hardware decodes in software or not at all.",
    file = "av1-720p.mp4",
    bytes = 1_153_946,
    duration = 5_000.milliseconds,
  ),
  SamplePreset(
    name = "HDR10, PQ",
    detail = "10 bit BT.2020 with PQ and mastering metadata. Encoding it is what tone mapping is for.",
    file = "hevc-hdr10-pq.mp4",
    bytes = 4_666_207,
    duration = 5_000.milliseconds,
  ),
  SamplePreset(
    name = "HLG",
    detail = "10 bit BT.2020 with the transfer a phone camera shoots HDR in.",
    file = "hevc-hlg.mp4",
    bytes = 4_038_284,
    duration = 5_000.milliseconds,
  ),
  SamplePreset(
    name = "4K60, no B-frames",
    detail = "3840x2160 at 60 fps, at a size some encoders refuse.",
    file = "h264-4k60.mp4",
    bytes = 7_124_105,
    duration = 3_000.milliseconds,
  ),
  SamplePreset(
    name = "8K H.265",
    detail = "7680x4320 at 24 fps. Past what most devices will encode.",
    file = "hevc-8k24.mp4",
    bytes = 15_375_965,
    duration = 3_000.milliseconds,
  ),
  SamplePreset(
    name = "240 fps",
    detail = "720p at 240 fps, for what happens when the frame rate is dropped.",
    file = "h264-720p-240fps.mp4",
    bytes = 3_204_068,
    duration = 4_000.milliseconds,
  ),
  SamplePreset(
    name = "Ten minutes of 180p",
    detail = "Long and small, for watching progress and cancellation behave.",
    file = "h264-180p-10min.mp4",
    bytes = 17_191_500,
    duration = 600_000.milliseconds,
  ),
)
