package dev.jordond.filmstrip.avfoundation

import dev.jordond.filmstrip.ComponentRegistry
import dev.jordond.filmstrip.ExperimentalFilmstripApi
import dev.jordond.filmstrip.Filmstrip
import dev.jordond.filmstrip.InternalFilmstripApi
import dev.jordond.filmstrip.avfoundation.internal.AvFoundationDriver
import dev.jordond.filmstrip.avfoundation.internal.syncSampleAtOrBefore
import dev.jordond.filmstrip.avfoundation.internal.toAvComposition
import dev.jordond.filmstrip.avfoundation.internal.toDuration
import dev.jordond.filmstrip.edit.EditComposition
import dev.jordond.filmstrip.edit.compositionOf
import dev.jordond.filmstrip.effects.BuiltInEffectResolver
import dev.jordond.filmstrip.effects.color.brightness
import dev.jordond.filmstrip.export.CopyBlocker
import dev.jordond.filmstrip.export.ExportPath
import dev.jordond.filmstrip.export.ExportPlan
import dev.jordond.filmstrip.export.ExportSpec
import dev.jordond.filmstrip.export.ExportStatus
import dev.jordond.filmstrip.export.Verdict
import dev.jordond.filmstrip.media.MediaSink
import dev.jordond.filmstrip.media.MediaSource
import dev.jordond.filmstrip.media.chainedProber
import dev.jordond.filmstrip.transform.internal.ResolveResult
import dev.jordond.filmstrip.transform.internal.ResolvedComposition
import io.kotest.matchers.shouldBe
import kotlinx.cinterop.ExperimentalForeignApi
import kotlinx.cinterop.readValue
import kotlinx.cinterop.useContents
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.toList
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.withContext
import platform.AVFoundation.AVAsset
import platform.AVFoundation.AVAssetTrack
import platform.AVFoundation.AVAssetTrackSegment
import platform.AVFoundation.AVMediaTypeAudio
import platform.AVFoundation.AVMediaTypeVideo
import platform.AVFoundation.AVURLAsset
import platform.AVFoundation.segments
import platform.AVFoundation.tracksWithMediaType
import platform.Foundation.NSFileManager
import platform.Foundation.NSProcessInfo
import platform.Foundation.NSTemporaryDirectory
import platform.Foundation.NSURL
import kotlin.test.Test
import kotlin.test.assertIs
import kotlin.test.assertTrue
import kotlin.time.Duration
import kotlin.time.Duration.Companion.milliseconds
import kotlin.time.Duration.Companion.seconds

/**
 * The snapped trim, which lets the cut move back to a sync sample so the export can stream-copy.
 *
 * The trim used here starts inside the clip and between two sync samples, so an implementation that
 * moved the cut to zero, left it where it was asked, or clamped it to the clip's ends would all read
 * differently here.
 *
 * Skipped when the fixtures are absent, since they are generated by host ffmpeg and a machine
 * without it has nothing to cut.
 */
@OptIn(ExperimentalForeignApi::class, ExperimentalFilmstripApi::class, InternalFilmstripApi::class)
class AppleFastTrimTest {
  private val fixtures = NSProcessInfo.processInfo.environment[FIXTURES] as? String

  private val filmstrip = Filmstrip { avFoundationBackend() }

  @Test
  fun `plans an untouched snapped trim as a copy`() =
    runTest(timeout = TIMEOUT) {
      val resolved = trimmed() ?: return@runTest

      resolved.path shouldBe ExportPath.Transmux
      resolved.tracks
        .first()
        .clips
        .single()
        .startsAtKeyFrame shouldBe true
    }

  @Test
  fun `opens the cut on the sync sample at or before the trim`() =
    runTest(timeout = TIMEOUT) {
      val long = fixture(LONG) ?: return@runTest
      val resolved = trimmed() ?: return@runTest

      val cut = resolved.toAvComposition().composition.firstCut(AVMediaTypeVideo) ?: return@runTest
      val opening = sourceTrack(long, AVMediaTypeVideo)?.syncSampleAtOrBefore(TRIM_START)

      cut.start shouldBe opening
      assertTrue(cut.start < TRIM_START, "the cut opened at ${cut.start} rather than earlier than $TRIM_START")
      assertTrue(cut.start > Duration.ZERO, "the cut fell back to the start of the file instead of snapping")
    }

  // The cut moves back to the nearest sync sample, not merely to some earlier one, so nothing
  // between where it landed and where it was asked for can be one either. Probed in the middle of
  // that gap, which an implementation snapping to the wrong side of it would answer differently.
  @Test
  fun `moves the cut no further back than it has to`() =
    runTest(timeout = TIMEOUT) {
      val long = fixture(LONG) ?: return@runTest
      val track = sourceTrack(long, AVMediaTypeVideo) ?: return@runTest
      val opening = track.syncSampleAtOrBefore(TRIM_START) ?: return@runTest

      track.syncSampleAtOrBefore(opening + (TRIM_START - opening) / 2) shouldBe opening
    }

  // The cut has to land on a sample a decoder can open on, not merely on an earlier one.
  @Test
  fun `opens on a sample that is itself a sync sample`() =
    runTest(timeout = TIMEOUT) {
      val long = fixture(LONG) ?: return@runTest
      val track = sourceTrack(long, AVMediaTypeVideo) ?: return@runTest

      val opening = track.syncSampleAtOrBefore(TRIM_START)

      opening shouldBe track.syncSampleAtOrBefore(opening ?: return@runTest)
    }

  // The seam the planner reads through. It settles the opening once and every backend lays what it
  // resolved, so the driver answering anything but the track would move the cut on this backend
  // alone.
  @Test
  fun `answers the planner what the track itself answers`() =
    runTest(timeout = TIMEOUT) {
      val long = fixture(LONG) ?: return@runTest
      val track = sourceTrack(long, AVMediaTypeVideo) ?: return@runTest

      val throughDriver =
        withContext(Dispatchers.Default) {
          driver().syncSampleAtOrBefore(MediaSource.of(long), TRIM_START)
        }

      throughDriver shouldBe track.syncSampleAtOrBefore(TRIM_START)
    }

  @Test
  fun `leaves the end of the cut where it was asked for`() =
    runTest(timeout = TIMEOUT) {
      val resolved = trimmed() ?: return@runTest

      val cut = resolved.toAvComposition().composition.firstCut(AVMediaTypeVideo)

      cut?.end shouldBe TRIM_END
    }

  @Test
  fun `cuts the audio from the same place as the picture`() =
    runTest(timeout = TIMEOUT) {
      val composition = trimmed()?.toAvComposition()?.composition ?: return@runTest

      val video = composition.firstCut(AVMediaTypeVideo)
      val audio = composition.firstCut(AVMediaTypeAudio)

      assertTrue(audio != null, "the copy wrote no audio track to keep in step with the picture")
      audio.start shouldBe video?.start
    }

  // The control. A trim the planner could not route to a copy re-encodes, and a re-encode has no
  // reason to open anywhere but where the caller asked.
  @Test
  fun `cuts exactly where asked when an effect makes it re-encode`() =
    runTest(timeout = TIMEOUT) {
      val long = fixture(LONG) ?: return@runTest
      val graded =
        compositionOf {
          clip(MediaSource.of(long)) {
            trim(TRIM_START, TRIM_END)
            snapWithin(SNAP_WITHIN)
          }
          effects { brightness(1.2f) }
        }
      val resolved = resolved(graded)

      resolved.path shouldBe ExportPath.Transcode
      val cut = resolved.toAvComposition().composition.firstCut(AVMediaTypeVideo)
      cut?.start shouldBe TRIM_START
      cut?.end shouldBe TRIM_END
    }

  // The other control, and the default. A clip that never said the cut may move keeps it, and the
  // trim is then the term that costs the copy.
  @Test
  fun `leaves the cut where it was asked when nothing lets it move`() =
    runTest(timeout = TIMEOUT) {
      val long = fixture(LONG) ?: return@runTest
      val asked = compositionOf { clip(MediaSource.of(long)) { trim(TRIM_START, TRIM_END) } }

      val plan = plan(asked)
      plan.path shouldBe ExportPath.Transcode
      assertTrue(
        CopyBlocker.TrimNotOnSyncSample in plan.copyBlockedBy,
        "the copy was blocked by ${plan.copyBlockedBy} rather than by the trim",
      )

      val resolved = resolved(asked)
      resolved.tracks
        .first()
        .clips
        .single()
        .startsAtKeyFrame shouldBe false
      resolved
        .toAvComposition()
        .composition
        .firstCut(AVMediaTypeVideo)
        ?.start shouldBe TRIM_START
    }

  // The claims above are about the graph. This one is about the file, which is the only place a cut
  // that snapped in the composition and not in the output would show.
  @Test
  fun `writes a file that runs from where the copy opened`() =
    runTest(timeout = TIMEOUT) {
      val long = fixture(LONG) ?: return@runTest
      val opening = sourceTrack(long, AVMediaTypeVideo)?.syncSampleAtOrBefore(TRIM_START) ?: return@runTest
      val output = NSTemporaryDirectory() + "filmstrip-apple-fast-trim.mp4"

      val written =
        withContext(Dispatchers.Default) {
          filmstrip
            .export(snapping(long), ExportSpec(), MediaSink.of(output))
            .toList()
            .last()
        }

      val success = assertIs<ExportStatus.Success>(written)
      val length = success.info.duration
      assertTrue(
        (length - (TRIM_END - opening)).absoluteValue <= FRAME,
        "the file runs $length, and the copy opened at $opening so it should run ${TRIM_END - opening}",
      )
      NSFileManager.defaultManager.removeItemAtPath(output, error = null)
    }

  /**
   * The trimmed edit every copy claim reads, which lets the cut move far enough back to reach the
   * fixture's sync samples.
   */
  private fun snapping(source: String): EditComposition =
    compositionOf {
      clip(MediaSource.of(source)) {
        trim(TRIM_START, TRIM_END)
        snapWithin(SNAP_WITHIN)
      }
    }

  private suspend fun trimmed(): ResolvedComposition? {
    val long = fixture(LONG) ?: return null
    return resolved(snapping(long))
  }

  /**
   * The graph an export of [composition] runs, negotiated through the engine the export itself goes
   * through.
   */
  private suspend fun resolved(composition: EditComposition): ResolvedComposition =
    withContext(Dispatchers.Default) {
      when (val result = engine().resolve(composition, ExportSpec())) {
        is ResolveResult.Refused -> error(result.error.message)
        is ResolveResult.Resolved -> result.composition
      }
    }

  private suspend fun plan(composition: EditComposition): ExportPlan =
    withContext(Dispatchers.Default) {
      when (val verdict = filmstrip.plan(composition, ExportSpec())) {
        is Verdict.Capable -> verdict.plan
        is Verdict.Degraded -> verdict.plan
        is Verdict.Incapable -> error("$verdict")
      }
    }

  private fun engine() =
    ComponentRegistry.Builder().add(BuiltInEffectResolver()).build().let { components ->
      avFoundationExportEngine(chainedProber(components), components.effectResolvers)
    }

  private fun driver() =
    AvFoundationDriver(chainedProber(ComponentRegistry.Builder().add(BuiltInEffectResolver()).build()))

  private fun sourceTrack(
    path: String,
    mediaType: String?,
  ): AVAssetTrack? =
    AVURLAsset(uRL = NSURL.fileURLWithPath(path), options = null)
      .tracksWithMediaType(mediaType)
      .firstOrNull() as? AVAssetTrack

  private fun fixture(name: String): String? {
    val directory = fixtures ?: return null
    val path = "$directory/$name"
    return path.takeIf { NSFileManager.defaultManager.fileExistsAtPath(it) }
  }

  private companion object {
    const val FIXTURES = "FILMSTRIP_FIXTURES"
    const val LONG = "apple_export_long.mp4"

    val TIMEOUT = 2.seconds * 60

    // Inside the twelve second fixture and between two of its sync samples, which sit a second
    // apart, so the snap has somewhere to move to and the clip has room either side of it.
    val TRIM_START = 3_500.milliseconds
    val TRIM_END = 7.seconds

    // How far the cut may move. The fixture's sync samples sit a second apart, so this reaches the
    // one before TRIM_START.
    val SNAP_WITHIN = 2.seconds

    // A frame of the fixture, which is what the written duration can honestly differ by.
    val FRAME = 34.milliseconds
  }
}

/**
 * Where the first segment of this asset's [mediaType] track was cut from the source.
 */
@OptIn(ExperimentalForeignApi::class)
private fun AVAsset.firstCut(mediaType: String?): SourceCut? {
  val track = tracksWithMediaType(mediaType).firstOrNull() as? AVAssetTrack ?: return null
  val segment = track.segments.firstOrNull() as? AVAssetTrackSegment ?: return null

  return segment.timeMapping.useContents {
    SourceCut(source.start.readValue().toDuration(), source.duration.readValue().toDuration())
  }
}

private class SourceCut(
  val start: Duration,
  duration: Duration,
) {
  val end: Duration = start + duration
}
