package dev.jordond.filmstrip.avfoundation

import dev.jordond.filmstrip.CapabilitiesResult
import dev.jordond.filmstrip.ComponentRegistry
import dev.jordond.filmstrip.ExperimentalFilmstripApi
import dev.jordond.filmstrip.Filmstrip
import dev.jordond.filmstrip.InternalFilmstripApi
import dev.jordond.filmstrip.avfoundation.internal.copyFormatDescription
import dev.jordond.filmstrip.edit.AudioLevel
import dev.jordond.filmstrip.edit.AudioSpec
import dev.jordond.filmstrip.edit.EditComposition
import dev.jordond.filmstrip.edit.TimeRange
import dev.jordond.filmstrip.edit.TrackContent
import dev.jordond.filmstrip.edit.compositionOf
import dev.jordond.filmstrip.effects.color.brightness
import dev.jordond.filmstrip.effects.color.contrast
import dev.jordond.filmstrip.effects.geometry.crop
import dev.jordond.filmstrip.effects.geometry.scale
import dev.jordond.filmstrip.export.AdjustmentKind
import dev.jordond.filmstrip.export.ExportError
import dev.jordond.filmstrip.export.ExportPath
import dev.jordond.filmstrip.export.ExportSpec
import dev.jordond.filmstrip.export.ExportStatus
import dev.jordond.filmstrip.export.Verdict
import dev.jordond.filmstrip.export.VideoCodec
import dev.jordond.filmstrip.geometry.AspectRatio
import dev.jordond.filmstrip.geometry.Fill
import dev.jordond.filmstrip.geometry.Fit
import dev.jordond.filmstrip.geometry.Size
import dev.jordond.filmstrip.media.ImageSource
import dev.jordond.filmstrip.media.MediaInfo
import dev.jordond.filmstrip.media.MediaSink
import dev.jordond.filmstrip.media.MediaSource
import dev.jordond.filmstrip.media.chainedProber
import dev.jordond.filmstrip.test.ToneAnalysis
import dev.jordond.filmstrip.transform.internal.ResolveResult
import dev.jordond.filmstrip.transform.internal.ResolvedClip
import dev.jordond.filmstrip.transform.internal.ResolvedComposition
import dev.jordond.filmstrip.transform.internal.ResolvedGain
import io.kotest.matchers.shouldBe
import kotlinx.cinterop.ExperimentalForeignApi
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.cancelAndJoin
import kotlinx.coroutines.flow.toList
import kotlinx.coroutines.launch
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.withContext
import platform.AVFoundation.AVAssetTrack
import platform.AVFoundation.AVMediaTypeVideo
import platform.AVFoundation.AVURLAsset
import platform.AVFoundation.tracksWithMediaType
import platform.CoreFoundation.CFRelease
import platform.CoreFoundation.CFRetain
import platform.CoreMedia.CMFormatDescriptionGetExtension
import platform.CoreMedia.kCMFormatDescriptionExtension_FormatName
import platform.Foundation.CFBridgingRelease
import platform.Foundation.NSFileManager
import platform.Foundation.NSProcessInfo
import platform.Foundation.NSTemporaryDirectory
import platform.Foundation.NSURL
import kotlin.math.abs
import kotlin.test.Test
import kotlin.test.assertIs
import kotlin.test.assertNull
import kotlin.test.assertTrue
import kotlin.time.Duration
import kotlin.time.Duration.Companion.milliseconds
import kotlin.time.Duration.Companion.seconds

/**
 * The end-to-end pass over real clips, real AVFoundation, real VideoToolbox and a real file, read
 * back with the prober.
 *
 * Skipped when the fixtures are absent, since they are generated by host ffmpeg
 * and a machine without it has nothing to export from.
 */
@OptIn(ExperimentalForeignApi::class, ExperimentalFilmstripApi::class, InternalFilmstripApi::class)
class AppleExportTest {
  private val fixtures = NSProcessInfo.processInfo.environment[FIXTURES] as? String

  private val filmstrip = Filmstrip { avFoundationBackend() }

  @Test
  fun `reports what the encoders can do`() =
    runTest(timeout = TIMEOUT) {
      val result = withContext(Dispatchers.Default) { filmstrip.capabilities() }
      val capabilities = assertIs<CapabilitiesResult.Success>(result).capabilities

      assertTrue(capabilities.video.isNotEmpty(), "expected at least one video encoder")
      if (isSimulator()) {
        // The simulator has no hardware video encode path at all, so VideoToolbox reports every
        // encoder as software there. That is an environment limit, not a finding about the
        // mechanism, so it is reported rather than dressed up as a failure. Run macosArm64Test for
        // the real claim.
        println("skipping the hardware assertion on the simulator, which has no hardware encoder")
      } else {
        assertTrue(capabilities.video.all { it.isHardwareAccelerated == true }, "VideoToolbox encoders are hardware")
      }
      capabilities.audio
        .single()
        .codec.name shouldBe "Aac"

      // This machine's own answer varies with its silicon, so this only checks the probe is wired
      // to something real: a claimed HDR encoder has to be one this device actually lists.
      if (capabilities.supportsHdrEncoding) {
        assertTrue(
          capabilities.video.any { it.codec == VideoCodec.Hevc },
          "HDR support was claimed for a codec this device does not list",
        )
      }
    }

  // One clip, trimmed, scaled, written and read back at the size the plan promised.
  @Test
  fun `exports one clip trimmed and scaled`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest

      val composition =
        compositionOf {
          clip(MediaSource.of(landscape)) { trim(500.milliseconds, 1_500.milliseconds) }
        }

      val output = temporaryPath("trimmed")
      val success = exported(composition, ExportSpec(targetHeight = 240), output)

      success.info.video!!.displaySize shouldBe Size(426, 240)
      assertTrue(success.info.duration in 800.milliseconds..1_300.milliseconds, "duration was ${success.info.duration}")
      assertTrue(success.info.audio != null, "the audio track did not survive")

      remove(output)
    }

  @Test
  fun `concatenates clips of differing sizes onto one output frame`() =
    runTest(timeout = TIMEOUT) {
      val first = fixture("apple_export_a.mp4") ?: return@runTest
      val second = fixture("apple_export_b.mp4") ?: return@runTest

      val composition =
        compositionOf {
          clip(MediaSource.of(first)) { trim(0.seconds, 1.seconds) }
          clip(MediaSource.of(second)) { trim(0.seconds, 1.seconds) }
        }

      val output = temporaryPath("concat")
      val success = exported(composition, ExportSpec(targetHeight = 240), output)

      success.info.video!!.displaySize shouldBe Size(426, 240)
      assertTrue(
        success.info.duration in 1_800.milliseconds..2_300.milliseconds,
        "duration was ${success.info.duration}",
      )

      remove(output)
    }

  @Test
  fun `reframes a landscape clip to portrait`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest

      val composition =
        compositionOf {
          clip(MediaSource.of(landscape)) { trim(0.seconds, 1.seconds) }
          effects { crop(AspectRatio.Portrait, Fit.Crop) }
        }

      val output = temporaryPath("reframe")
      val success = exported(composition, ExportSpec(targetHeight = 640), output)

      val size = success.info.video!!.displaySize
      assertTrue(size.height > size.width, "expected a portrait frame, got $size")

      remove(output)
    }

  @Test
  fun `letterboxes and does not distort when the aspect does not match`() =
    runTest(timeout = TIMEOUT) {
      val portrait = fixture("apple_export_portrait.mp4") ?: return@runTest

      val composition =
        compositionOf {
          clip(MediaSource.of(portrait)) { trim(0.seconds, 1.seconds) }
          effects { scale(240, Fit.Contain) }
        }

      val output = temporaryPath("letterbox")
      val success = exported(composition, ExportSpec(), output)

      // Contain keeps the source aspect and writes the bars, so the frame stays the shape the clip
      // was instead of being stretched into the output's.
      success.info.video!!.displaySize shouldBe Size(134, 240)

      remove(output)
    }

  @Test
  fun `fills the letterbox bars with a solid colour`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest
      val teal = Triple(0x11, 0xC2, 0xAA)

      val composition =
        compositionOf {
          clip(MediaSource.of(landscape)) { trim(0.seconds, 1.seconds) }
          fill(Fill.Solid(teal.toArgb()))
          effects { crop(AspectRatio.Square, Fit.Contain) }
        }

      val output = temporaryPath("solid-fill")
      exported(composition, ExportSpec(), output)

      assertClose(samplePixel(output, 0.5f, 0.05f), teal, "top bar")
      assertClose(samplePixel(output, 0.5f, 0.95f), teal, "bottom bar")

      remove(output)
    }

  // The fill-paint-order regression: a composition brightness must not reach a bar it was not
  // given a colour for, whatever it does to the clip's own pixels.
  @Test
  fun `a composition brightness leaves a solid fill's bars untouched`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest
      val teal = Triple(0x11, 0xC2, 0xAA)

      suspend fun exportedWith(
        name: String,
        factor: Float?,
      ): String {
        val composition =
          compositionOf {
            clip(MediaSource.of(landscape)) { trim(0.seconds, 1.seconds) }
            fill(Fill.Solid(teal.toArgb()))
            effects {
              crop(AspectRatio.Square, Fit.Contain)
              if (factor != null) brightness(factor)
            }
          }
        val output = temporaryPath("solid-fill-brightness-$name")
        exported(composition, ExportSpec(), output)
        return output
      }

      val plain = exportedWith("plain", null)
      val dimmed = exportedWith("dimmed", 0.5f)

      assertClose(samplePixel(dimmed, 0.5f, 0.05f), teal, "top bar")
      assertClose(samplePixel(dimmed, 0.5f, 0.95f), teal, "bottom bar")

      val fullCentre = luminance(samplePixel(plain, 0.5f, 0.5f))
      val dimCentre = luminance(samplePixel(dimmed, 0.5f, 0.5f))
      val ratio = dimCentre.toFloat() / fullCentre.toFloat()
      assertTrue(
        ratio in 0.35f..0.65f,
        "expected the centre near half brightness, got $ratio ($fullCentre -> $dimCentre)",
      )

      remove(plain)
      remove(dimmed)
    }

  // The same claim for the half of a matrix a brightness does not have. A contrast carries a bias,
  // Core Image holds the frame premultiplied, and an offset landing where the picture has no alpha
  // is exactly what would tint the bar the fill was given to own. The clip is a flat photo, so the
  // centre is a colour the effect is predicted to move rather than one that merely differs.
  @Test
  fun `a composition contrast leaves a solid fill's bars untouched`() =
    runTest(timeout = TIMEOUT) {
      val teal = Triple(0x11, 0xC2, 0xAA)

      suspend fun exportedWith(
        name: String,
        factor: Float?,
      ): String {
        val composition =
          compositionOf {
            image(ImageSource.of(photoFile()), PHOTO)
            fill(Fill.Solid(teal.toArgb()))
            effects {
              crop(AspectRatio.Square, Fit.Contain)
              if (factor != null) contrast(factor)
            }
          }
        val output = temporaryPath("solid-fill-contrast-$name")
        exported(composition, ExportSpec(), output)
        return output
      }

      val plain = exportedWith("plain", null)
      val firmer = exportedWith("firmer", FIRMER)

      val graded = frameOf(firmer, PHOTO * MIDDLE)
      assertClose(graded.average(0.5f, 0.05f), teal, "top bar")
      assertClose(graded.average(0.5f, 0.95f), teal, "bottom bar")

      val before = frameOf(plain, PHOTO * MIDDLE).average(0.5f, 0.5f)
      val after = graded.average(0.5f, 0.5f)
      assertTrue(
        distance(before, after) > COLOR_TOLERANCE,
        "the contrast never reached the picture, which read $before plain and $after graded",
      )

      remove(plain)
      remove(firmer)
    }

  // Nothing here authors a fill, so this pins the default against a regression: the bars stay
  // black, the way every export wrote them before a fill could be chosen.
  @Test
  fun `leaves the letterbox bars black by default`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest

      val composition =
        compositionOf {
          clip(MediaSource.of(landscape)) { trim(0.seconds, 1.seconds) }
          effects { crop(AspectRatio.Square, Fit.Contain) }
        }

      val output = temporaryPath("black-fill")
      exported(composition, ExportSpec(), output)

      assertClose(samplePixel(output, 0.5f, 0.05f), BLACK, "top bar")
      assertClose(samplePixel(output, 0.5f, 0.95f), BLACK, "bottom bar")

      remove(output)
    }

  @Test
  fun `blurs the letterbox bars from the clip's own frame`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest

      val composition =
        compositionOf {
          clip(MediaSource.of(landscape)) { trim(0.seconds, 1.seconds) }
          fill(Fill.Blur)
          effects { crop(AspectRatio.Square, Fit.Contain) }
        }

      val output = temporaryPath("blurred-fill")
      exported(composition, ExportSpec(), output)

      val near = samplePixel(output, 0.15f, 0.05f)
      val far = samplePixel(output, 0.85f, 0.05f)

      assertTrue(near != BLACK, "expected a blurred bar, got black")
      assertTrue(distance(near, far) > COLOR_TOLERANCE, "expected the blur to vary across the bar, got $near and $far")

      remove(output)
    }

  // The blur only ever reaches the bars, never the clip's own pixels. Comparing the centre against
  // the same composition exported with a solid fill instead is what proves that: nothing else here
  // tells the two exports apart, so a centre that still matches means the composite never covered
  // the clip.
  @Test
  fun `keeps the clip sharp under a blurred fill`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest

      suspend fun exportedWith(fill: Fill): String {
        val composition =
          compositionOf {
            clip(MediaSource.of(landscape)) { trim(0.seconds, 1.seconds) }
            fill(fill)
            effects { crop(AspectRatio.Square, Fit.Contain) }
          }
        val output = temporaryPath("blurred-sharp-${fill::class.simpleName}")
        exported(composition, ExportSpec(), output)
        return output
      }

      val blurred = exportedWith(Fill.Blur)
      val reference = exportedWith(Fill.Black)

      assertClose(samplePixel(blurred, 0.5f, 0.5f), samplePixel(reference, 0.5f, 0.5f), "clip centre")

      remove(blurred)
      remove(reference)
    }

  // dim is documented as a multiply, not an offset, so half dim should land the background
  // roughly halfway to black. An endpoint alone would not catch an offset standing in for a
  // multiply, since both reach black at dim = 1.
  @Test
  fun `dims the letterbox bars proportionally`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest

      suspend fun exportedWith(
        name: String,
        fill: Fill,
      ): String {
        val composition =
          compositionOf {
            clip(MediaSource.of(landscape)) { trim(0.seconds, 1.seconds) }
            fill(fill)
            effects { crop(AspectRatio.Square, Fit.Contain) }
          }
        val output = temporaryPath("dim-$name")
        exported(composition, ExportSpec(), output)
        return output
      }

      val undimmed = exportedWith("undimmed", Fill.Blur)
      val halfDimmed = exportedWith("half", Fill.Blurred(dim = 0.5f))

      val full = samplePixel(undimmed, 0.15f, 0.05f)
      val half = samplePixel(halfDimmed, 0.15f, 0.05f)
      val ratio = luminance(half).toFloat() / luminance(full).toFloat()

      assertTrue(ratio in 0.35f..0.65f, "expected half dim near half brightness, got $ratio ($full -> $half)")

      remove(undimmed)
      remove(halfDimmed)
    }

  // Crop covers the frame itself, so the bars a Contain fit would need never open up. Sampling both
  // edges with a loud fill chosen is what proves it costs nothing when there is nowhere for it to
  // show.
  @Test
  fun `writes no bars when the fill cannot be seen`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest
      val magenta = Triple(0xFF, 0x00, 0xFF)

      val composition =
        compositionOf {
          clip(MediaSource.of(landscape)) { trim(0.seconds, 1.seconds) }
          fill(Fill.Solid(magenta.toArgb()))
          // resolved.fit, which the final pin to the output frame reads, only ever comes from a
          // Scale effect's own fit. The crop alone would leave it defaulted to Contain.
          effects {
            crop(AspectRatio.Square, Fit.Crop)
            scale(300, Fit.Crop)
          }
        }

      val output = temporaryPath("crop-fill")
      exported(composition, ExportSpec(), output)

      assertTrue(
        distance(samplePixel(output, 0.5f, 0.02f), magenta) > COLOR_TOLERANCE,
        "the fill leaked into the top edge",
      )
      assertTrue(
        distance(samplePixel(output, 0.5f, 0.98f), magenta) > COLOR_TOLERANCE,
        "the fill leaked into the bottom edge",
      )

      remove(output)
    }

  /**
   * The plan claims a passthrough, so the file has to prove one ran.
   *
   * An encoder stamps its own name into the format description, so the source's survives a copy and
   * not a re-encode. The trim is the control: it is the same export down to the path the planner
   * picks, and a reader that always answered null would pass the first claim on its own. It cuts
   * off a sync sample and says nothing about moving, which is what leaves the copy out of reach.
   */
  @Test
  fun `copies the streams across when nothing touches them`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest
      val source = formatName(landscape)
      assertTrue(source != null, "the fixture's own format description could not be read")

      val output = temporaryPath("transmux")
      val composition = compositionOf { clip(MediaSource.of(landscape)) }
      val plan = assertIs<Verdict.Capable>(filmstrip.plan(composition, ExportSpec())).plan
      plan.path shouldBe ExportPath.Transmux
      exported(composition, ExportSpec(), output)
      formatName(output) shouldBe source

      val reEncoded = temporaryPath("transcode")
      val trimmed =
        compositionOf {
          clip(MediaSource.of(landscape)) { trim(500.milliseconds, 1.seconds) }
        }
      val control = assertIs<Verdict.Capable>(filmstrip.plan(trimmed, ExportSpec())).plan
      control.path shouldBe ExportPath.Transcode
      exported(trimmed, ExportSpec(), reEncoded)
      assertTrue(formatName(reEncoded) != source, "the trimmed export passed the source's format off as its own")

      remove(output)
      remove(reEncoded)
    }

  @Test
  fun `writes a silent track when a clip is muted`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest

      val composition =
        compositionOf {
          clip(MediaSource.of(landscape)) {
            trim(0.seconds, 1.seconds)
            audio(AudioLevel.Mute)
          }
        }

      val output = temporaryPath("muted")
      val success = exported(composition, ExportSpec(targetHeight = 240), output)

      // Mute keeps the track and writes silence into it, which is a different operation from
      // dropping it.
      assertTrue(success.info.audio != null, "the muted track was dropped and not silenced")

      remove(output)
    }

  // The whole point of AudioSpec.AudioOnly is a file with no video track, so an assertion that only
  // checked the audio survived would pass even if a full video track were written alongside it.
  @Test
  fun `writes an audio track and drops video when the composition is audio-only`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest

      val composition =
        compositionOf {
          clip(MediaSource.of(landscape)) { trim(0.seconds, 1.seconds) }
          audio(AudioSpec.AudioOnly)
        }

      val output = temporaryPath("audio-only")
      val success = exported(composition, ExportSpec(), output)

      val audio = success.info.audio
      assertTrue(audio != null, "the audio track did not survive")
      assertTrue(audio.sampleRate > 0, "expected a sane sample rate, got ${audio.sampleRate}")
      assertNull(success.info.video, "AudioSpec.AudioOnly must not leave a video track behind")
      assertTrue(success.info.duration in 800.milliseconds..1_300.milliseconds, "duration was ${success.info.duration}")

      remove(output)
    }

  /**
   * The mix, read back off a real exported file rather than off the graph that was handed to the
   * writer.
   *
   * The bed carries the one tone no other fixture does, so a level measured at 880 Hz belongs to it
   * and to nothing else. It is trimmed shorter than the composition and held off past zero, which is
   * what makes the offset and the loop separable: 880 Hz has to be absent before the bed opens, and
   * present again inside a pass the loop had to lay down to reach.
   *
   * Levels are compared as a ratio against the primary's own tone in the same window, so the
   * amplitude the fixtures were generated at and whatever AAC did to the output both divide out. An
   * absolute threshold would be pinning the fixture generator rather than the mix.
   */
  @Test
  fun `mixes a looping bed under the primary at the gain the plan folded`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest
      val bed = fixture("tone_bed_880.mp4") ?: return@runTest

      val composition =
        compositionOf {
          clip(MediaSource.of(landscape))
          track(TrackContent.Audio) {
            clip(MediaSource.of(bed)) { trim(Duration.ZERO, BED_PASS) }
            audio(AudioLevel.Volume(BED_VOLUME))
            startAt(BED_START)
            looping()
          }
        }

      val spec = ExportSpec(targetHeight = 240)
      val resolved = resolved(composition, spec)
      val bedTrack = resolved.tracks.single { it.content == TrackContent.Audio }
      val primaryTrack = resolved.tracks.single { it.content != TrackContent.Audio }
      val primaryClip = primaryTrack.clips.single()

      // The plan holds one clip per pass, so which pass the window's middle lands in is read off
      // the laid list rather than worked out from the bed's own length.
      val middle = LOOPED + WINDOW / 2
      val pass = bedTrack.clips.indexOfLast { it.span.start <= middle }
      assertTrue(pass >= 1, "the window at $middle sits in pass ${pass + 1}, which the loop never had to lay down")
      val bedClip = bedTrack.clips[pass]

      val output = temporaryPath("audio-bed")
      exported(composition, spec, output)
      val audio = audioOf(output)

      val primaryTone = audio.toneOver(LOOPED, WINDOW, PRIMARY_HZ)
      val bedTone = audio.toneOver(LOOPED, WINDOW, BED_HZ)
      val beforePrimary = audio.toneOver(BEFORE_BED, WINDOW, PRIMARY_HZ)
      val beforeBed = audio.toneOver(BEFORE_BED, WINDOW, BED_HZ)
      println("440Hz: $beforePrimary before the bed, $primaryTone inside pass ${pass + 1}")
      println("880Hz: $beforeBed before the bed, $bedTone inside pass ${pass + 1}")

      assertTrue(primaryTone > AUDIBLE, "the primary's own tone never reached the file, reading $primaryTone")
      assertTrue(beforePrimary > AUDIBLE, "the window before the bed carries no primary, reading $beforePrimary")
      assertTrue(
        beforeBed < bedTone * SILENT,
        "the bed was audible at $beforeBed before its $BED_START start, against $bedTone once it had opened",
      )

      // The gain the planner folded, read off the plan rather than typed here, and sampled in the
      // pass's own time at the point inside it the window's middle lands on.
      val expected = bedClip.gain.gainAt(middle - bedClip.span.start) / primaryClip.gain.gainAt(middle)
      val measured = bedTone / primaryTone
      assertTrue(
        abs(measured - expected) <= GAIN_TOLERANCE,
        "expected the bed at $expected of the primary, measured $measured ($bedTone against $primaryTone)",
      )

      remove(output)
    }

  /**
   * Every pass the plan laid, read back out of the written file rather than only the one instant
   * the test above reaches.
   *
   * The bed's trim, the track's offset and the composition's length divide into each other nowhere,
   * so the last pass is always cut and no reading sits near a pass boundary. The track's fade covers
   * the whole run instead of restarting each pass, and the readings a quarter and three quarters
   * along it are what separate the two: a fade replayed per pass opens pass two at silence where
   * this one opens well up the ramp.
   */
  @Test
  fun `measures every pass of a looping bed against the gain the plan laid`() =
    runTest(timeout = TIMEOUT) {
      val long = fixture("apple_export_long.mp4") ?: return@runTest
      val bed = fixture("tone_bed_880.mp4") ?: return@runTest

      val composition =
        compositionOf {
          clip(MediaSource.of(long)) { trim(ONE_CLIP_PRIMARY) }
          track(TrackContent.Audio) {
            clip(MediaSource.of(bed)) { trim(ONE_CLIP_TRIM) }
            startAt(ONE_CLIP_START)
            fadeIn(ONE_CLIP_FADE_IN)
            looping()
          }
        }
      val spec = ExportSpec(targetHeight = 240)

      val resolved = resolved(composition, spec)
      val laid = resolved.tracks.single { it.content == TrackContent.Audio }.clips
      val primary =
        resolved.tracks
          .single { it.content != TrackContent.Audio }
          .clips
          .single()

      // Asserted before a sample is measured, so a schedule that laid the wrong passes fails by
      // name rather than as a level that missed.
      laid.map { it.span } shouldBe ONE_CLIP_SPANS
      assertFadeCarriesAcross(laid)

      val output = temporaryPath("loop-passes")
      assertRunsFor(loopExported(composition, spec, output), resolved.duration)

      val audio = audioOf(output)
      val fixtures = fixtureRatio(bed, long)
      ONE_CLIP_READINGS.forEach { (pass, into) ->
        assertBedLevel(audio, fixtures, laid[pass], primary, into, "pass ${pass + 1}")
      }

      // Before the track opens the bed contributes nothing, held to the same tolerance every
      // reading against a folded gain is.
      val before = audio.bedAgainstPrimary(ONE_CLIP_QUIET)
      assertTrue(
        before <= ToneAnalysis.MEASURED_GAIN_TOLERANCE,
        "the bed read $before at $ONE_CLIP_QUIET, before its ${laid.first().span.start} start",
      )

      remove(output)
    }

  /**
   * Two clips on one looping track, told apart by a clip volume rather than by frequency, since
   * there is only one bed tone to go round.
   *
   * Every pass lays A then B, so a reading inside B says the writer kept the two in order and cut
   * the run where the plan did rather than laying each clip on a loop of its own.
   */
  @Test
  fun `keeps two looping clips apart at the levels the plan laid`() =
    runTest(timeout = TIMEOUT) {
      val long = fixture("apple_export_long.mp4") ?: return@runTest
      val bed = fixture("tone_bed_880.mp4") ?: return@runTest

      val composition =
        compositionOf {
          clip(MediaSource.of(long)) { trim(ONE_CLIP_PRIMARY) }
          track(TrackContent.Audio) {
            clip(MediaSource.of(bed)) { trim(TWO_CLIP_A) }
            clip(MediaSource.of(bed)) {
              trim(TWO_CLIP_B)
              audio(AudioLevel.Volume(TWO_CLIP_B_GAIN))
            }
            startAt(TWO_CLIP_START)
            looping()
          }
        }
      val spec = ExportSpec(targetHeight = 240)

      val resolved = resolved(composition, spec)
      val laid = resolved.tracks.single { it.content == TrackContent.Audio }.clips
      val primary =
        resolved.tracks
          .single { it.content != TrackContent.Audio }
          .clips
          .single()
      laid.map { it.span } shouldBe TWO_CLIP_SPANS

      val output = temporaryPath("loop-two-clips")
      assertRunsFor(loopExported(composition, spec, output), resolved.duration)

      val audio = audioOf(output)
      val fixtures = fixtureRatio(bed, long)

      // A writer that stopped after the first pass leaves silence from here on, which the levels
      // below would report as a gain that missed rather than as a bed that never arrived.
      val (firstPass, firstInto) = TWO_CLIP_READINGS.first()
      val present = audio.bedAgainstPrimary(laid[firstPass].span.start + firstInto)
      assertTrue(
        present > ToneAnalysis.MEASURED_GAIN_TOLERANCE,
        "the bed read $present a pass past its own end, where it should still be playing",
      )

      TWO_CLIP_READINGS.forEach { (index, into) ->
        val clip = if (laid[index].sourceIndex == 0) "clip A" else "clip B"
        assertBedLevel(audio, fixtures, laid[index], primary, into, "pass ${index / 2 + 1}, $clip")
      }

      remove(output)
    }

  /**
   * A looping video primary under a longer audio-only track, the case where the loop has to carry
   * pictures as well as samples.
   *
   * Before the passes were laid the writer ran the primary once and left the fill from there on, so
   * the frame inside the third pass is as much of the assertion as the tone is.
   */
  @Test
  fun `loops a video primary under a longer audio track`() =
    runTest(timeout = TIMEOUT) {
      val long = fixture("apple_export_long.mp4") ?: return@runTest
      val bed = fixture("tone_bed_880.mp4") ?: return@runTest

      val composition =
        compositionOf {
          // Written as a track rather than as a primary clip, since only a track carries looping
          // and the builder promotes a leading track to the primary one.
          track {
            clip(MediaSource.of(bed)) { trim(LOOP_VIDEO_TRIM) }
            looping()
          }
          track(TrackContent.Audio) {
            clip(MediaSource.of(long)) { trim(LOOP_VIDEO_TONE) }
          }
        }
      val spec = ExportSpec(targetHeight = 240)

      val resolved = resolved(composition, spec)
      val laid = resolved.tracks.single { it.content != TrackContent.Audio }.clips
      val tone =
        resolved.tracks
          .single { it.content == TrackContent.Audio }
          .clips
          .single()
      laid.map { it.span } shouldBe LOOP_VIDEO_SPANS

      val output = temporaryPath("loop-video")
      assertRunsFor(loopExported(composition, spec, output), resolved.duration)

      val audio = audioOf(output)
      val fixtures = fixtureRatio(bed, long)
      LOOP_VIDEO_READINGS.forEach { (pass, into) ->
        assertBedLevel(audio, fixtures, laid[pass], tone, into, "pass ${pass + 1}")
      }

      // The audio-only track holds one level for the whole composition, so its own tone cannot move
      // across the readings. A track laid only as far as the primary's first pass reads nothing at
      // the later ones, which every ratio above would report as the loop being wrong instead.
      val reference = audio.toneAt(LOOP_VIDEO_REFERENCE, PRIMARY_HZ)
      LOOP_VIDEO_READINGS.forEach { (pass, into) ->
        val at = laid[pass].span.start + into
        val held = audio.toneAt(at, PRIMARY_HZ) / reference
        assertTrue(
          abs(held - 1f) <= ToneAnalysis.MEASURED_GAIN_TOLERANCE,
          "at $at the audio track read $held of the level it holds at $LOOP_VIDEO_REFERENCE",
        )
      }

      // The picture inside a later pass, which is the bed's own pattern rather than the flat colour
      // a composition with nothing laid on it falls back to.
      val (picturePass, pictureInto) = LOOP_VIDEO_READINGS.first()
      val pictureAt = laid[picturePass].span.start + pictureInto
      val fixtureSpread = spreadOf(frameOf(bed, LOOP_VIDEO_TRIM.start + pictureInto))
      val spread = spreadOf(frameOf(output, pictureAt))
      assertTrue(
        spread >= fixtureSpread * PICTURE_SPREAD_FLOOR,
        "the frame at $pictureAt spans $spread against the fixture's own $fixtureSpread, so it carries the fill",
      )

      remove(output)
    }

  @Test
  fun `streams progress that only ever climbs`() =
    runTest(timeout = TIMEOUT) {
      val long = fixture("apple_export_long.mp4") ?: return@runTest

      val composition = compositionOf { clip(MediaSource.of(long)) }
      val output = temporaryPath("progress")
      // 360 divides the fixture's frame exactly, so the plan needs no adjustment and Started is
      // genuinely the first thing a caller sees.
      val statuses =
        withContext(Dispatchers.Default) {
          filmstrip.export(composition, ExportSpec(targetHeight = 360), MediaSink.of(output)).toList()
        }

      assertIs<ExportStatus.Started>(statuses.first())
      val progress = statuses.filterIsInstance<ExportStatus.Progress>()
      assertTrue(progress.isNotEmpty(), "expected at least one progress report")
      progress.zipWithNext().forEach { (first, second) ->
        assertTrue(second.fraction >= first.fraction, "progress went backwards")
      }
      assertIs<ExportStatus.Success>(statuses.last())

      remove(output)
    }

  // Cancelling the collector cancels the export, and everything at the destination belongs to the
  // run, so nothing is left behind.
  @Test
  fun `cancelling the collector leaves no partial file`() =
    runTest(timeout = TIMEOUT) {
      val long = fixture("apple_export_long.mp4") ?: return@runTest
      val output = temporaryPath("cancelled")
      val composition = compositionOf { clip(MediaSource.of(long)) }

      // Cancelled on Started, not after a fixed window. A hardware encode of even a long
      // clip outruns any window worth waiting for, and a run that finished first would be checking
      // that a successful export keeps its file, which is the opposite claim.
      withContext(Dispatchers.Default) {
        val started = CompletableDeferred<Unit>()
        val job =
          launch {
            filmstrip.export(composition, ExportSpec(targetHeight = 360), MediaSink.of(output)).collect {
              if (it is ExportStatus.Started) started.complete(Unit)
            }
          }
        started.await()
        job.cancelAndJoin()
      }

      NSFileManager.defaultManager.fileExistsAtPath(output) shouldBe false
    }

  @Test
  fun `resolves a temporary sink to the file it wrote`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest

      val composition =
        compositionOf {
          clip(MediaSource.of(landscape)) { trim(0.seconds, 1.seconds) }
        }

      val success =
        withContext(Dispatchers.Default) {
          val statuses = filmstrip.export(composition, ExportSpec(targetHeight = 180), MediaSink.Temporary).toList()
          when (val finished = statuses.last()) {
            is ExportStatus.Failure -> error(finished.error.message)
            else -> assertIs<ExportStatus.Success>(finished)
          }
        }

      val path = assertIs<MediaSink.Path>(success.output).path
      NSFileManager.defaultManager.fileExistsAtPath(path) shouldBe true
      remove(path)
    }

  @Test
  fun `reports an unwritable destination and does not start`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest

      val composition = compositionOf { clip(MediaSource.of(landscape)) }
      val statuses =
        withContext(Dispatchers.Default) {
          filmstrip
            .export(composition, ExportSpec(targetHeight = 240), MediaSink.of("/nonexistent/dir/out.mp4"))
            .toList()
        }

      val failure = assertIs<ExportStatus.Failure>(statuses.last())
      assertIs<ExportError.SinkUnwritable>(failure.error)
      // Nothing was opened, so the export never began.
      assertTrue(statuses.none { it is ExportStatus.Started }, "the export started on an unwritable sink")
    }

  @Test
  fun `leaves nothing behind when the export fails`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest
      val output = temporaryPath("leftover")

      val composition = compositionOf { clip(MediaSource.of(landscape)) }
      withContext(Dispatchers.Default) {
        filmstrip.export(composition, ExportSpec(targetHeight = 240), MediaSink.of(output)).toList()
      }
      remove(output)

      NSFileManager.defaultManager.fileExistsAtPath(output) shouldBe false
    }

  private suspend fun exported(
    composition: EditComposition,
    spec: ExportSpec,
    output: String,
  ): ExportStatus.Success =
    withContext(Dispatchers.Default) {
      when (val verdict = filmstrip.plan(composition, spec)) {
        is Verdict.Incapable -> error(verdict.reasons.joinToString { it.message })
        is Verdict.Capable, is Verdict.Degraded -> Unit
      }

      val statuses = filmstrip.export(composition, spec, MediaSink.of(output)).toList()
      when (val finished = statuses.last()) {
        is ExportStatus.Failure -> error(finished.error.message)
        else -> assertIs<ExportStatus.Success>(finished)
      }
    }

  /**
   * Exports [composition] to [output] and hands back what the written file says about itself.
   *
   * Scaling the long fixture to the spec's target height can land between two widths VideoToolbox
   * accepts, which the planner reports as an adjustment and which none of the looping tests
   * measures. That one is let through and every other kind is not.
   */
  private suspend fun loopExported(
    composition: EditComposition,
    spec: ExportSpec,
    output: String,
  ): MediaInfo =
    withContext(Dispatchers.Default) {
      when (val verdict = filmstrip.plan(composition, spec)) {
        is Verdict.Incapable -> {
          error(verdict.reasons.joinToString { it.message })
        }
        is Verdict.Capable -> {
        }
        is Verdict.Degraded -> {
          assertTrue(
            verdict.adjustments.all { it.kind == AdjustmentKind.ResolutionClamped },
            "the plan degraded for more than the frame: ${verdict.adjustments.map { it.message }}",
          )
        }
      }

      val statuses = filmstrip.export(composition, spec, MediaSink.of(output)).toList()
      when (val finished = statuses.last()) {
        is ExportStatus.Failure -> error(finished.error.message)
        else -> assertIs<ExportStatus.Success>(finished).info
      }
    }

  /**
   * Asserts [written] runs for as long as [planned], to within one frame of the output.
   *
   * A looping track that laid its last pass whole rather than cutting it overruns by the rest of
   * that pass, most of a second here, so one frame separates the two without pinning how much
   * padding the writer put at the end.
   */
  private fun assertRunsFor(
    written: MediaInfo,
    planned: Duration,
  ) {
    val frame = 1.seconds / (written.video?.frameRate?.toDouble() ?: OUTPUT_FRAME_RATE)
    val overrun = written.duration - planned
    assertTrue(
      abs(overrun.inWholeMicroseconds) <= frame.inWholeMicroseconds,
      "the file runs for ${written.duration} against the planned $planned, out by $overrun on a $frame frame",
    )
  }

  /**
   * Asserts each of [laid] opens on the gain the pass before it closed on.
   *
   * This is the whole difference between a track fade measured over the run and one replayed every
   * pass, and it is read off the plan rather than out of the file because a fade that restarts is
   * already wrong before anything is encoded.
   */
  private fun assertFadeCarriesAcross(laid: List<ResolvedClip>) {
    laid.zipWithNext { earlier, later ->
      val closed = earlier.gain.gainAt(earlier.duration)
      val opened = later.gain.gainAt(Duration.ZERO)
      assertTrue(
        abs(opened - closed) <= ResolvedGain.PRODUCT_TOLERANCE,
        "a pass opened at $opened where the one before it closed at $closed, so the fade restarted",
      )
    }
  }

  /**
   * Asserts the bed reads at [clip]'s laid gain [into] that clip, against the 440 Hz track's own
   * level at the same instant.
   *
   * Where on the composition clock that lands comes off the laid span rather than being written
   * out here, so the level measured and the gain sampled cannot drift apart. Either curve is
   * measured from zero at its own clip's start, so [against] is sampled at the instant less that
   * clip's own span start.
   */
  private fun assertBedLevel(
    audio: AudioProbe,
    fixtures: Float,
    clip: ResolvedClip,
    against: ResolvedClip,
    into: Duration,
    what: String,
  ) {
    assertTrue(into < clip.duration, "$into runs past $what, which is ${clip.duration} long")
    val at = clip.span.start + into
    val expected = fixtures * (clip.gain.gainAt(into) / against.gain.gainAt(at - against.span.start))
    val measured = audio.bedAgainstPrimary(at)
    assertTrue(
      abs(measured - expected) <= ToneAnalysis.MEASURED_GAIN_TOLERANCE,
      "at $at, $into into $what, the bed read $measured against $expected from the laid gain",
    )
  }

  /**
   * How loud the bed fixture's tone is against the long fixture's, so how loud either was generated
   * divides out of every reading taken from the mix.
   */
  private fun fixtureRatio(
    bed: String,
    primary: String,
  ): Float = audioOf(bed).toneAt(FIXTURE_READING, BED_HZ) / audioOf(primary).toneAt(FIXTURE_READING, PRIMARY_HZ)

  /**
   * The 880 Hz tone measured against the 440 Hz one at the same instant.
   *
   * Every level is read as a ratio of the two because an AAC round trip attenuates the whole mix,
   * and an absolute reading would be pinning the codec rather than the gain.
   */
  private fun AudioProbe.bedAgainstPrimary(at: Duration): Float = toneAt(at, BED_HZ) / toneAt(at, PRIMARY_HZ)

  /**
   * How much of [frequencyHz] the file carries around [at].
   *
   * The window is centred on [at] rather than opened there, because a reading taken across a ramp
   * is the mean gain over the window and a linear ramp's mean sits at its middle. Anchoring the
   * window's start instead would read a fade high by half the window's own rise.
   */
  private fun AudioProbe.toneAt(
    at: Duration,
    frequencyHz: Int,
  ): Float = toneOver(at - TONE_WINDOW / 2, TONE_WINDOW, frequencyHz)

  /**
   * How far apart the lightest and darkest of a grid of samples across [frame] sit.
   *
   * A fill is one flat colour and reads near nothing here, where the fixture's own pattern spans
   * most of the range, so this says whether a frame carries a picture at all. A grid rather than
   * every pixel because a few dozen points already separate a pattern from a flat colour.
   */
  private fun spreadOf(frame: FrameProbe): Int {
    val samples =
      (0 until PICTURE_GRID).flatMap { row ->
        (0 until PICTURE_GRID).map { column ->
          luminance(frame.at((column + HALF) / PICTURE_GRID, (row + HALF) / PICTURE_GRID))
        }
      }
    return samples.max() - samples.min()
  }

  /**
   * The graph an export of [composition] runs, which is where the folded gain a backend consumes
   * lives.
   *
   * Negotiated through the same engine the export goes through, so the curve read here is the curve
   * the writer was handed rather than a second fold of the same levels.
   */
  private suspend fun resolved(
    composition: EditComposition,
    spec: ExportSpec,
  ): ResolvedComposition =
    withContext(Dispatchers.Default) {
      val components = ComponentRegistry.Builder().build()
      val engine = avFoundationExportEngine(chainedProber(components), components.effectResolvers)
      when (val result = engine.resolve(composition, spec)) {
        is ResolveResult.Refused -> error(result.error.message)
        is ResolveResult.Resolved -> result.composition
      }
    }

  private fun fixture(name: String): String? {
    val directory = fixtures ?: return null
    val path = "$directory/$name"
    return path.takeIf { NSFileManager.defaultManager.fileExistsAtPath(it) }
  }

  /**
   * The name the encoder stamped into this file's video format description.
   */
  private fun formatName(path: String): String? {
    val track =
      AVURLAsset(uRL = NSURL.fileURLWithPath(path), options = null)
        .tracksWithMediaType(AVMediaTypeVideo)
        .firstOrNull() as? AVAssetTrack ?: return null
    val format = track.copyFormatDescription() ?: return null

    try {
      val name = CMFormatDescriptionGetExtension(format, kCMFormatDescriptionExtension_FormatName) ?: return null
      return CFBridgingRelease(CFRetain(name)) as? String
    } finally {
      CFRelease(format)
    }
  }

  /**
   * The flat photo the fill's contrast case draws from, written into the temporary directory once.
   */
  private fun photoFile(): String = photoFixture("filmstrip-apple-export-photo", PHOTO_SIZE, PHOTO_COLOR)

  private fun temporaryPath(name: String): String = NSTemporaryDirectory() + "filmstrip-apple-$name.mp4"

  private fun remove(path: String) {
    NSFileManager.defaultManager.removeItemAtPath(path, error = null)
  }

  private fun isSimulator(): Boolean = NSProcessInfo.processInfo.environment[SIMULATOR_DEVICE_NAME] != null

  private companion object {
    const val FIXTURES = "FILMSTRIP_FIXTURES"
    const val SIMULATOR_DEVICE_NAME = "SIMULATOR_DEVICE_NAME"
    val TIMEOUT = 2.seconds * 60
    val BLACK = Triple(0, 0, 0)

    // The photo the contrast case lays over the fill, held long enough to read inside its span
    // rather than on either edge of it.
    val PHOTO = 1.seconds
    const val MIDDLE = 0.4
    val PHOTO_SIZE = Size(640, 360)

    // Mid-range on all three channels, so the gain moves every one of them without any running out
    // of range and clamping to the same answer a broken lowering would give.
    val PHOTO_COLOR = Triple(0x66, 0x99, 0xCC)

    const val FIRMER = 1.5f

    // The tones the fixtures were generated with. Only the bed carries 880Hz, which is what lets a
    // level measured in the mix be attributed to one source.
    const val PRIMARY_HZ = 440
    const val BED_HZ = 880

    // Shorter than the composition, so the bed has to be laid down more than once to cover it.
    val BED_PASS = 500.milliseconds
    val BED_START = 500.milliseconds
    const val BED_VOLUME = 0.5f

    // Long enough to hold hundreds of cycles of either tone, and clear of both ends of the pass it
    // sits in so an encoder's priming cannot drag a neighbouring stretch into the measurement.
    val WINDOW = 250.milliseconds
    val BEFORE_BED = 150.milliseconds
    val LOOPED = 1_100.milliseconds

    // A presence floor rather than a claim about any gain, which is what the ratio makes. Well
    // under the level the fixtures were generated at and well over what a silent stretch reads.
    const val AUDIBLE = 0.02f
    const val SILENT = 0.15f
    const val GAIN_TOLERANCE = 0.05f

    // A hundred milliseconds, eighty-eight cycles of the bed's tone. Long enough for the two
    // frequencies to separate cleanly and short enough to sit well inside one pass.
    val TONE_WINDOW = 100.milliseconds

    // Inside both fixtures, where each holds its own steady tone.
    val FIXTURE_READING = 500.milliseconds

    // The fixtures' own rate, read only when a written file names none.
    const val OUTPUT_FRAME_RATE = 30.0

    // Every length below is shared with the other backends' looping tests, so a lowering that
    // disagrees about a pass fails the same reading in more than one suite. None of them divides
    // evenly into any other, which is what keeps the last pass cut and every reading clear of a
    // pass boundary by more than the measurement window.
    val ONE_CLIP_PRIMARY = TimeRange.of(Duration.ZERO, 7_300.milliseconds)

    // One clip, trimmed off both ends, offset into the composition and looped under it.
    val ONE_CLIP_TRIM = TimeRange.of(200.milliseconds, 1_900.milliseconds)
    val ONE_CLIP_START = 700.milliseconds

    // Long enough to cover the first two passes, so the fade is still climbing where pass two opens
    // and a fade that restarted would read nothing like it.
    val ONE_CLIP_FADE_IN = 3_000.milliseconds
    val ONE_CLIP_SPANS =
      listOf(
        TimeRange.of(700.milliseconds, 2_400.milliseconds),
        TimeRange.of(2_400.milliseconds, 4_100.milliseconds),
        TimeRange.of(4_100.milliseconds, 5_800.milliseconds),
        TimeRange.of(5_800.milliseconds, 7_300.milliseconds),
      )

    // Which laid pass each reading falls in and how far into it, which is what puts it on the
    // composition clock. Taking the instant off the laid span rather than writing it out is what
    // keeps the level measured and the gain sampled at the same place.
    //
    // A quarter and three quarters into the track's fade, then the plateau past it, then the pass
    // the run cut short.
    val ONE_CLIP_READINGS =
      listOf(
        0 to 750.milliseconds,
        1 to 550.milliseconds,
        2 to 400.milliseconds,
        3 to 1_100.milliseconds,
      )

    // Before the track opens, where the mix carries the primary alone.
    val ONE_CLIP_QUIET = 300.milliseconds

    val TWO_CLIP_START = 500.milliseconds
    val TWO_CLIP_A = TimeRange.of(Duration.ZERO, 1_100.milliseconds)
    val TWO_CLIP_B = TimeRange.of(1_400.milliseconds, 2_300.milliseconds)

    // Far enough under clip A to tell the two apart at a glance, and far enough off zero that a
    // clip which arrived muted is not mistaken for it.
    const val TWO_CLIP_B_GAIN = 0.4f
    val TWO_CLIP_SPANS =
      listOf(
        TimeRange.of(500.milliseconds, 1_600.milliseconds),
        TimeRange.of(1_600.milliseconds, 2_500.milliseconds),
        TimeRange.of(2_500.milliseconds, 3_600.milliseconds),
        TimeRange.of(3_600.milliseconds, 4_500.milliseconds),
        TimeRange.of(4_500.milliseconds, 5_600.milliseconds),
        TimeRange.of(5_600.milliseconds, 6_500.milliseconds),
        TimeRange.of(6_500.milliseconds, 7_300.milliseconds),
      )

    // Clip A and clip B inside pass two, clip B inside pass three, then the clip A the run cut.
    val TWO_CLIP_READINGS =
      listOf(
        2 to 500.milliseconds,
        3 to 600.milliseconds,
        5 to 500.milliseconds,
        6 to 500.milliseconds,
      )

    val LOOP_VIDEO_TRIM = TimeRange.of(100.milliseconds, 1_600.milliseconds)
    val LOOP_VIDEO_TONE = TimeRange.of(Duration.ZERO, 5_300.milliseconds)
    val LOOP_VIDEO_SPANS =
      listOf(
        TimeRange.of(Duration.ZERO, 1_500.milliseconds),
        TimeRange.of(1_500.milliseconds, 3_000.milliseconds),
        TimeRange.of(3_000.milliseconds, 4_500.milliseconds),
        TimeRange.of(4_500.milliseconds, 5_300.milliseconds),
      )
    val LOOP_VIDEO_READINGS = listOf(2 to 400.milliseconds, 3 to 400.milliseconds)

    // Inside the first pass, where the audio track's level is read before the loop repeats.
    val LOOP_VIDEO_REFERENCE = 500.milliseconds

    // How much of the fixture's own range a written frame has to span to count as carrying its
    // picture. A flat fill spans almost nothing, so half is generous and still nowhere near it.
    const val PICTURE_SPREAD_FLOOR = 0.5f

    // Points across a frame's width and height, sampled at the middle of each cell.
    const val PICTURE_GRID = 8
    const val HALF = 0.5f
  }
}
