package dev.jordond.filmstrip.avfoundation

import dev.jordond.filmstrip.CapabilitiesResult
import dev.jordond.filmstrip.ComponentRegistry
import dev.jordond.filmstrip.ExperimentalFilmstripApi
import dev.jordond.filmstrip.Filmstrip
import dev.jordond.filmstrip.InternalFilmstripApi
import dev.jordond.filmstrip.avfoundation.internal.copyFormatDescription
import dev.jordond.filmstrip.edit.AudioLevel
import dev.jordond.filmstrip.edit.AudioSpec
import dev.jordond.filmstrip.edit.EditComposition
import dev.jordond.filmstrip.edit.TrackContent
import dev.jordond.filmstrip.edit.compositionOf
import dev.jordond.filmstrip.effects.color.brightness
import dev.jordond.filmstrip.effects.color.contrast
import dev.jordond.filmstrip.effects.geometry.crop
import dev.jordond.filmstrip.effects.geometry.scale
import dev.jordond.filmstrip.export.ExportError
import dev.jordond.filmstrip.export.ExportPath
import dev.jordond.filmstrip.export.ExportSpec
import dev.jordond.filmstrip.export.ExportStatus
import dev.jordond.filmstrip.export.Verdict
import dev.jordond.filmstrip.export.VideoCodec
import dev.jordond.filmstrip.geometry.AspectRatio
import dev.jordond.filmstrip.geometry.Fill
import dev.jordond.filmstrip.geometry.Fit
import dev.jordond.filmstrip.geometry.Size
import dev.jordond.filmstrip.media.ImageSource
import dev.jordond.filmstrip.media.MediaSink
import dev.jordond.filmstrip.media.MediaSource
import dev.jordond.filmstrip.media.chainedProber
import dev.jordond.filmstrip.transform.internal.ResolveResult
import dev.jordond.filmstrip.transform.internal.ResolvedComposition
import io.kotest.matchers.shouldBe
import kotlinx.cinterop.ExperimentalForeignApi
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.cancelAndJoin
import kotlinx.coroutines.flow.toList
import kotlinx.coroutines.launch
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.withContext
import platform.AVFoundation.AVAssetTrack
import platform.AVFoundation.AVMediaTypeVideo
import platform.AVFoundation.AVURLAsset
import platform.AVFoundation.tracksWithMediaType
import platform.CoreFoundation.CFRelease
import platform.CoreFoundation.CFRetain
import platform.CoreMedia.CMFormatDescriptionGetExtension
import platform.CoreMedia.kCMFormatDescriptionExtension_FormatName
import platform.Foundation.CFBridgingRelease
import platform.Foundation.NSFileManager
import platform.Foundation.NSProcessInfo
import platform.Foundation.NSTemporaryDirectory
import platform.Foundation.NSURL
import kotlin.math.abs
import kotlin.test.Test
import kotlin.test.assertIs
import kotlin.test.assertNull
import kotlin.test.assertTrue
import kotlin.time.Duration
import kotlin.time.Duration.Companion.milliseconds
import kotlin.time.Duration.Companion.seconds

/**
 * The end-to-end pass over real clips, real AVFoundation, real VideoToolbox and a real file, read
 * back with the prober.
 *
 * Skipped when the fixtures are absent, since they are generated by host ffmpeg
 * and a machine without it has nothing to export from.
 */
@OptIn(ExperimentalForeignApi::class, ExperimentalFilmstripApi::class, InternalFilmstripApi::class)
class AppleExportTest {
  private val fixtures = NSProcessInfo.processInfo.environment[FIXTURES] as? String

  private val filmstrip = Filmstrip { avFoundationBackend() }

  @Test
  fun `reports what the encoders can do`() =
    runTest(timeout = TIMEOUT) {
      val result = withContext(Dispatchers.Default) { filmstrip.capabilities() }
      val capabilities = assertIs<CapabilitiesResult.Success>(result).capabilities

      assertTrue(capabilities.video.isNotEmpty(), "expected at least one video encoder")
      if (isSimulator()) {
        // The simulator has no hardware video encode path at all, so VideoToolbox reports every
        // encoder as software there. That is an environment limit, not a finding about the
        // mechanism, so it is reported rather than dressed up as a failure. Run macosArm64Test for
        // the real claim.
        println("skipping the hardware assertion on the simulator, which has no hardware encoder")
      } else {
        assertTrue(capabilities.video.all { it.isHardwareAccelerated == true }, "VideoToolbox encoders are hardware")
      }
      capabilities.audio
        .single()
        .codec.name shouldBe "Aac"

      // This machine's own answer varies with its silicon, so this only checks the probe is wired
      // to something real: a claimed HDR encoder has to be one this device actually lists.
      if (capabilities.supportsHdrEncoding) {
        assertTrue(
          capabilities.video.any { it.codec == VideoCodec.Hevc },
          "HDR support was claimed for a codec this device does not list",
        )
      }
    }

  // One clip, trimmed, scaled, written and read back at the size the plan promised.
  @Test
  fun `exports one clip trimmed and scaled`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest

      val composition =
        compositionOf {
          clip(MediaSource.of(landscape)) { trim(500.milliseconds, 1_500.milliseconds) }
        }

      val output = temporaryPath("trimmed")
      val success = exported(composition, ExportSpec(targetHeight = 240), output)

      success.info.video!!.displaySize shouldBe Size(426, 240)
      assertTrue(success.info.duration in 800.milliseconds..1_300.milliseconds, "duration was ${success.info.duration}")
      assertTrue(success.info.audio != null, "the audio track did not survive")

      remove(output)
    }

  @Test
  fun `concatenates clips of differing sizes onto one output frame`() =
    runTest(timeout = TIMEOUT) {
      val first = fixture("apple_export_a.mp4") ?: return@runTest
      val second = fixture("apple_export_b.mp4") ?: return@runTest

      val composition =
        compositionOf {
          clip(MediaSource.of(first)) { trim(0.seconds, 1.seconds) }
          clip(MediaSource.of(second)) { trim(0.seconds, 1.seconds) }
        }

      val output = temporaryPath("concat")
      val success = exported(composition, ExportSpec(targetHeight = 240), output)

      success.info.video!!.displaySize shouldBe Size(426, 240)
      assertTrue(
        success.info.duration in 1_800.milliseconds..2_300.milliseconds,
        "duration was ${success.info.duration}",
      )

      remove(output)
    }

  @Test
  fun `reframes a landscape clip to portrait`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest

      val composition =
        compositionOf {
          clip(MediaSource.of(landscape)) { trim(0.seconds, 1.seconds) }
          effects { crop(AspectRatio.Portrait, Fit.Crop) }
        }

      val output = temporaryPath("reframe")
      val success = exported(composition, ExportSpec(targetHeight = 640), output)

      val size = success.info.video!!.displaySize
      assertTrue(size.height > size.width, "expected a portrait frame, got $size")

      remove(output)
    }

  @Test
  fun `letterboxes and does not distort when the aspect does not match`() =
    runTest(timeout = TIMEOUT) {
      val portrait = fixture("apple_export_portrait.mp4") ?: return@runTest

      val composition =
        compositionOf {
          clip(MediaSource.of(portrait)) { trim(0.seconds, 1.seconds) }
          effects { scale(240, Fit.Contain) }
        }

      val output = temporaryPath("letterbox")
      val success = exported(composition, ExportSpec(), output)

      // Contain keeps the source aspect and writes the bars, so the frame stays the shape the clip
      // was instead of being stretched into the output's.
      success.info.video!!.displaySize shouldBe Size(134, 240)

      remove(output)
    }

  @Test
  fun `fills the letterbox bars with a solid colour`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest
      val teal = Triple(0x11, 0xC2, 0xAA)

      val composition =
        compositionOf {
          clip(MediaSource.of(landscape)) { trim(0.seconds, 1.seconds) }
          fill(Fill.Solid(teal.toArgb()))
          effects { crop(AspectRatio.Square, Fit.Contain) }
        }

      val output = temporaryPath("solid-fill")
      exported(composition, ExportSpec(), output)

      assertClose(samplePixel(output, 0.5f, 0.05f), teal, "top bar")
      assertClose(samplePixel(output, 0.5f, 0.95f), teal, "bottom bar")

      remove(output)
    }

  // The fill-paint-order regression: a composition brightness must not reach a bar it was not
  // given a colour for, whatever it does to the clip's own pixels.
  @Test
  fun `a composition brightness leaves a solid fill's bars untouched`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest
      val teal = Triple(0x11, 0xC2, 0xAA)

      suspend fun exportedWith(
        name: String,
        factor: Float?,
      ): String {
        val composition =
          compositionOf {
            clip(MediaSource.of(landscape)) { trim(0.seconds, 1.seconds) }
            fill(Fill.Solid(teal.toArgb()))
            effects {
              crop(AspectRatio.Square, Fit.Contain)
              if (factor != null) brightness(factor)
            }
          }
        val output = temporaryPath("solid-fill-brightness-$name")
        exported(composition, ExportSpec(), output)
        return output
      }

      val plain = exportedWith("plain", null)
      val dimmed = exportedWith("dimmed", 0.5f)

      assertClose(samplePixel(dimmed, 0.5f, 0.05f), teal, "top bar")
      assertClose(samplePixel(dimmed, 0.5f, 0.95f), teal, "bottom bar")

      val fullCentre = luminance(samplePixel(plain, 0.5f, 0.5f))
      val dimCentre = luminance(samplePixel(dimmed, 0.5f, 0.5f))
      val ratio = dimCentre.toFloat() / fullCentre.toFloat()
      assertTrue(
        ratio in 0.35f..0.65f,
        "expected the centre near half brightness, got $ratio ($fullCentre -> $dimCentre)",
      )

      remove(plain)
      remove(dimmed)
    }

  // The same claim for the half of a matrix a brightness does not have. A contrast carries a bias,
  // Core Image holds the frame premultiplied, and an offset landing where the picture has no alpha
  // is exactly what would tint the bar the fill was given to own. The clip is a flat photo, so the
  // centre is a colour the effect is predicted to move rather than one that merely differs.
  @Test
  fun `a composition contrast leaves a solid fill's bars untouched`() =
    runTest(timeout = TIMEOUT) {
      val teal = Triple(0x11, 0xC2, 0xAA)

      suspend fun exportedWith(
        name: String,
        factor: Float?,
      ): String {
        val composition =
          compositionOf {
            image(ImageSource.of(photoFile()), PHOTO)
            fill(Fill.Solid(teal.toArgb()))
            effects {
              crop(AspectRatio.Square, Fit.Contain)
              if (factor != null) contrast(factor)
            }
          }
        val output = temporaryPath("solid-fill-contrast-$name")
        exported(composition, ExportSpec(), output)
        return output
      }

      val plain = exportedWith("plain", null)
      val firmer = exportedWith("firmer", FIRMER)

      val graded = frameOf(firmer, PHOTO * MIDDLE)
      assertClose(graded.average(0.5f, 0.05f), teal, "top bar")
      assertClose(graded.average(0.5f, 0.95f), teal, "bottom bar")

      val before = frameOf(plain, PHOTO * MIDDLE).average(0.5f, 0.5f)
      val after = graded.average(0.5f, 0.5f)
      assertTrue(
        distance(before, after) > COLOR_TOLERANCE,
        "the contrast never reached the picture, which read $before plain and $after graded",
      )

      remove(plain)
      remove(firmer)
    }

  // Nothing here authors a fill, so this pins the default against a regression: the bars stay
  // black, the way every export wrote them before a fill could be chosen.
  @Test
  fun `leaves the letterbox bars black by default`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest

      val composition =
        compositionOf {
          clip(MediaSource.of(landscape)) { trim(0.seconds, 1.seconds) }
          effects { crop(AspectRatio.Square, Fit.Contain) }
        }

      val output = temporaryPath("black-fill")
      exported(composition, ExportSpec(), output)

      assertClose(samplePixel(output, 0.5f, 0.05f), BLACK, "top bar")
      assertClose(samplePixel(output, 0.5f, 0.95f), BLACK, "bottom bar")

      remove(output)
    }

  @Test
  fun `blurs the letterbox bars from the clip's own frame`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest

      val composition =
        compositionOf {
          clip(MediaSource.of(landscape)) { trim(0.seconds, 1.seconds) }
          fill(Fill.Blur)
          effects { crop(AspectRatio.Square, Fit.Contain) }
        }

      val output = temporaryPath("blurred-fill")
      exported(composition, ExportSpec(), output)

      val near = samplePixel(output, 0.15f, 0.05f)
      val far = samplePixel(output, 0.85f, 0.05f)

      assertTrue(near != BLACK, "expected a blurred bar, got black")
      assertTrue(distance(near, far) > COLOR_TOLERANCE, "expected the blur to vary across the bar, got $near and $far")

      remove(output)
    }

  // The blur only ever reaches the bars, never the clip's own pixels. Comparing the centre against
  // the same composition exported with a solid fill instead is what proves that: nothing else here
  // tells the two exports apart, so a centre that still matches means the composite never covered
  // the clip.
  @Test
  fun `keeps the clip sharp under a blurred fill`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest

      suspend fun exportedWith(fill: Fill): String {
        val composition =
          compositionOf {
            clip(MediaSource.of(landscape)) { trim(0.seconds, 1.seconds) }
            fill(fill)
            effects { crop(AspectRatio.Square, Fit.Contain) }
          }
        val output = temporaryPath("blurred-sharp-${fill::class.simpleName}")
        exported(composition, ExportSpec(), output)
        return output
      }

      val blurred = exportedWith(Fill.Blur)
      val reference = exportedWith(Fill.Black)

      assertClose(samplePixel(blurred, 0.5f, 0.5f), samplePixel(reference, 0.5f, 0.5f), "clip centre")

      remove(blurred)
      remove(reference)
    }

  // dim is documented as a multiply, not an offset, so half dim should land the background
  // roughly halfway to black. An endpoint alone would not catch an offset standing in for a
  // multiply, since both reach black at dim = 1.
  @Test
  fun `dims the letterbox bars proportionally`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest

      suspend fun exportedWith(
        name: String,
        fill: Fill,
      ): String {
        val composition =
          compositionOf {
            clip(MediaSource.of(landscape)) { trim(0.seconds, 1.seconds) }
            fill(fill)
            effects { crop(AspectRatio.Square, Fit.Contain) }
          }
        val output = temporaryPath("dim-$name")
        exported(composition, ExportSpec(), output)
        return output
      }

      val undimmed = exportedWith("undimmed", Fill.Blur)
      val halfDimmed = exportedWith("half", Fill.Blurred(dim = 0.5f))

      val full = samplePixel(undimmed, 0.15f, 0.05f)
      val half = samplePixel(halfDimmed, 0.15f, 0.05f)
      val ratio = luminance(half).toFloat() / luminance(full).toFloat()

      assertTrue(ratio in 0.35f..0.65f, "expected half dim near half brightness, got $ratio ($full -> $half)")

      remove(undimmed)
      remove(halfDimmed)
    }

  // Crop covers the frame itself, so the bars a Contain fit would need never open up. Sampling both
  // edges with a loud fill chosen is what proves it costs nothing when there is nowhere for it to
  // show.
  @Test
  fun `writes no bars when the fill cannot be seen`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest
      val magenta = Triple(0xFF, 0x00, 0xFF)

      val composition =
        compositionOf {
          clip(MediaSource.of(landscape)) { trim(0.seconds, 1.seconds) }
          fill(Fill.Solid(magenta.toArgb()))
          // resolved.fit, which the final pin to the output frame reads, only ever comes from a
          // Scale effect's own fit. The crop alone would leave it defaulted to Contain.
          effects {
            crop(AspectRatio.Square, Fit.Crop)
            scale(300, Fit.Crop)
          }
        }

      val output = temporaryPath("crop-fill")
      exported(composition, ExportSpec(), output)

      assertTrue(
        distance(samplePixel(output, 0.5f, 0.02f), magenta) > COLOR_TOLERANCE,
        "the fill leaked into the top edge",
      )
      assertTrue(
        distance(samplePixel(output, 0.5f, 0.98f), magenta) > COLOR_TOLERANCE,
        "the fill leaked into the bottom edge",
      )

      remove(output)
    }

  /**
   * The plan claims a passthrough, so the file has to prove one ran.
   *
   * An encoder stamps its own name into the format description, so the source's survives a copy and
   * not a re-encode. The trim is the control: it is the same export down to the path the planner
   * picks, and a reader that always answered null would pass the first claim on its own. It cuts
   * off a sync sample and says nothing about moving, which is what leaves the copy out of reach.
   */
  @Test
  fun `copies the streams across when nothing touches them`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest
      val source = formatName(landscape)
      assertTrue(source != null, "the fixture's own format description could not be read")

      val output = temporaryPath("transmux")
      val composition = compositionOf { clip(MediaSource.of(landscape)) }
      val plan = assertIs<Verdict.Capable>(filmstrip.plan(composition, ExportSpec())).plan
      plan.path shouldBe ExportPath.Transmux
      exported(composition, ExportSpec(), output)
      formatName(output) shouldBe source

      val reEncoded = temporaryPath("transcode")
      val trimmed =
        compositionOf {
          clip(MediaSource.of(landscape)) { trim(500.milliseconds, 1.seconds) }
        }
      val control = assertIs<Verdict.Capable>(filmstrip.plan(trimmed, ExportSpec())).plan
      control.path shouldBe ExportPath.Transcode
      exported(trimmed, ExportSpec(), reEncoded)
      assertTrue(formatName(reEncoded) != source, "the trimmed export passed the source's format off as its own")

      remove(output)
      remove(reEncoded)
    }

  @Test
  fun `writes a silent track when a clip is muted`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest

      val composition =
        compositionOf {
          clip(MediaSource.of(landscape)) {
            trim(0.seconds, 1.seconds)
            audio(AudioLevel.Mute)
          }
        }

      val output = temporaryPath("muted")
      val success = exported(composition, ExportSpec(targetHeight = 240), output)

      // Mute keeps the track and writes silence into it, which is a different operation from
      // dropping it.
      assertTrue(success.info.audio != null, "the muted track was dropped and not silenced")

      remove(output)
    }

  // The whole point of AudioSpec.AudioOnly is a file with no video track, so an assertion that only
  // checked the audio survived would pass even if a full video track were written alongside it.
  @Test
  fun `writes an audio track and drops video when the composition is audio-only`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest

      val composition =
        compositionOf {
          clip(MediaSource.of(landscape)) { trim(0.seconds, 1.seconds) }
          audio(AudioSpec.AudioOnly)
        }

      val output = temporaryPath("audio-only")
      val success = exported(composition, ExportSpec(), output)

      val audio = success.info.audio
      assertTrue(audio != null, "the audio track did not survive")
      assertTrue(audio.sampleRate > 0, "expected a sane sample rate, got ${audio.sampleRate}")
      assertNull(success.info.video, "AudioSpec.AudioOnly must not leave a video track behind")
      assertTrue(success.info.duration in 800.milliseconds..1_300.milliseconds, "duration was ${success.info.duration}")

      remove(output)
    }

  /**
   * The mix, read back off a real exported file rather than off the graph that was handed to the
   * writer.
   *
   * The bed carries the one tone no other fixture does, so a level measured at 880 Hz belongs to it
   * and to nothing else. It is trimmed shorter than the composition and held off past zero, which is
   * what makes the offset and the loop separable: 880 Hz has to be absent before the bed opens, and
   * present again inside a pass the loop had to lay down to reach.
   *
   * Levels are compared as a ratio against the primary's own tone in the same window, so the
   * amplitude the fixtures were generated at and whatever AAC did to the output both divide out. An
   * absolute threshold would be pinning the fixture generator rather than the mix.
   */
  @Test
  fun `mixes a looping bed under the primary at the gain the plan folded`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest
      val bed = fixture("tone_bed_880.mp4") ?: return@runTest

      val composition =
        compositionOf {
          clip(MediaSource.of(landscape))
          track(TrackContent.Audio) {
            clip(MediaSource.of(bed)) { trim(Duration.ZERO, BED_PASS) }
            audio(AudioLevel.Volume(BED_VOLUME))
            startAt(BED_START)
            looping()
          }
        }

      val spec = ExportSpec(targetHeight = 240)
      val resolved = resolved(composition, spec)
      val bedTrack = resolved.tracks.single { it.content == TrackContent.Audio }
      val bedClip = bedTrack.clips.single()
      val primaryTrack = resolved.tracks.single { it.content != TrackContent.Audio }
      val primaryClip = primaryTrack.clips.single()

      // Where the second window lands on the bed's own repeat, which is what says it is measuring a
      // pass the loop laid down rather than the bed's first and only run.
      val middle = LOOPED + WINDOW / 2
      val intoBed = middle - bedTrack.start
      val pass = (intoBed / bedClip.duration).toInt()
      assertTrue(pass >= 1, "the window at $middle sits in pass $pass, which the loop never had to lay down")

      val output = temporaryPath("audio-bed")
      exported(composition, spec, output)
      val audio = audioOf(output)

      val primaryTone = audio.toneOver(LOOPED, WINDOW, PRIMARY_HZ)
      val bedTone = audio.toneOver(LOOPED, WINDOW, BED_HZ)
      val beforePrimary = audio.toneOver(BEFORE_BED, WINDOW, PRIMARY_HZ)
      val beforeBed = audio.toneOver(BEFORE_BED, WINDOW, BED_HZ)
      println("440Hz: $beforePrimary before the bed, $primaryTone inside pass $pass")
      println("880Hz: $beforeBed before the bed, $bedTone inside pass $pass")

      assertTrue(primaryTone > AUDIBLE, "the primary's own tone never reached the file, reading $primaryTone")
      assertTrue(beforePrimary > AUDIBLE, "the window before the bed carries no primary, reading $beforePrimary")
      assertTrue(
        beforeBed < bedTone * SILENT,
        "the bed was audible at $beforeBed before its $BED_START start, against $bedTone once it had opened",
      )

      // The gain the planner folded, read off the plan rather than typed here, and sampled in the
      // clip's own time at the point inside the pass the window's middle lands on.
      val expected = bedClip.gain.gainAt(intoBed - bedClip.duration * pass) / primaryClip.gain.gainAt(middle)
      val measured = bedTone / primaryTone
      assertTrue(
        abs(measured - expected) <= GAIN_TOLERANCE,
        "expected the bed at $expected of the primary, measured $measured ($bedTone against $primaryTone)",
      )

      remove(output)
    }

  @Test
  fun `streams progress that only ever climbs`() =
    runTest(timeout = TIMEOUT) {
      val long = fixture("apple_export_long.mp4") ?: return@runTest

      val composition = compositionOf { clip(MediaSource.of(long)) }
      val output = temporaryPath("progress")
      // 360 divides the fixture's frame exactly, so the plan needs no adjustment and Started is
      // genuinely the first thing a caller sees.
      val statuses =
        withContext(Dispatchers.Default) {
          filmstrip.export(composition, ExportSpec(targetHeight = 360), MediaSink.of(output)).toList()
        }

      assertIs<ExportStatus.Started>(statuses.first())
      val progress = statuses.filterIsInstance<ExportStatus.Progress>()
      assertTrue(progress.isNotEmpty(), "expected at least one progress report")
      progress.zipWithNext().forEach { (first, second) ->
        assertTrue(second.fraction >= first.fraction, "progress went backwards")
      }
      assertIs<ExportStatus.Success>(statuses.last())

      remove(output)
    }

  // Cancelling the collector cancels the export, and everything at the destination belongs to the
  // run, so nothing is left behind.
  @Test
  fun `cancelling the collector leaves no partial file`() =
    runTest(timeout = TIMEOUT) {
      val long = fixture("apple_export_long.mp4") ?: return@runTest
      val output = temporaryPath("cancelled")
      val composition = compositionOf { clip(MediaSource.of(long)) }

      // Cancelled on Started, not after a fixed window. A hardware encode of even a long
      // clip outruns any window worth waiting for, and a run that finished first would be checking
      // that a successful export keeps its file, which is the opposite claim.
      withContext(Dispatchers.Default) {
        val started = CompletableDeferred<Unit>()
        val job =
          launch {
            filmstrip.export(composition, ExportSpec(targetHeight = 360), MediaSink.of(output)).collect {
              if (it is ExportStatus.Started) started.complete(Unit)
            }
          }
        started.await()
        job.cancelAndJoin()
      }

      NSFileManager.defaultManager.fileExistsAtPath(output) shouldBe false
    }

  @Test
  fun `resolves a temporary sink to the file it wrote`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest

      val composition =
        compositionOf {
          clip(MediaSource.of(landscape)) { trim(0.seconds, 1.seconds) }
        }

      val success =
        withContext(Dispatchers.Default) {
          val statuses = filmstrip.export(composition, ExportSpec(targetHeight = 180), MediaSink.Temporary).toList()
          when (val finished = statuses.last()) {
            is ExportStatus.Failure -> error(finished.error.message)
            else -> assertIs<ExportStatus.Success>(finished)
          }
        }

      val path = assertIs<MediaSink.Path>(success.output).path
      NSFileManager.defaultManager.fileExistsAtPath(path) shouldBe true
      remove(path)
    }

  @Test
  fun `reports an unwritable destination and does not start`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest

      val composition = compositionOf { clip(MediaSource.of(landscape)) }
      val statuses =
        withContext(Dispatchers.Default) {
          filmstrip
            .export(composition, ExportSpec(targetHeight = 240), MediaSink.of("/nonexistent/dir/out.mp4"))
            .toList()
        }

      val failure = assertIs<ExportStatus.Failure>(statuses.last())
      assertIs<ExportError.SinkUnwritable>(failure.error)
      // Nothing was opened, so the export never began.
      assertTrue(statuses.none { it is ExportStatus.Started }, "the export started on an unwritable sink")
    }

  @Test
  fun `leaves nothing behind when the export fails`() =
    runTest(timeout = TIMEOUT) {
      val landscape = fixture("apple_export_a.mp4") ?: return@runTest
      val output = temporaryPath("leftover")

      val composition = compositionOf { clip(MediaSource.of(landscape)) }
      withContext(Dispatchers.Default) {
        filmstrip.export(composition, ExportSpec(targetHeight = 240), MediaSink.of(output)).toList()
      }
      remove(output)

      NSFileManager.defaultManager.fileExistsAtPath(output) shouldBe false
    }

  private suspend fun exported(
    composition: EditComposition,
    spec: ExportSpec,
    output: String,
  ): ExportStatus.Success =
    withContext(Dispatchers.Default) {
      when (val verdict = filmstrip.plan(composition, spec)) {
        is Verdict.Incapable -> error(verdict.reasons.joinToString { it.message })
        is Verdict.Capable, is Verdict.Degraded -> Unit
      }

      val statuses = filmstrip.export(composition, spec, MediaSink.of(output)).toList()
      when (val finished = statuses.last()) {
        is ExportStatus.Failure -> error(finished.error.message)
        else -> assertIs<ExportStatus.Success>(finished)
      }
    }

  /**
   * The graph an export of [composition] runs, which is where the folded gain a backend consumes
   * lives.
   *
   * Negotiated through the same engine the export goes through, so the curve read here is the curve
   * the writer was handed rather than a second fold of the same levels.
   */
  private suspend fun resolved(
    composition: EditComposition,
    spec: ExportSpec,
  ): ResolvedComposition =
    withContext(Dispatchers.Default) {
      val components = ComponentRegistry.Builder().build()
      val engine = avFoundationExportEngine(chainedProber(components), components.effectResolvers)
      when (val result = engine.resolve(composition, spec)) {
        is ResolveResult.Refused -> error(result.error.message)
        is ResolveResult.Resolved -> result.composition
      }
    }

  private fun fixture(name: String): String? {
    val directory = fixtures ?: return null
    val path = "$directory/$name"
    return path.takeIf { NSFileManager.defaultManager.fileExistsAtPath(it) }
  }

  /**
   * The name the encoder stamped into this file's video format description.
   */
  private fun formatName(path: String): String? {
    val track =
      AVURLAsset(uRL = NSURL.fileURLWithPath(path), options = null)
        .tracksWithMediaType(AVMediaTypeVideo)
        .firstOrNull() as? AVAssetTrack ?: return null
    val format = track.copyFormatDescription() ?: return null

    try {
      val name = CMFormatDescriptionGetExtension(format, kCMFormatDescriptionExtension_FormatName) ?: return null
      return CFBridgingRelease(CFRetain(name)) as? String
    } finally {
      CFRelease(format)
    }
  }

  /**
   * The flat photo the fill's contrast case draws from, written into the temporary directory once.
   */
  private fun photoFile(): String = photoFixture("filmstrip-apple-export-photo", PHOTO_SIZE, PHOTO_COLOR)

  private fun temporaryPath(name: String): String = NSTemporaryDirectory() + "filmstrip-apple-$name.mp4"

  private fun remove(path: String) {
    NSFileManager.defaultManager.removeItemAtPath(path, error = null)
  }

  private fun isSimulator(): Boolean = NSProcessInfo.processInfo.environment[SIMULATOR_DEVICE_NAME] != null

  private companion object {
    const val FIXTURES = "FILMSTRIP_FIXTURES"
    const val SIMULATOR_DEVICE_NAME = "SIMULATOR_DEVICE_NAME"
    val TIMEOUT = 2.seconds * 60
    val BLACK = Triple(0, 0, 0)

    // The photo the contrast case lays over the fill, held long enough to read inside its span
    // rather than on either edge of it.
    val PHOTO = 1.seconds
    const val MIDDLE = 0.4
    val PHOTO_SIZE = Size(640, 360)

    // Mid-range on all three channels, so the gain moves every one of them without any running out
    // of range and clamping to the same answer a broken lowering would give.
    val PHOTO_COLOR = Triple(0x66, 0x99, 0xCC)

    const val FIRMER = 1.5f

    // The tones the fixtures were generated with. Only the bed carries 880Hz, which is what lets a
    // level measured in the mix be attributed to one source.
    const val PRIMARY_HZ = 440
    const val BED_HZ = 880

    // Shorter than the composition, so the bed has to be laid down more than once to cover it.
    val BED_PASS = 500.milliseconds
    val BED_START = 500.milliseconds
    const val BED_VOLUME = 0.5f

    // Long enough to hold hundreds of cycles of either tone, and clear of both ends of the pass it
    // sits in so an encoder's priming cannot drag a neighbouring stretch into the measurement.
    val WINDOW = 250.milliseconds
    val BEFORE_BED = 150.milliseconds
    val LOOPED = 1_100.milliseconds

    // A presence floor rather than a claim about any gain, which is what the ratio makes. Well
    // under the level the fixtures were generated at and well over what a silent stretch reads.
    const val AUDIBLE = 0.02f
    const val SILENT = 0.15f
    const val GAIN_TOLERANCE = 0.05f
  }
}
