import dev.jordond.filmstrip.convention.testmedia.FixtureSpec
import dev.jordond.filmstrip.convention.testmedia.testMedia

plugins {
  id("filmstrip.internal")
  alias(libs.plugins.multiplatform)
}

kotlin {
  jvmToolchain(
    libs.versions.jvmTarget
      .get()
      .toInt(),
  )
  applyDefaultHierarchyTemplate()

  listOf(iosArm64(), iosSimulatorArm64()).forEach { target ->
    target.binaries.framework {
      baseName = "IosHarness"
      isStatic = true
    }
  }
  macosArm64().binaries.framework {
    baseName = "IosHarness"
    isStatic = true
  }

  sourceSets {
    appleMain.dependencies {
      implementation(libs.kotlinx.coroutines.core)
    }

    appleTest.dependencies {
      implementation(kotlin("test"))
    }
  }

  // No `binaryOptions["sanitizer"] = "address"` anywhere here on purpose. Kotlin/Native 2.4.10
  // accepts it and then warns "ADDRESS sanitizer is not supported yet", producing an uninstrumented
  // binary. The linked test.kexe carries no __asan symbols. Leaving it in would look like coverage
  // that does not exist. See PlayerObserverTest for what is covered instead.
}

// The clips the tests read, generated by host ffmpeg and verified with ffprobe. `concat_a` and
// `concat_b` differ in resolution and nothing else, so a filter graph that reconfigures at the
// boundary is the only thing that can change between them.
val harnessMedia =
  testMedia(
    name = "harness",
    specs =
      listOf(
        FixtureSpec("p1080_30", 1920, 1080, 30, 6.0, 48000, 2, bitrateKbps = 12_000),
        FixtureSpec("concat_a", 1920, 1080, 30, 3.0, 48000, 2, bitrateKbps = 12_000),
        FixtureSpec("concat_b", 1280, 720, 30, 3.0, 48000, 2, bitrateKbps = 6_000, hue = 120),
      ),
  )

// The tests read the fixtures straight off the host filesystem rather than from a bundle.
val testMediaDirectory = harnessMedia.directory
val resultsDirectory = layout.projectDirectory.dir("results").asFile

// Writing results is opt-in. Without the flag the harness still measures and prints, and does not
// touch the checked-in numbers. Those were taken on an idle machine, and a run inside a
// parallel build reports p95 figures several times higher because the rest of the build is
// competing for the same GPU. Letting `./gradlew build` overwrite them replaces a measurement with
// an artefact of whatever else was compiling at the time.
val recordResults = providers.gradleProperty("filmstrip.recordResults").isPresent

tasks.withType<org.jetbrains.kotlin.gradle.targets.native.tasks.KotlinNativeTest>().configureEach {
  dependsOn(harnessMedia.download)
  // simctl only forwards variables prefixed SIMCTL_CHILD_ into the simulated process. The macOS
  // test runs directly, so it needs the plain names as well.
  environment("FILMSTRIP_FIXTURES", testMediaDirectory.absolutePath)
  environment("SIMCTL_CHILD_FILMSTRIP_FIXTURES", testMediaDirectory.absolutePath)

  if (recordResults) {
    environment("FILMSTRIP_RESULTS", resultsDirectory.absolutePath)
    environment("SIMCTL_CHILD_FILMSTRIP_RESULTS", resultsDirectory.absolutePath)

    val results = resultsDirectory
    doFirst { results.mkdirs() }
  }
}
