import dev.jordond.filmstrip.convention.androidDeviceTests
import dev.jordond.filmstrip.convention.testmedia.FixtureSpec
import dev.jordond.filmstrip.convention.testmedia.FixtureTransfer
import dev.jordond.filmstrip.convention.testmedia.GenerateTestMediaTask

plugins {
  id("filmstrip.library.android")
}

androidDeviceTests()

kotlin {
  sourceSets {
    androidMain.dependencies {
      api(projects.filmstripTransform)
      implementation(libs.media3.transformer)
    }

    named("androidDeviceTest").dependencies {
      implementation(kotlin("test"))
      implementation(libs.kotlinx.coroutines.test)
      implementation(libs.androidx.test.runner)
      implementation(libs.androidx.test.core)
    }
  }

  sourceSets.androidMain {
    languageSettings.optIn("androidx.media3.common.util.UnstableApi")
  }
}

// The clips the device test encodes, generated by host ffmpeg into the device-test source set's
// resources so they ride into the test APK. Absent when the host has no ffmpeg, which the test reads as "skip"
// since there is nothing to export from.
val exportFixtures =
  tasks.register<GenerateTestMediaTask>("generateDeviceTestFixtures") {
    group = "verification"
    description = "Generates the clips the Android export device test encodes."
    specs.set(
      listOf(
        FixtureSpec("android_export_a", 640, 360, 30, 2.0, 48000, 2, bitrateKbps = 1_500),
        FixtureSpec("android_export_b", 480, 270, 30, 2.0, 48000, 2, bitrateKbps = 1_000, hue = 120),
        // Long enough that there is still an export running when the collector is cancelled. A
        // phone encodes two seconds of 240p in about as long as it takes to ask it to stop.
        FixtureSpec("android_export_long", 1280, 720, 30, 12.0, 48000, 2, bitrateKbps = 6_000),
        // Not thirty, so an export that silently retimes to the default rate shows up.
        FixtureSpec("android_export_24fps", 640, 360, 24, 2.0, 48000, 2, bitrateKbps = 1_500),
        // Landscape frames with a quarter turn in the container, the shape a phone camera writes
        // for a portrait recording. Coded size and display size disagree, which is the only way to
        // see whether an export bakes the rotation or passes it along.
        FixtureSpec("android_export_rotated", 640, 360, 30, 2.0, 48000, 2, bitrateKbps = 1_500, rotationDegrees = 90),
        // Ten-bit BT.2020 PQ, which is the only way to find out what the HDR branch does.
        FixtureSpec(
          "android_export_hdr",
          1280,
          720,
          30,
          2.0,
          48000,
          2,
          bitrateKbps = 6_000,
          transfer = FixtureTransfer.Pq,
        ),
        FixtureSpec(
          "android_export_hdr_hlg",
          1280,
          720,
          30,
          2.0,
          48000,
          2,
          bitrateKbps = 6_000,
          transfer = FixtureTransfer.Hlg,
        ),
      ),
    )
    outputDirectory.set(layout.buildDirectory.dir("device-test-fixtures"))
    manifest.set(layout.buildDirectory.file("device-test-fixtures/fixtures.txt"))
  }

val hasFfmpeg =
  providers.environmentVariable("PATH").orElse("").map { path ->
    path.split(File.pathSeparatorChar).any { entry -> File(entry, "ffmpeg").canExecute() }
  }

if (hasFfmpeg.get()) {
  kotlin.sourceSets.named("androidDeviceTest") {
    resources.srcDir(exportFixtures.map { it.outputDirectory })
  }
}
