package dev.jordond.filmstrip.convention.testmedia

import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import org.gradle.process.ExecOperations
import java.io.ByteArrayOutputStream
import java.io.File
import javax.inject.Inject

/**
 * Encodes the test fixtures with host ffmpeg, then verifies each one with ffprobe.
 *
 * ffmpeg is host tooling only. Nothing it produces is linked into the library. The fixtures are
 * input bytes, the same as a checked-in sample clip would be.
 *
 * The verification pass is the point of the task doing more than shelling out: ffmpeg falls back
 * silently when a codec cannot honour a request, and a fixture whose sample rate is not the one
 * under test would invalidate the audio-boundary results without ever failing a build.
 */
abstract class GenerateTestMediaTask
  @Inject
  constructor(
    private val exec: ExecOperations,
  ) : DefaultTask() {
    @get:Input
    abstract val specs: ListProperty<FixtureSpec>

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @get:OutputFile
    abstract val manifest: RegularFileProperty

    @TaskAction
    fun generate() {
      val outputDir = outputDirectory.get().asFile
      outputDir.mkdirs()

      val version = capture(listOf("ffmpeg", "-version")).lineSequence().first().trim()
      val rows = mutableListOf<String>()

      specs.get().forEach { spec ->
        val target = outputDir.resolve(spec.fileName)
        target.delete()
        exec.exec {
          commandLine(ffmpegArgs(spec, target.absolutePath))
        }
        if (spec.rotationDegrees != 0) rotate(spec, target)
        rows += verify(spec, target.absolutePath)
      }

      val text =
        buildString {
          appendLine("# filmstrip test fixtures")
          appendLine("# generated by $version")
          appendLine("# name width height fps frames duration bitrateBps sampleRate channels bytes")
          rows.forEach { appendLine(it) }
        }

      manifest
        .get()
        .asFile
        .also { it.parentFile.mkdirs() }
        .writeText(text)
      outputDir.resolve("fixtures.txt").writeText(text)
    }

    private fun ffmpegArgs(
      spec: FixtureSpec,
      target: String,
    ): List<String> =
      buildList {
        addAll(listOf("ffmpeg", "-y", "-hide_banner", "-loglevel", "error", "-nostdin"))
        addAll(
          listOf(
            "-f",
            "lavfi",
            "-i",
            "testsrc=size=${spec.width}x${spec.height}:rate=${spec.frameRate}:duration=${spec.durationSeconds}",
          ),
        )
        addAll(
          listOf(
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:sample_rate=${spec.sampleRate}:duration=${spec.durationSeconds}",
          ),
        )
        // Seeded noise, so the clips carry camera-like entropy instead of testsrc's ~0.5 Mbps.
        // Without it the decoder feeding the effect pipeline does almost no work and the realtime
        // benchmark would understate the total per-frame cost. The seed keeps it reproducible.
        val filters =
          buildList {
            if (spec.hue != 0) add("hue=h=${spec.hue}")
            add("noise=alls=14:allf=t+u:all_seed=20260819")
            // After the noise, so the patch is flat. That is the whole point of it: a test that
            // predicts what an operation did to one pixel cannot read a pixel whose neighbours
            // disagree with it.
            spec.patch?.let { patch ->
              add(
                "drawbox=x=(iw-${patch.size})/2:y=(ih-${patch.size})/2:" +
                  "w=${patch.size}:h=${patch.size}:color=${patch.hex}:t=fill",
              )
            }
          }
        addAll(listOf("-filter:v", filters.joinToString(",")))
        addAll(spec.transfer?.let { hdrVideoArgs(it) } ?: sdrVideoArgs())
        addAll(
          listOf(
            "-preset",
            "medium",
            "-b:v",
            "${spec.bitrateKbps}k",
            "-maxrate",
            "${(spec.bitrateKbps * 3) / 2}k",
            "-bufsize",
            "${spec.bitrateKbps * 2}k",
            "-g",
            spec.frameRate.toString(),
            "-keyint_min",
            spec.frameRate.toString(),
            "-c:a",
            "aac",
            "-b:a",
            "128k",
            "-ar",
            spec.sampleRate.toString(),
            "-ac",
            spec.channelCount.toString(),
            "-movflags",
            "+faststart",
            "-shortest",
            target,
          ),
        )
      }

    private fun sdrVideoArgs(): List<String> = listOf("-c:v", "libx264", "-pix_fmt", "yuv420p")

    /**
     * Rewrites the container with a display matrix, leaving the encoded frames alone.
     *
     * Rotation cannot ride on the encode pass, since it is a container field rather than anything
     * the codec sees. The stream copy is what puts it there.
     */
    private fun rotate(
      spec: FixtureSpec,
      target: File,
    ) {
      val rotated = target.resolveSibling("${spec.name}-rotating.mp4")
      rotated.delete()
      exec.exec {
        commandLine(
          listOf(
            "ffmpeg",
            "-y",
            "-hide_banner",
            "-loglevel",
            "error",
            "-nostdin",
            "-display_rotation",
            spec.rotationDegrees.toString(),
            "-i",
            target.absolutePath,
            "-c",
            "copy",
            "-movflags",
            "+faststart",
            rotated.absolutePath,
          ),
        )
      }
      if (!target.delete() || !rotated.renameTo(target)) {
        throw GradleException("could not replace ${spec.fileName} with its rotated copy")
      }
    }

    /**
     * Ten-bit HEVC in BT.2020, tagged in the container and in the bitstream.
     *
     * The x265 parameters tag the bitstream and the ffmpeg flags tag the container. MediaExtractor
     * reads one and media3's decoder reads the other, so both have to say the same thing.
     *
     * `hdr10` is set only for PQ, since the static metadata it writes is defined against an
     * absolute signal and HLG carries none.
     */
    private fun hdrVideoArgs(transfer: FixtureTransfer): List<String> {
      val x265 =
        buildList {
          add("colorprim=bt2020")
          add("transfer=${transfer.tag}")
          add("colormatrix=bt2020nc")
          if (transfer == FixtureTransfer.Pq) add("hdr10=1")
          add("repeat-headers=1")
        }

      return listOf(
        "-c:v",
        "libx265",
        "-pix_fmt",
        "yuv420p10le",
        "-color_primaries",
        "bt2020",
        "-color_trc",
        transfer.tag,
        "-colorspace",
        "bt2020nc",
        "-x265-params",
        x265.joinToString(":"),
        "-tag:v",
        "hvc1",
      )
    }

    /**
     * Reads back what was actually written and fails on any drift from [spec].
     */
    private fun verify(
      spec: FixtureSpec,
      target: String,
    ): String {
      val probe =
        capture(
          listOf(
            "ffprobe",
            "-v",
            "error",
            "-count_frames",
            "-show_entries",
            "stream=codec_type,width,height,avg_frame_rate,nb_read_frames,bit_rate,sample_rate,channels," +
              "pix_fmt,color_transfer,color_primaries",
            "-show_entries",
            "stream_side_data=rotation",
            "-show_entries",
            "format=duration,size",
            "-of",
            "default=noprint_wrappers=1",
            target,
          ),
        )

      val fields =
        probe
          .lineSequence()
          .mapNotNull { line -> line.split("=", limit = 2).takeIf { it.size == 2 } }
          .groupBy({ it[0].trim() }, { it[1].trim() })

      fun single(
        key: String,
        index: Int = 0,
      ): String = fields[key]?.getOrNull(index) ?: error("ffprobe reported no $key for ${spec.fileName}")

      val width = single("width").toInt()
      val height = single("height").toInt()
      val frameRate = single("avg_frame_rate").split("/").let { it[0].toDouble() / it[1].toDouble() }
      val sampleRate = single("sample_rate").toInt()
      val channels = single("channels").toInt()
      val duration = single("duration").toDouble()
      val bytes = single("size").toLong()
      val frames = single("nb_read_frames").toInt()
      val videoBitrate = single("bit_rate").toLong()

      val drift =
        buildList {
          if (width != spec.width || height != spec.height) add("size ${width}x$height != ${spec.width}x${spec.height}")
          if (kotlin.math.abs(frameRate - spec.frameRate) > 0.01) add("fps $frameRate != ${spec.frameRate}")
          if (sampleRate != spec.sampleRate) add("sampleRate $sampleRate != ${spec.sampleRate}")
          if (channels != spec.channelCount) add("channels $channels != ${spec.channelCount}")
          if (kotlin.math.abs(duration - spec.durationSeconds) >
            0.25
          ) {
            add("duration $duration != ${spec.durationSeconds}")
          }
          if (spec.rotationDegrees != 0) {
            val rotation = fields["rotation"]?.firstOrNull()?.toIntOrNull()
            if (rotation != spec.rotationDegrees) add("rotation $rotation != ${spec.rotationDegrees}")
          }
          spec.transfer?.let { asked ->
            val pixelFormat = single("pix_fmt")
            val transfer = single("color_transfer")
            val primaries = single("color_primaries")
            if (pixelFormat != "yuv420p10le") add("pix_fmt $pixelFormat is not ten bit")
            if (transfer != asked.tag) add("color_trc $transfer is not ${asked.tag}")
            if (primaries != "bt2020") add("color_primaries $primaries is not BT.2020")
          }
        }

      if (drift.isNotEmpty()) {
        throw GradleException("${spec.fileName} does not match its spec: ${drift.joinToString("; ")}")
      }

      return listOf(
        spec.name,
        width,
        height,
        frameRate.toInt(),
        frames,
        duration,
        videoBitrate,
        sampleRate,
        channels,
        bytes,
      ).joinToString(" ")
    }

    private fun capture(command: List<String>): String {
      val stdout = ByteArrayOutputStream()
      exec.exec {
        commandLine(command)
        standardOutput = stdout
      }
      return stdout.toString(Charsets.UTF_8)
    }
  }
