package dev.jordond.filmstrip.media3

import androidx.test.platform.app.InstrumentationRegistry
import dev.jordond.filmstrip.CapabilitiesResult
import dev.jordond.filmstrip.Filmstrip
import dev.jordond.filmstrip.edit.AudioSpec
import dev.jordond.filmstrip.edit.Clip
import dev.jordond.filmstrip.edit.EditComposition
import dev.jordond.filmstrip.edit.TimeRange
import dev.jordond.filmstrip.edit.Track
import dev.jordond.filmstrip.effects.Rotate
import dev.jordond.filmstrip.effects.Scale
import dev.jordond.filmstrip.export.AdjustmentKind
import dev.jordond.filmstrip.export.ExportPath
import dev.jordond.filmstrip.export.ExportPlan
import dev.jordond.filmstrip.export.ExportSpec
import dev.jordond.filmstrip.export.ExportStatus
import dev.jordond.filmstrip.export.Verdict
import dev.jordond.filmstrip.media.MediaInfo
import dev.jordond.filmstrip.media.MediaSink
import dev.jordond.filmstrip.media.MediaSource
import dev.jordond.filmstrip.media.ProbeResult
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.cancelAndJoin
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.toList
import kotlinx.coroutines.launch
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.withContext
import kotlinx.coroutines.withTimeoutOrNull
import java.io.File
import kotlin.math.abs
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertIs
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue
import kotlin.time.Duration
import kotlin.time.Duration.Companion.milliseconds
import kotlin.time.Duration.Companion.minutes
import kotlin.time.Duration.Companion.seconds

/**
 * The end-to-end pass: real clips, real hardware encoders, a real file, read back with the same
 * prober a caller would use.
 *
 * Skipped when the fixtures are absent, since they are generated by host
 * ffmpeg at build time and a machine without one has nothing to export from.
 */
class AndroidExportTest {
  private val context = InstrumentationRegistry.getInstrumentation().targetContext
  private val filmstrip = Filmstrip(context) { media3Backend() }

  @Test
  fun reportsWhatTheEncodersCanDo() =
    runTest(timeout = TIMEOUT) {
      val result = filmstrip.capabilities()

      assertIs<CapabilitiesResult.Success>(result)
      assertTrue(result.capabilities.video.isNotEmpty(), "expected at least one video encoder")
    }

  @Test
  fun downscalesAClipAndWritesWhatThePlanPromised() =
    runTest(timeout = TIMEOUT) {
      val source = fixture(CLIP_A) ?: return@runTest

      val written = export(capablePlan(composition(source), ExportSpec(targetHeight = 240)))

      written.video?.displaySize?.height shouldBeCloseTo 240
      written.duration shouldBeCloseTo 2_000.milliseconds
    }

  @Test
  fun honoursAScaleEffectTheSameWayAsATargetHeight() =
    runTest(timeout = TIMEOUT) {
      val source = fixture(CLIP_A) ?: return@runTest
      val scaled = composition(Clip(source, effects = listOf(Scale(targetHeight = 240))))

      val written = export(capablePlan(scaled, ExportSpec()))

      written.video?.displaySize?.height shouldBeCloseTo 240
    }

  @Test
  fun trimsToTheRequestedWindow() =
    runTest(timeout = TIMEOUT) {
      val source = fixture(CLIP_A) ?: return@runTest
      val trimmed = composition(Clip(source, trim = TimeRange.of(500.milliseconds, 1_500.milliseconds)))

      val written = export(capablePlan(trimmed, ExportSpec(targetHeight = 240)))

      written.duration shouldBeCloseTo 1_000.milliseconds
    }

  @Test
  fun concatenatesTwoClipsOfDifferingSizes() =
    runTest(timeout = TIMEOUT) {
      val first = fixture(CLIP_A) ?: return@runTest
      val second = fixture(CLIP_B) ?: return@runTest
      val joined = EditComposition(listOf(Track(listOf(Clip(first), Clip(second)))))

      val written = export(capablePlan(joined, ExportSpec(targetHeight = 240)))

      written.duration shouldBeCloseTo 4_000.milliseconds
      written.video?.displaySize?.height shouldBeCloseTo 240
    }

  @Test
  fun removingAudioWritesNoAudioTrack() =
    runTest(timeout = TIMEOUT) {
      val source = fixture(CLIP_A) ?: return@runTest
      val silent = composition(source).withAudio(AudioSpec.Remove)

      val written = export(capablePlan(silent, ExportSpec(targetHeight = 240)))

      assertNull(written.audio, "AudioSpec.Remove must not leave an audio track behind")
    }

  // The whole point of AudioSpec.AudioOnly is a file with no video track, so an assertion that
  // only checked the audio survived would pass even if a full video track were written alongside
  // it.
  @Test
  fun audioOnlyWritesAnAudioTrackAndNoVideoTrack() =
    runTest(timeout = TIMEOUT) {
      val source = fixture(CLIP_A) ?: return@runTest
      val audioOnly = composition(source).withAudio(AudioSpec.AudioOnly)

      val plan = capablePlan(audioOnly, ExportSpec())
      val statuses = withContext(Dispatchers.Default) { filmstrip.export(plan, MediaSink.temporary()).toList() }

      assertTrue(statuses.first() is ExportStatus.Started, "the first status is always Started")
      val finished = statuses.last()
      if (finished is ExportStatus.Failure) throw AssertionError("export failed: ${finished.error.message}")
      val success = assertIs<ExportStatus.Success>(finished)

      // Read it back the way a caller would, without trusting what the encoder reported.
      val written = assertIs<ProbeResult.Success>(filmstrip.probe(success.output.asSource())).info
      val audio = assertNotNull(written.audio, "the written file has no audio track")
      assertTrue(audio.sampleRate > 0, "expected a sane sample rate, got ${audio.sampleRate}")
      assertNull(written.video, "AudioSpec.AudioOnly must not leave a video track behind")
      written.duration shouldBeCloseTo 2_000.milliseconds
    }

  // The top of the encoder's range, which nothing else here reaches. A phone that cannot do 2160
  // has to say so through the plan, never by writing something smaller in silence.
  @Test
  fun exportsAtFourKOrReportsTheClamp() =
    runTest(timeout = TIMEOUT) {
      val source = fixture(CLIP_LONG) ?: return@runTest
      // A software encoder will accept a 4K request and then write whatever it feels like, so the
      // claim below is about hardware. The emulator is the case this skips.
      if (!hasHardwareEncoder()) return@runTest

      val verdict = filmstrip.plan(composition(source), ExportSpec(targetHeight = 2_160))

      val plan =
        when (verdict) {
          is Verdict.Capable -> {
            verdict.plan
          }
          is Verdict.Degraded -> {
            assertTrue(
              verdict.adjustments.any { it.kind == AdjustmentKind.ResolutionClamped },
              "4K was refused for a reason other than the resolution: ${verdict.adjustments.map { it.message }}",
            )
            verdict.plan
          }
          is Verdict.Incapable -> {
            throw AssertionError("refused: ${verdict.reasons.map { it.message }}")
          }
        }

      // Whatever the plan settled on is what has to come out, so a clamp is honoured and not
      // merely announced.
      val written = export(plan)
      written.video?.displaySize?.height shouldBeCloseTo plan.output.size.height
    }

  @Test
  fun cancellingLeavesNoPartialFile() =
    runTest(timeout = TIMEOUT) {
      val source = fixture(CLIP_LONG) ?: return@runTest
      // Not the cache. A destination the caller named is the one the guarantee is about, and an
      // intermediate under cacheDir would be swept up whether or not the guarantee holds.
      val output = File(context.filesDir, "cancelled.mp4")
      output.delete()

      val plan = capablePlan(composition(source), ExportSpec(targetHeight = 360))
      // Real time, not the test scheduler's: the point is to stop an export that is under way.
      // Cancelled on Started, not after a fixed window, since a hardware encode outruns
      // any window worth waiting for and a run that finished first would be checking that a
      // successful export keeps its file, which is the opposite claim.
      withContext(Dispatchers.Default) {
        val started = CompletableDeferred<Unit>()
        val job =
          launch {
            filmstrip.export(plan, MediaSink.of(output.path)).collect {
              if (it is ExportStatus.Started) started.complete(Unit)
            }
          }
        started.await()
        // A path sink is written to directly, so there is a real file to remove. Waiting for it to
        // turn up is what stops the assertion below passing on an export that had not opened its
        // muxer yet, which would be a claim about nothing.
        assertTrue(output.appears(), "the muxer never opened the file, so there was nothing to leave behind")
        job.cancelAndJoin()
      }

      assertTrue(!output.exists(), "a cancelled export must not leave a half-written file")
    }

  @Test
  fun carriesTheSourceRotationIntoTheOutputContainerWhenItReEncodes() =
    runTest(timeout = TIMEOUT) {
      val source = rotatedFixture() ?: return@runTest
      val rotation = assertNotNull(assertIs<ProbeResult.Success>(filmstrip.probe(source)).info.video).rotationDegrees

      val written = assertNotNull(export(capablePlan(composition(source), ExportSpec(targetHeight = 240))).video)

      assertEquals(rotation, written.rotationDegrees, "coded ${written.codedSize}, display ${written.displaySize}")
      assertTrue(
        written.codedSize.width > written.codedSize.height,
        "expected the frames left landscape, got ${written.codedSize}",
      )
    }

  @Test
  fun carriesTheSourceRotationIntoTheOutputContainerWhenItTransmuxes() =
    runTest(timeout = TIMEOUT) {
      val source = rotatedFixture() ?: return@runTest
      val rotation = assertNotNull(assertIs<ProbeResult.Success>(filmstrip.probe(source)).info.video).rotationDegrees
      val plan = capablePlan(composition(source), ExportSpec())
      assertEquals(ExportPath.Transmux, plan.path, "this export was meant to copy the streams across")

      val written = assertNotNull(export(plan).video)

      assertEquals(rotation, written.rotationDegrees, "coded ${written.codedSize}, display ${written.displaySize}")
    }

  @Test
  fun writesARotateEffectToTheContainerRatherThanTheFrames() =
    runTest(timeout = TIMEOUT) {
      val source = fixture(CLIP_A) ?: return@runTest
      val turned = composition(Clip(source, effects = listOf(Rotate(degrees = 90))))

      val written = assertNotNull(export(capablePlan(turned, ExportSpec())).video)

      // The quarter turn has to land somewhere, and it is not in the frames: they come back the
      // landscape size they went in at, with the container carrying the turn.
      assertTrue(written.rotationDegrees != 0, "the turn reached neither the frames nor the container")
      assertTrue(
        written.codedSize.width > written.codedSize.height,
        "expected the frames left landscape, got ${written.codedSize}",
      )
      assertTrue(
        written.displaySize.height > written.displaySize.width,
        "expected a portrait display, got ${written.displaySize}",
      )
    }

  /**
   * The rotated clip, checked to still carry its quarter turn before anything is asked of it.
   *
   * A fixture that lost its rotation somewhere between ffmpeg and the device would make the
   * rotation tests pass by describing a clip that was never rotated.
   */
  private suspend fun rotatedFixture(): MediaSource? {
    val source = fixture(CLIP_ROTATED) ?: return null
    val video = assertNotNull(assertIs<ProbeResult.Success>(filmstrip.probe(source)).info.video)

    assertTrue(video.rotationDegrees != 0, "the fixture arrived without its rotation")
    assertTrue(video.codedSize.width > video.codedSize.height, "the fixture's frames are not landscape")
    assertTrue(video.displaySize.height > video.displaySize.width, "the fixture does not display portrait")
    return source
  }

  private suspend fun capablePlan(
    composition: EditComposition,
    spec: ExportSpec,
  ) = when (val verdict = filmstrip.plan(composition, spec)) {
    is Verdict.Capable -> verdict.plan
    is Verdict.Degraded -> verdict.plan
    is Verdict.Incapable -> throw AssertionError("refused: ${verdict.reasons.map { it.message }}")
  }

  // Collected off the test scheduler, whose virtual clock would spin the backend's progress poll
  // instead of pacing it.
  private suspend fun export(plan: ExportPlan): MediaInfo {
    val statuses = withContext(Dispatchers.Default) { filmstrip.export(plan, MediaSink.temporary()).toList() }

    assertTrue(statuses.first() is ExportStatus.Started, "the first status is always Started")
    val finished = statuses.last()
    if (finished is ExportStatus.Failure) throw AssertionError("export failed: ${finished.error.message}")

    val success = assertIs<ExportStatus.Success>(finished)
    // Close, not equal. The plan measures the first encoder the codec list advertises for the MIME
    // type, media3 picks its own and clamps again to what that one accepts.
    success.info.video
      ?.displaySize
      ?.height shouldBeCloseTo plan.output.size.height
    // Read it back the way a caller would, without trusting what the encoder reported.
    return assertIs<ProbeResult.Success>(filmstrip.probe(success.output.asSource())).info.also {
      assertNotNull(it.video, "the written file has no video track")
    }
  }

  private suspend fun File.appears(): Boolean =
    withTimeoutOrNull(MUXER_OPENS) {
      while (!exists()) delay(POLL)
      true
    } ?: false

  private suspend fun hasHardwareEncoder(): Boolean =
    (filmstrip.capabilities() as? CapabilitiesResult.Success)
      ?.capabilities
      ?.video
      ?.any { it.isHardwareAccelerated == true } == true

  private fun composition(source: MediaSource) = EditComposition(listOf(Track(listOf(Clip(source)))))

  private fun composition(clip: Clip) = EditComposition(listOf(Track(listOf(clip))))

  /**
   * Copies a packaged fixture into the cache, or null when the build had no ffmpeg to make one.
   */
  private fun fixture(name: String): MediaSource? {
    val stream = javaClass.classLoader?.getResourceAsStream(name) ?: return null
    val file = File(context.cacheDir, name)
    stream.use { input -> file.outputStream().use(input::copyTo) }
    return MediaSource.of(file.path)
  }

  private fun MediaSink.asSource(): MediaSource =
    when (this) {
      is MediaSink.Path -> MediaSource.of(path)
      is MediaSink.Uri -> MediaSource.ofUri(uri)
      is MediaSink.Temporary -> throw AssertionError("Temporary resolves to a real path on success")
    }

  private infix fun Duration.shouldBeCloseTo(expected: Duration) =
    assertTrue((this - expected).absoluteValue <= DURATION_TOLERANCE, "expected about $expected, got $this")

  private infix fun Int?.shouldBeCloseTo(expected: Int) =
    assertTrue(this != null && abs(this - expected) <= SIZE_TOLERANCE, "expected about $expected, got $this")

  private companion object {
    val TIMEOUT = 5.minutes

    const val CLIP_A = "android_export_a.mp4"
    const val CLIP_B = "android_export_b.mp4"
    const val CLIP_LONG = "android_export_long.mp4"
    const val CLIP_ROTATED = "android_export_rotated.mp4"

    // How long the muxer gets to create the file, and how often it is looked for.
    val MUXER_OPENS = 10.seconds
    val POLL = 10.milliseconds

    // A trim lands on frame boundaries, and a container's reported duration rounds.
    val DURATION_TOLERANCE = 150.milliseconds

    // Encoders align to their own multiple, which is 2 on most and 16 on some.
    const val SIZE_TOLERANCE = 16
  }
}
