package dev.jordond.filmstrip.media3

import android.graphics.Bitmap
import androidx.test.platform.app.InstrumentationRegistry
import dev.jordond.filmstrip.CapabilitiesResult
import dev.jordond.filmstrip.ComponentRegistry
import dev.jordond.filmstrip.Filmstrip
import dev.jordond.filmstrip.edit.AudioLevel
import dev.jordond.filmstrip.edit.AudioSpec
import dev.jordond.filmstrip.edit.Clip
import dev.jordond.filmstrip.edit.EditComposition
import dev.jordond.filmstrip.edit.TimeRange
import dev.jordond.filmstrip.edit.Track
import dev.jordond.filmstrip.edit.TrackContent
import dev.jordond.filmstrip.edit.compositionOf
import dev.jordond.filmstrip.effects.BuiltInEffectResolver
import dev.jordond.filmstrip.effects.geometry.Rotate
import dev.jordond.filmstrip.effects.geometry.Scale
import dev.jordond.filmstrip.export.AdjustmentKind
import dev.jordond.filmstrip.export.CopyBlocker
import dev.jordond.filmstrip.export.ExportPath
import dev.jordond.filmstrip.export.ExportPlan
import dev.jordond.filmstrip.export.ExportSpec
import dev.jordond.filmstrip.export.ExportStatus
import dev.jordond.filmstrip.export.Verdict
import dev.jordond.filmstrip.media.FormatHint
import dev.jordond.filmstrip.media.MediaInfo
import dev.jordond.filmstrip.media.MediaSink
import dev.jordond.filmstrip.media.MediaSource
import dev.jordond.filmstrip.media.ProbeResult
import dev.jordond.filmstrip.media.chainedProber
import dev.jordond.filmstrip.test.ToneAnalysis.MEASURED_GAIN_TOLERANCE
import dev.jordond.filmstrip.transform.internal.ResolveResult
import dev.jordond.filmstrip.transform.internal.ResolvedClip
import dev.jordond.filmstrip.transform.internal.ResolvedComposition
import dev.jordond.filmstrip.transform.internal.ResolvedTrack
import dev.jordond.filmstrip.transform.internal.passesCovering
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.cancelAndJoin
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.toList
import kotlinx.coroutines.launch
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.withContext
import kotlinx.coroutines.withTimeoutOrNull
import java.io.File
import kotlin.math.abs
import kotlin.math.roundToInt
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertIs
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue
import kotlin.time.Duration
import kotlin.time.Duration.Companion.milliseconds
import kotlin.time.Duration.Companion.minutes
import kotlin.time.Duration.Companion.seconds

/**
 * The end-to-end pass: real clips, real hardware encoders, a real file, read back with the same
 * prober a caller would use.
 *
 * Skipped when the fixtures are absent, since they are generated by host
 * ffmpeg at build time and a machine without one has nothing to export from.
 */
class AndroidExportTest {
  private val context = InstrumentationRegistry.getInstrumentation().targetContext
  private val filmstrip = Filmstrip(context) { media3Backend() }

  // The engine `filmstrip` exports through, built again here because only it can hand back the
  // lowered composition. A test that wants the gain an export applies has to read the plan's own
  // fold rather than multiply the levels a second time.
  private val components = ComponentRegistry.Builder().add(BuiltInEffectResolver()).build()
  private val engine = media3ExportEngine(chainedProber(components), components.effectResolvers)

  @Test
  fun reportsWhatTheEncodersCanDo() =
    runTest(timeout = TIMEOUT) {
      val result = filmstrip.capabilities()

      assertIs<CapabilitiesResult.Success>(result)
      assertTrue(result.capabilities.video.isNotEmpty(), "expected at least one video encoder")
    }

  @Test
  fun downscalesAClipAndWritesWhatThePlanPromised() =
    runTest(timeout = TIMEOUT) {
      val source = fixture(CLIP_A) ?: return@runTest

      val written = export(capablePlan(composition(source), ExportSpec(targetHeight = 240)))

      written.video?.displaySize?.height shouldBeCloseTo 240
      written.duration shouldBeCloseTo 2_000.milliseconds
    }

  @Test
  fun honoursAScaleEffectTheSameWayAsATargetHeight() =
    runTest(timeout = TIMEOUT) {
      val source = fixture(CLIP_A) ?: return@runTest
      val scaled = composition(Clip(source, effects = listOf(Scale(targetHeight = 240))))

      val written = export(capablePlan(scaled, ExportSpec()))

      written.video?.displaySize?.height shouldBeCloseTo 240
    }

  @Test
  fun trimsToTheRequestedWindow() =
    runTest(timeout = TIMEOUT) {
      val source = fixture(CLIP_A) ?: return@runTest
      val trimmed = composition(Clip(source, trim = TimeRange.of(500.milliseconds, 1_500.milliseconds)))

      val written = export(capablePlan(trimmed, ExportSpec(targetHeight = 240)))

      written.duration shouldBeCloseTo 1_000.milliseconds
    }

  @Test
  fun concatenatesTwoClipsOfDifferingSizes() =
    runTest(timeout = TIMEOUT) {
      val first = fixture(CLIP_A) ?: return@runTest
      val second = fixture(CLIP_B) ?: return@runTest
      val joined = EditComposition(listOf(Track(listOf(Clip(first), Clip(second)))))

      val written = export(capablePlan(joined, ExportSpec(targetHeight = 240)))

      written.duration shouldBeCloseTo 4_000.milliseconds
      written.video?.displaySize?.height shouldBeCloseTo 240
    }

  @Test
  fun removingAudioWritesNoAudioTrack() =
    runTest(timeout = TIMEOUT) {
      val source = fixture(CLIP_A) ?: return@runTest
      val silent = composition(source).withAudio(AudioSpec.Remove)

      val written = export(capablePlan(silent, ExportSpec(targetHeight = 240)))

      assertNull(written.audio, "AudioSpec.Remove must not leave an audio track behind")
    }

  // The whole point of AudioSpec.AudioOnly is a file with no video track, so an assertion that
  // only checked the audio survived would pass even if a full video track were written alongside
  // it.
  @Test
  fun audioOnlyWritesAnAudioTrackAndNoVideoTrack() =
    runTest(timeout = TIMEOUT) {
      val source = fixture(CLIP_A) ?: return@runTest
      val audioOnly = composition(source).withAudio(AudioSpec.AudioOnly)

      val plan = capablePlan(audioOnly, ExportSpec())
      val statuses = withContext(Dispatchers.Default) { filmstrip.export(plan, MediaSink.temporary()).toList() }

      assertTrue(statuses.first() is ExportStatus.Started, "the first status is always Started")
      val finished = statuses.last()
      if (finished is ExportStatus.Failure) throw AssertionError("export failed: ${finished.error.message}")
      val success = assertIs<ExportStatus.Success>(finished)

      // Read it back the way a caller would, without trusting what the encoder reported.
      val written = assertIs<ProbeResult.Success>(filmstrip.probe(success.output.asSource())).info
      val audio = assertNotNull(written.audio, "the written file has no audio track")
      assertTrue(audio.sampleRate > 0, "expected a sane sample rate, got ${audio.sampleRate}")
      assertNull(written.video, "AudioSpec.AudioOnly must not leave a video track behind")
      written.duration shouldBeCloseTo 2_000.milliseconds
    }

  /**
   * A music bed mixed under the primary, read back out of the file the encoder wrote.
   *
   * The two sources carry different tones, so a level measured in the output can be attributed to
   * one of them instead of to their sum. The bed opens late and its clip is trimmed short enough to
   * repeat inside the primary's two seconds, which is what puts a later pass under the middle of
   * the timeline where an offset that never applied and a loop that never repeated both show up.
   */
  @Test
  fun mixesALoopingBedUnderThePrimaryAtTheGainThePlanFolded() =
    runTest(timeout = TIMEOUT) {
      val primaryFile = fixtureFile(CLIP_A) ?: return@runTest
      val bedFile = fixtureFile(CLIP_BED) ?: return@runTest
      val spec = ExportSpec(targetHeight = 240)
      val edit =
        EditComposition(
          listOf(
            Track(listOf(Clip(MediaSource.of(primaryFile.path)))),
            Track(
              clips = listOf(Clip(MediaSource.of(bedFile.path), trim = TimeRange.of(Duration.ZERO, BED_PASS))),
              content = TrackContent.Audio,
              audio = AudioLevel.Volume(BED_VOLUME),
              start = BED_START,
              looping = true,
            ),
          ),
        )

      val lowered = lowered(edit, spec)
      val primaryClip = lowered.tracks[0].clips.single()
      val laid = lowered.tracks[1].clips
      val tones = sourceTones(primaryFile, bedFile)

      val written = decodeAudio(exportedFile(capablePlan(edit, spec)))

      assertTrue(
        written.duration >= MIDDLE_AT + WINDOW,
        "the decode ran out at ${written.duration}, before the window this measures",
      )

      // Before the bed opens the plan has it silent, which is what a track that ignored its start
      // breaks.
      val early = EARLY_AT + WINDOW / 2
      val beforeStart = written.bedGainAt(early, WINDOW, tones, primaryClip.gain.gainAt(early))
      assertTrue(
        beforeStart <= MEASURED_GAIN_TOLERANCE,
        "the bed plays at $beforeStart before it starts, so the start never applied",
      )

      // The middle of the timeline, inside a pass the bed only reaches by repeating. The planner
      // holds one clip per pass, so which pass covers the reading and how far into it the reading
      // sits both come off the laid list instead of being worked out from the fixture's length.
      val middle = MIDDLE_AT + WINDOW / 2
      val pass = laid.passCovering(middle)
      val measured = written.bedGainAt(middle, WINDOW, tones, primaryClip.gain.gainAt(middle))
      val expected = laid[pass].gain.gainAt(middle - laid[pass].span.start)
      assertTrue(
        pass >= 1,
        "$middle lands in pass ${pass + 1} of ${laid.size}, so nothing here is past the bed's own end",
      )
      assertTrue(
        abs(measured - expected) <= MEASURED_GAIN_TOLERANCE,
        "the bed plays at $measured a loop pass past its own end, where the plan folded $expected",
      )
    }

  /**
   * A fade on the bed, read off the written file at points across the ramp rather than at its ends.
   *
   * Written through the DSL, with every reading inside the bed's first pass, so what is measured is
   * the ramp itself rather than what a repeat does with it. Each point is compared against the curve
   * the planner folded at the same instant. A midpoint on its own would not be enough, since a
   * symmetric ramp reads the same at its centre whichever way it runs.
   */
  @Test
  fun fadesTheBedInAlongTheCurveThePlanFolded() =
    runTest(timeout = TIMEOUT) {
      val primaryFile = fixtureFile(CLIP_A) ?: return@runTest
      val bedFile = fixtureFile(CLIP_BED) ?: return@runTest
      val spec = ExportSpec(targetHeight = 240)
      val edit =
        compositionOf {
          clip(MediaSource.of(primaryFile.path))
          track(TrackContent.Audio) {
            clip(MediaSource.of(bedFile.path)) { trim(Duration.ZERO, FADE_PASS) }
            fadeIn(FADE_LENGTH)
            startAt(BED_START)
            looping()
          }
        }

      val lowered = lowered(edit, spec)
      val primaryClip = lowered.tracks[0].clips.single()
      val bedClip = lowered.tracks[1].clips.first()
      val tones = sourceTones(primaryFile, bedFile)

      val written = decodeAudio(exportedFile(capablePlan(edit, spec)))

      assertTrue(
        written.duration >= BED_START + RAMP_AT.last() + RAMP_WINDOW,
        "the decode ran out at ${written.duration}, before the ramp this measures",
      )

      val firstPassEnds = bedClip.span.start + bedClip.duration
      RAMP_AT.forEach { inClip ->
        val at = bedClip.span.start + inClip
        assertTrue(at < firstPassEnds, "$at reads past the first pass, which ends at $firstPassEnds")
        val measured = written.bedGainAt(at, RAMP_WINDOW, tones, primaryClip.gain.gainAt(at))
        val expected = bedClip.gain.gainAt(inClip)
        assertTrue(
          abs(measured - expected) <= MEASURED_GAIN_TOLERANCE,
          "the bed plays at $measured $inClip into its pass, where the plan folded $expected",
        )
      }
    }

  /**
   * Every pass of a trimmed, offset bed, read out of the written file against the gain the planner
   * laid for that pass.
   *
   * The track's fade runs once over the whole run rather than restarting each pass, so pass two
   * opens well above zero and the ramp is read at a quarter and at three quarters of its length
   * instead of only at its middle. The last pass is cut where the composition ends, and a backend
   * that laid a whole pass there runs long.
   */
  @Test
  fun measuresEveryPassOfALoopingBedAgainstTheLaidGain() =
    runTest(timeout = TIMEOUT) {
      val primaryFile = fixtureFile(CLIP_LONG) ?: return@runTest
      val bedFile = fixtureFile(CLIP_BED) ?: return@runTest
      val spec = ExportSpec(targetHeight = 240)
      val edit =
        compositionOf {
          clip(MediaSource.of(primaryFile.path)) { trim(Duration.ZERO, PRIMARY_RUN) }
          track(TrackContent.Audio) {
            clip(MediaSource.of(bedFile.path)) { trim(LOOP_BED_TRIM) }
            fadeIn(TRACK_FADE)
            startAt(LOOP_BED_START)
            looping()
          }
        }

      val lowered = lowered(edit, spec)
      val primaryClip = lowered.tracks[0].clips.single()
      val laid = lowered.tracks[1].clips
      lowered.tracks[1].pinSchedule(edit.tracks[1], lowered.duration, CASE_ONE_PASSES, CASE_ONE_CUT)
      // Without this the whole case reads zero against zero and passes while the fade replays.
      assertTrue(
        laid[1].gain.gainAt(Duration.ZERO) > MEASURED_GAIN_TOLERANCE,
        "pass two opens at ${laid[1].gain.gainAt(Duration.ZERO)}, so the track fade restarted rather than carried on",
      )
      val tones = sourceTones(primaryFile, bedFile)

      val plan = capablePlan(edit, spec)
      val file = exportedFile(plan)
      val written = decodeAudio(file)

      val quiet = written.bedGainAt(BEFORE_BED, LOOP_WINDOW, tones, primaryClip.gain.gainAt(BEFORE_BED))
      assertTrue(quiet <= MEASURED_GAIN_TOLERANCE, "the bed plays at $quiet at $BEFORE_BED, before it starts")

      CASE_ONE_READINGS.forEach { written.readBed(laid, it, tones, primaryClip) }

      assertRunsFor(assertNotNull(probeOf(file)), written, tones, plan)
    }

  /**
   * A looping track of two clips, told apart in the mix by the volume the second one carries.
   *
   * Both clips carry the same tone, so what separates them is the level, and reading each of them a
   * pass or more past the first is what catches a track that went silent after pass one. The reading
   * inside the quieter clip is also held below the louder one, since a lowering that played both
   * clips of a pass over each other reads their sum there.
   */
  @Test
  fun tellsTwoLoopingBedClipsApartByTheVolumeTheyCarry() =
    runTest(timeout = TIMEOUT) {
      val primaryFile = fixtureFile(CLIP_LONG) ?: return@runTest
      val bedFile = fixtureFile(CLIP_BED) ?: return@runTest
      val spec = ExportSpec(targetHeight = 240)
      val edit =
        compositionOf {
          clip(MediaSource.of(primaryFile.path)) { trim(Duration.ZERO, PRIMARY_RUN) }
          track(TrackContent.Audio) {
            clip(MediaSource.of(bedFile.path)) {
              trim(LOUD_CLIP_TRIM)
              audio(AudioLevel.Inherit)
            }
            clip(MediaSource.of(bedFile.path)) {
              trim(QUIET_CLIP_TRIM)
              audio(AudioLevel.Volume(QUIET_CLIP_VOLUME))
            }
            startAt(PAIR_BED_START)
            looping()
          }
        }

      val lowered = lowered(edit, spec)
      val primaryClip = lowered.tracks[0].clips.single()
      val laid = lowered.tracks[1].clips
      lowered.tracks[1].pinSchedule(edit.tracks[1], lowered.duration, CASE_TWO_PASSES, CASE_TWO_CUT)
      assertEquals(
        CASE_TWO_CLIPS,
        laid.map { it.sourceIndex },
        "the two clips of the run did not alternate, so a pass was laid from the wrong one",
      )
      val tones = sourceTones(primaryFile, bedFile)

      val plan = capablePlan(edit, spec)
      val file = exportedFile(plan)
      val written = decodeAudio(file)

      val levels = CASE_TWO_READINGS.map { written.readBed(laid, it, tones, primaryClip) }
      val (loud, quiet) = levels

      assertTrue(loud > MEASURED_GAIN_TOLERANCE, "the bed read $loud a pass past its first, so it went silent")
      assertTrue(
        quiet < loud - MEASURED_GAIN_TOLERANCE,
        "the quiet clip read $quiet against the loud clip's $loud, so the two play over each other",
      )

      assertRunsFor(assertNotNull(probeOf(file)), written, tones, plan)
    }

  /**
   * A looping video primary under a longer audio-only track, so what repeats is the picture as well
   * as the tone.
   *
   * The audio track is the one that fixes the composition's length, which puts three whole passes
   * and a cut one under it. The frame is read the same distance into two different passes, where the
   * same instant of the source has to come back, since a primary that stopped after its first pass
   * leaves the fill colour there instead.
   */
  @Test
  fun loopsAVideoPrimaryUnderALongerAudioTrack() =
    runTest(timeout = TIMEOUT) {
      val bedFile = fixtureFile(CLIP_BED) ?: return@runTest
      val toneFile = fixtureFile(CLIP_LONG) ?: return@runTest
      val spec = ExportSpec(targetHeight = 240)
      // The primary track is the looping one here, which the builder has no verb for.
      val edit =
        EditComposition(
          listOf(
            Track(
              clips = listOf(Clip(MediaSource.of(bedFile.path), trim = VIDEO_LOOP_TRIM)),
              looping = true,
            ),
            Track(
              clips = listOf(Clip(MediaSource.of(toneFile.path), trim = TimeRange.of(Duration.ZERO, UNDERLAY_RUN))),
              content = TrackContent.Audio,
            ),
          ),
        )

      val lowered = lowered(edit, spec)
      val laid = lowered.tracks[0].clips
      lowered.tracks[0].pinSchedule(edit.tracks[0], lowered.duration, CASE_THREE_PASSES, CASE_THREE_CUT)
      val underlay = lowered.tracks[1].clips.single()
      val tones = sourceTones(toneFile, bedFile)

      val plan = capablePlan(edit, spec)
      val file = exportedFile(plan)
      val written = decodeAudio(file)

      val early = written.amplitudeOver(EARLY_AT, LOOP_WINDOW, PRIMARY_HZ)
      assertTrue(early > tones.primary * AUDIBLE, "the audio-only track reads $early at $EARLY_AT")
      CASE_THREE_READINGS.forEach { written.readBed(laid, it, tones, underlay) }

      // The same distance into two passes is the same instant of the source, so the two frames are
      // the same picture unless the primary stopped repeating. A third frame at a different instant
      // of the source is what says the band being compared moves at all, since a run that froze on
      // one frame would match itself everywhere.
      val repeated = frameOf(file, laid[CASE_THREE_READINGS.first().pass].span.start + FRAME_INTO)
      val first = frameOf(file, laid.first().span.start + FRAME_INTO)
      val elsewhere = frameOf(file, laid.first().span.start + FRAME_ELSEWHERE)
      assertTrue(
        repeated.grid().maxOf(::luminance) > LIT,
        "the frame a pass past the first reads ${repeated.grid()}, which is the fill and not the clip",
      )
      repeated.grid().zip(first.grid()).forEach { (later, opening) ->
        assertTrue(
          distance(later, opening) <= FRAME_TOLERANCE,
          "a repeated frame reads $later where the first pass reads $opening at the same instant of the source",
        )
      }
      val sameInstant = spread(repeated.band(), first.band())
      val otherInstant = spread(repeated.band(), elsewhere.band())
      assertTrue(
        otherInstant > sameInstant + FRAME_TOLERANCE,
        "the moving band reads $otherInstant apart at a different instant of the source and " +
          "$sameInstant apart at the same one, so it is not moving and the comparison says nothing",
      )

      assertRunsFor(assertNotNull(probeOf(file)), written, tones, plan)
    }

  // The top of the encoder's range, which nothing else here reaches. A phone that cannot do 2160
  // has to say so through the plan, never by writing something smaller in silence.
  @Test
  fun exportsAtFourKOrReportsTheClamp() =
    runTest(timeout = TIMEOUT) {
      val source = fixture(CLIP_LONG) ?: return@runTest
      // A software encoder will accept a 4K request and then write whatever it feels like, so the
      // claim below is about hardware. The emulator is the case this skips.
      if (!hasHardwareEncoder()) return@runTest

      val verdict = filmstrip.plan(composition(source), ExportSpec(targetHeight = 2_160))

      val plan =
        when (verdict) {
          is Verdict.Capable -> {
            verdict.plan
          }
          is Verdict.Degraded -> {
            assertTrue(
              verdict.adjustments.any { it.kind == AdjustmentKind.ResolutionClamped },
              "4K was refused for a reason other than the resolution: ${verdict.adjustments.map { it.message }}",
            )
            verdict.plan
          }
          is Verdict.Incapable -> {
            throw AssertionError("refused: ${verdict.reasons.map { it.message }}")
          }
        }

      // Whatever the plan settled on is what has to come out, so a clamp is honoured and not
      // merely announced.
      val written = export(plan)
      written.video?.displaySize?.height shouldBeCloseTo plan.output.size.height
    }

  @Test
  fun cancellingLeavesNoPartialFile() =
    runTest(timeout = TIMEOUT) {
      val source = fixture(CLIP_LONG) ?: return@runTest
      // Not the cache. A destination the caller named is the one the guarantee is about, and an
      // intermediate under cacheDir would be swept up whether or not the guarantee holds.
      val output = File(context.filesDir, "cancelled.mp4")
      output.delete()

      val plan = capablePlan(composition(source), ExportSpec(targetHeight = 360))
      // Real time, not the test scheduler's: the point is to stop an export that is under way.
      // Cancelled on Started, not after a fixed window, since a hardware encode outruns
      // any window worth waiting for and a run that finished first would be checking that a
      // successful export keeps its file, which is the opposite claim.
      withContext(Dispatchers.Default) {
        val started = CompletableDeferred<Unit>()
        val job =
          launch {
            filmstrip.export(plan, MediaSink.of(output.path)).collect {
              if (it is ExportStatus.Started) started.complete(Unit)
            }
          }
        started.await()
        // A path sink is written to directly, so there is a real file to remove. Waiting for it to
        // turn up is what stops the assertion below passing on an export that had not opened its
        // muxer yet, which would be a claim about nothing.
        assertTrue(output.appears(), "the muxer never opened the file, so there was nothing to leave behind")
        job.cancelAndJoin()
      }

      assertTrue(!output.exists(), "a cancelled export must not leave a half-written file")
    }

  @Test
  fun carriesTheSourceRotationIntoTheOutputContainerWhenItReEncodes() =
    runTest(timeout = TIMEOUT) {
      val source = rotatedFixture() ?: return@runTest
      val rotation = assertNotNull(assertIs<ProbeResult.Success>(filmstrip.probe(source)).info.video).rotationDegrees

      val written = assertNotNull(export(capablePlan(composition(source), ExportSpec(targetHeight = 240))).video)

      assertEquals(rotation, written.rotationDegrees, "coded ${written.codedSize}, display ${written.displaySize}")
      assertTrue(
        written.codedSize.width > written.codedSize.height,
        "expected the frames left landscape, got ${written.codedSize}",
      )
    }

  @Test
  fun carriesTheSourceRotationIntoTheOutputContainerWhenItTransmuxes() =
    runTest(timeout = TIMEOUT) {
      val source = rotatedFixture() ?: return@runTest
      val rotation = assertNotNull(assertIs<ProbeResult.Success>(filmstrip.probe(source)).info.video).rotationDegrees
      val plan = capablePlan(composition(source), ExportSpec())
      assertEquals(ExportPath.Transmux, plan.path, "this export was meant to copy the streams across")

      val written = assertNotNull(export(plan).video)

      assertEquals(rotation, written.rotationDegrees, "coded ${written.codedSize}, display ${written.displaySize}")
    }

  // A trim used to force a re-encode on every backend. A snap tolerance wide enough to reach the
  // sync sample at or before the cut is what leaves an otherwise untouched clip on the copy path,
  // so the claim is both that the path is a copy and that the window survives it.
  @Test
  fun aSnappedTrimCopiesTheWindowRatherThanReEncodingIt() =
    runTest(timeout = TIMEOUT) {
      val source = fixture(CLIP_LONG) ?: return@runTest
      val trimmed =
        composition(Clip(source, trim = TimeRange.of(TRIM_START, TRIM_END), snapWithin = SNAP_WITHIN))

      val plan = capablePlan(trimmed, ExportSpec())
      assertEquals(ExportPath.Transmux, plan.path, "a snapped trim on an untouched clip is meant to copy")
      val clip =
        lowered(trimmed, ExportSpec())
          .tracks
          .first()
          .clips
          .single()
      assertTrue(clip.startsAtKeyFrame, "the copy has no decoder to walk to the cut with")

      val written = export(plan)

      // The cut may open earlier than asked, since a copy has to begin on a sync sample, so the
      // written run is the window at least and the window plus the group it opened in at most.
      assertTrue(
        written.duration >= clip.duration - DURATION_TOLERANCE,
        "the copy wrote ${written.duration} for a window of ${clip.duration}",
      )
      assertTrue(
        written.duration < clip.info.duration - DURATION_TOLERANCE,
        "the copy wrote ${written.duration}, which is the whole ${clip.info.duration} source",
      )
    }

  // A tolerance too narrow to reach a sync sample leaves nothing for the copy to open on, so this
  // trim decodes to its cut like any other, and the plan is left to say why rather than an
  // adjustment nobody asked to be told about.
  @Test
  fun aTrimBeyondItsSnapToleranceTranscodesAndReportsTheBlocker() =
    runTest(timeout = TIMEOUT) {
      val source = fixture(CLIP_LONG) ?: return@runTest
      val trimmed =
        composition(Clip(source, trim = TimeRange.of(TRIM_START, TRIM_END), snapWithin = TOO_NARROW_TO_SNAP))

      val plan = capablePlan(trimmed, ExportSpec())

      assertEquals(ExportPath.Transcode, plan.path, "a cut the tolerance cannot reach has to decode to it")
      assertTrue(
        CopyBlocker.TrimNotOnSyncSample in plan.copyBlockedBy,
        "the caller was not told why the copy was skipped: ${plan.copyBlockedBy}",
      )
    }

  @Test
  fun writesARotateEffectToTheContainerRatherThanTheFrames() =
    runTest(timeout = TIMEOUT) {
      val source = fixture(CLIP_A) ?: return@runTest
      val turned = composition(Clip(source, effects = listOf(Rotate(degrees = 90))))

      val written = assertNotNull(export(capablePlan(turned, ExportSpec())).video)

      // The quarter turn has to land somewhere, and it is not in the frames: they come back the
      // landscape size they went in at, with the container carrying the turn.
      assertTrue(written.rotationDegrees != 0, "the turn reached neither the frames nor the container")
      assertTrue(
        written.codedSize.width > written.codedSize.height,
        "expected the frames left landscape, got ${written.codedSize}",
      )
      assertTrue(
        written.displaySize.height > written.displaySize.width,
        "expected a portrait display, got ${written.displaySize}",
      )
    }

  /**
   * The rotated clip, checked to still carry its quarter turn before anything is asked of it.
   *
   * A fixture that lost its rotation somewhere between ffmpeg and the device would make the
   * rotation tests pass by describing a clip that was never rotated.
   */
  private suspend fun rotatedFixture(): MediaSource? {
    val source = fixture(CLIP_ROTATED) ?: return null
    val video = assertNotNull(assertIs<ProbeResult.Success>(filmstrip.probe(source)).info.video)

    assertTrue(video.rotationDegrees != 0, "the fixture arrived without its rotation")
    assertTrue(video.codedSize.width > video.codedSize.height, "the fixture's frames are not landscape")
    assertTrue(video.displaySize.height > video.displaySize.width, "the fixture does not display portrait")
    return source
  }

  /**
   * The graph an export of [composition] would run, which is where the folded gain curves live.
   *
   * A curve is indexed by its own clip's time, so a caller sampling one converts from the
   * composition timeline itself rather than being handed a number for a fixed instant.
   */
  private suspend fun lowered(
    composition: EditComposition,
    spec: ExportSpec,
  ): ResolvedComposition =
    when (val result = engine.resolve(composition, spec)) {
      is ResolveResult.Resolved -> result.composition
      is ResolveResult.Refused -> throw AssertionError("the mix would not lower: ${result.error.message}")
    }

  /**
   * The tone each fixture carries, measured rather than assumed.
   *
   * What every assertion here compares is a gain, so the level the two sines happen to be written
   * at has to divide out along with the codec's. Read past the head of the file, where an AAC
   * decoder emits its priming samples.
   */
  private fun sourceTones(
    primary: File,
    bed: File,
  ): SourceTones =
    SourceTones(
      primary = decodeAudio(primary).amplitudeOver(EARLY_AT, WINDOW, PRIMARY_HZ),
      bed = decodeAudio(bed).amplitudeOver(EARLY_AT, WINDOW, BED_HZ),
    )

  /**
   * How loud each source's own tone is before anything is done to it.
   */
  private class SourceTones(
    val primary: Float,
    val bed: Float,
  )

  /**
   * The gain the bed plays at over the [window] centred on [at], on the scale the plan folds to.
   *
   * Both tones ride the same encode, so dividing one by the other cancels whatever the codec did to
   * the absolute level and leaves the ratio the two gains stand in. [primaryGain] is what the plan
   * folded for the track being divided by, so a primary that is itself scaled cannot read as a
   * louder bed.
   *
   * A window over a linear ramp reads its mean, which for a window centred on the point being asked
   * about is the value at that point.
   */
  private fun DecodedAudio.bedGainAt(
    at: Duration,
    window: Duration,
    tones: SourceTones,
    primaryGain: Float,
  ): Float {
    val from = at - window / 2
    val bed = amplitudeOver(from, window, BED_HZ)
    val primary = amplitudeOver(from, window, PRIMARY_HZ)
    // Guards the division rather than bounding an error. The primary plays across every window
    // measured here, so one that reads nothing is a decode that stopped, not a bed that behaved.
    assertTrue(primary > tones.primary * AUDIBLE, "the primary reads $primary at $at, so nothing was decoded there")
    return bed / primary * primaryGain * (tones.primary / tones.bed)
  }

  /**
   * Where a level is read: which laid pass, and how far into that pass.
   *
   * The instant on the composition clock and the level to expect both come off the same laid clip,
   * so a schedule that moved takes the reading with it rather than measuring the wrong stretch at
   * the right number.
   */
  private class Reading(
    val pass: Int,
    val into: Duration,
  )

  /**
   * Which laid pass covers [at].
   */
  private fun List<ResolvedClip>.passCovering(at: Duration): Int {
    val index = indexOfLast { it.span.start <= at }
    assertTrue(index >= 0, "$at sits before the first of $size laid passes")
    val clip = this[index]
    assertTrue(
      at < clip.span.start + clip.duration,
      "$at falls in the gap after pass ${index + 1}, which ends at ${clip.span.start + clip.duration}",
    )
    return index
  }

  /**
   * Holds this track's laid clips to the run [passesCovering] derives for [raw] over a composition
   * of [duration], and to [passes] passes with the last cut to [cut].
   *
   * Every clip is pinned, by which entry of the track it was laid from and by the slot it holds, so
   * a pass in the wrong place or laid from the wrong clip fails by name before any level is read.
   * The expectation runs through the same function the planner laid with rather than through a list
   * written out here, which would only say that two people typed the same schedule.
   */
  private fun ResolvedTrack.pinSchedule(
    raw: Track,
    duration: Duration,
    passes: Int,
    cut: Duration,
  ) {
    val lengths = raw.clips.map { assertNotNull(it.duration, "every clip of a pinned track is trimmed") }
    val fill = if (looping) duration - start else lengths.fold(Duration.ZERO, Duration::plus)
    val expected =
      passesCovering(lengths, fill).map { Triple(it.index, start + it.offset, start + it.offset + it.length) }

    assertEquals(passes, clips.size, "the track laid ${clips.map { it.span }}")
    assertEquals(cut, clips.last().duration, "the last pass was not cut where the composition ends")
    assertEquals(
      expected,
      clips.map { Triple(it.sourceIndex, it.span.start, it.span.start + it.duration) },
      "the laid clips are not the run passesCovering derives",
    )
  }

  /**
   * Reads the bed's level at [reading] and holds it to the gain [laid] folded for that pass.
   */
  private fun DecodedAudio.readBed(
    laid: List<ResolvedClip>,
    reading: Reading,
    tones: SourceTones,
    under: ResolvedClip,
  ): Float {
    val clip = laid[reading.pass]
    val at = clip.span.start + reading.into
    val expected = clip.gain.gainAt(reading.into)
    val measured = bedGainAt(at, LOOP_WINDOW, tones, under.gain.gainAt(at))
    assertTrue(
      abs(measured - expected) <= MEASURED_GAIN_TOLERANCE,
      "the bed read $measured at $at, ${reading.into} into pass ${reading.pass + 1} of ${laid.size}, " +
        "where the plan folded $expected",
    )
    return measured
  }

  /**
   * A grid of patch averages over the frame, so a claim about the picture is not made from one pixel
   * that chroma subsampling could have moved anywhere.
   */
  private fun Bitmap.grid(): List<Triple<Int, Int, Int>> =
    FRAME_ACROSS.flatMap { x -> FRAME_DOWN.map { y -> averageAt(x, y) } }

  /**
   * The row of patches across the one band of the test pattern that moves between frames.
   */
  private fun Bitmap.band(): List<Triple<Int, Int, Int>> = FRAME_ACROSS.map { averageAt(it, MOVING_BAND) }

  /**
   * How far apart two rows of patches read, summed over the row.
   */
  private fun spread(
    a: List<Triple<Int, Int, Int>>,
    b: List<Triple<Int, Int, Int>>,
  ): Int = a.zip(b).sumOf { (one, other) -> distance(one, other) }

  /**
   * Holds the written duration to [plan]'s, within one output frame short and one output frame plus
   * one AAC access unit long, and holds whatever was written past one frame to silence.
   *
   * The two allowances differ because a muxer tail only ever adds. Nothing may hide inside the long
   * one, so the stretch past a frame is read for both tones against the levels [tones] says the
   * sources were recorded at. Both the access unit and the frame come off what was written rather
   * than off a figure repeated here: the unit from [decoded]'s own rate, the frame from [plan] or
   * from what [written] reports.
   */
  private fun assertRunsFor(
    written: MediaInfo,
    decoded: DecodedAudio,
    tones: SourceTones,
    plan: ExportPlan,
  ) {
    val rate =
      plan.output.frameRate
        ?: assertNotNull(written.video?.frameRate, "the written file reports no frame rate to measure against")
          .roundToInt()
    val frame = (MILLIS_PER_SECOND / rate).milliseconds
    val accessUnit = AAC_UNIT_SAMPLES.seconds / decoded.sampleRate
    assertTrue(
      written.duration >= plan.duration - frame && written.duration <= plan.duration + frame + accessUnit,
      "the file runs ${written.duration} and decodes ${decoded.duration} of audio, where the plan is " +
        "${plan.duration} and the allowance is one $frame frame plus one $accessUnit access unit",
    )

    // Measured off the end of the decode rather than from an instant the container named, since the
    // two clocks are what this is comparing in the first place.
    val tail = written.duration - plan.duration - frame
    if (tail <= Duration.ZERO) return
    val from = decoded.duration - tail
    val bed = decoded.amplitudeOver(from, tail, BED_HZ)
    val primary = decoded.amplitudeOver(from, tail, PRIMARY_HZ)
    assertTrue(
      bed <= tones.bed * SILENT_TAIL && primary <= tones.primary * SILENT_TAIL,
      "the last $tail of the decode carries $bed at $BED_HZ and $primary at $PRIMARY_HZ, so the file " +
        "runs long with sound still in it rather than on an encoder's flush",
    )
  }

  @Test
  fun exportsAClipHandedOverAsBytes() =
    runTest(timeout = TIMEOUT) {
      val file = fixtureFile(CLIP_A) ?: return@runTest
      val source = MediaSource.ofBytes(file.readBytes(), FormatHint.Mp4)

      // Both the probe and the lowering need this as a file, and both reach it through the same
      // cache, so a buffer that plans is a buffer that encodes.
      val info = export(capablePlan(composition(source), ExportSpec()))

      info.duration shouldBeCloseTo assertNotNull(probeOf(file)).duration
    }

  private suspend fun probeOf(file: File): MediaInfo? =
    (filmstrip.probe(MediaSource.of(file.path)) as? ProbeResult.Success)?.info

  private suspend fun exportedFile(plan: ExportPlan): File {
    val statuses = withContext(Dispatchers.Default) { filmstrip.export(plan, MediaSink.temporary()).toList() }

    val finished = statuses.last()
    if (finished is ExportStatus.Failure) throw AssertionError("export failed: ${finished.error.message}")
    return when (val output = assertIs<ExportStatus.Success>(finished).output) {
      is MediaSink.Path -> File(output.path)
      else -> throw AssertionError("a finished export resolves to a real path, and gave $output")
    }
  }

  private suspend fun capablePlan(
    composition: EditComposition,
    spec: ExportSpec,
  ) = when (val verdict = filmstrip.plan(composition, spec)) {
    is Verdict.Capable -> verdict.plan
    is Verdict.Degraded -> verdict.plan
    is Verdict.Incapable -> throw AssertionError("refused: ${verdict.reasons.map { it.message }}")
  }

  // Collected off the test scheduler, whose virtual clock would spin the backend's progress poll
  // instead of pacing it.
  private suspend fun export(plan: ExportPlan): MediaInfo {
    val statuses = withContext(Dispatchers.Default) { filmstrip.export(plan, MediaSink.temporary()).toList() }

    assertTrue(statuses.first() is ExportStatus.Started, "the first status is always Started")
    val finished = statuses.last()
    if (finished is ExportStatus.Failure) throw AssertionError("export failed: ${finished.error.message}")

    val success = assertIs<ExportStatus.Success>(finished)
    // Close, not equal. The plan measures the first encoder the codec list advertises for the MIME
    // type, media3 picks its own and clamps again to what that one accepts.
    success.info.video
      ?.displaySize
      ?.height shouldBeCloseTo plan.output.size.height
    // Read it back the way a caller would, without trusting what the encoder reported.
    return assertIs<ProbeResult.Success>(filmstrip.probe(success.output.asSource())).info.also {
      assertNotNull(it.video, "the written file has no video track")
    }
  }

  private suspend fun File.appears(): Boolean =
    withTimeoutOrNull(MUXER_OPENS) {
      while (!exists()) delay(POLL)
      true
    } ?: false

  private suspend fun hasHardwareEncoder(): Boolean =
    (filmstrip.capabilities() as? CapabilitiesResult.Success)
      ?.capabilities
      ?.video
      ?.any { it.isHardwareAccelerated == true } == true

  private fun composition(source: MediaSource) = EditComposition(listOf(Track(listOf(Clip(source)))))

  private fun composition(clip: Clip) = EditComposition(listOf(Track(listOf(clip))))

  /**
   * Copies a packaged fixture into the cache, or null when the build had no ffmpeg to make one.
   */
  private fun fixture(name: String): MediaSource? = fixtureFile(name)?.let { MediaSource.of(it.path) }

  /**
   * The same fixture as a file, for a test that reads its samples rather than editing it.
   */
  private fun fixtureFile(name: String): File? {
    val stream = javaClass.classLoader?.getResourceAsStream(name) ?: return null
    val file = File(context.cacheDir, name)
    stream.use { input -> file.outputStream().use(input::copyTo) }
    return file
  }

  private fun MediaSink.asSource(): MediaSource =
    when (this) {
      is MediaSink.Path -> MediaSource.of(path)
      is MediaSink.Uri -> MediaSource.ofUri(uri)
      is MediaSink.Temporary -> throw AssertionError("Temporary resolves to a real path on success")
    }

  private infix fun Duration.shouldBeCloseTo(expected: Duration) =
    assertTrue((this - expected).absoluteValue <= DURATION_TOLERANCE, "expected about $expected, got $this")

  private infix fun Int?.shouldBeCloseTo(expected: Int) =
    assertTrue(this != null && abs(this - expected) <= SIZE_TOLERANCE, "expected about $expected, got $this")

  private companion object {
    val TIMEOUT = 5.minutes

    const val CLIP_A = "android_export_a.mp4"
    const val CLIP_B = "android_export_b.mp4"
    const val CLIP_LONG = "android_export_long.mp4"
    const val CLIP_ROTATED = "android_export_rotated.mp4"
    const val CLIP_BED = "tone_bed_880.mp4"

    // A window inside CLIP_LONG's twelve seconds, opening between two of its sync samples rather
    // than on one, since a cut that already sits on a key frame snaps nowhere and would pass
    // whether the snap works or not. CLIP_LONG is encoded with a key frame every second, so this
    // cut sits half a second past the sync sample it snaps back to.
    val TRIM_START = 4_500.milliseconds
    val TRIM_END = 7_250.milliseconds

    // Comfortably past the half second gap TRIM_START leaves to reach a sync sample.
    val SNAP_WITHIN = 1.seconds

    // Comfortably short of that same gap, so the cut is never mistaken for one the snap reaches.
    val TOO_NARROW_TO_SNAP = 100.milliseconds

    // The one frequency the bed carries and no other fixture does, against the one every other
    // fixture carries. Separating them is what lets a level in the mix be read back to a source.
    const val PRIMARY_HZ = 440
    const val BED_HZ = 880

    const val BED_VOLUME = 0.5f

    // The bed's clip, and the gap in front of it. Different lengths on purpose. A pass has to open
    // every BED_PASS once the bed has started, the way it does on the other three backends, and a
    // reading that counted the gap into the period would open one every BED_START + BED_PASS and
    // leave silence between. Equal lengths hide that, since a pass lands under MIDDLE_AT either way.
    val BED_START = 600.milliseconds
    val BED_PASS = 400.milliseconds

    // Two windows into the primary's two seconds: one in the gap before the bed opens, one in a
    // stretch the bed only covers when its passes run back to back. A period that counted the gap
    // in would be silent across the second of them. Both sit 100ms clear of a boundary, which is
    // more than the priming an AAC decoder can shift the whole run by.
    val EARLY_AT = 100.milliseconds
    val MIDDLE_AT = 1_200.milliseconds
    val WINDOW = 200.milliseconds

    // The fade test's own bed, whose pass is longer than the loop test's so the ramp has room to be
    // read across its range, with a stretch past the ramp's top to read the plateau on.
    val FADE_PASS = 1_200.milliseconds
    val FADE_LENGTH = 800.milliseconds

    // Where the ramp is read, in the bed clip's own time. Three points across it and one past its
    // top, which is what says the ramp stopped at the peak instead of climbing through it. Every
    // window sits 150ms clear of the stretch it measures.
    val RAMP_AT = listOf(200.milliseconds, 400.milliseconds, 600.milliseconds, 1_000.milliseconds)

    // Short enough to sit inside the stretch it measures, and a whole number of cycles of both
    // tones, so neither leaks into the other's reading.
    val RAMP_WINDOW = 100.milliseconds

    // The floor a window's primary tone has to clear against its own source level for the division
    // that recovers a gain to mean anything. Not an accuracy bound, which is
    // ToneAnalysis.MEASURED_GAIN_TOLERANCE and shared with the other three backends.
    const val AUDIBLE = 0.5f

    // How long the muxer gets to create the file, and how often it is looked for.
    val MUXER_OPENS = 10.seconds
    val POLL = 10.milliseconds

    // A trim lands on frame boundaries, and a container's reported duration rounds.
    val DURATION_TOLERANCE = 150.milliseconds

    // Encoders align to their own multiple, which is 2 on most and 16 on some.
    const val SIZE_TOLERANCE = 16

    // The three looping cases below carry the same figures on all four backends, so a lowering that
    // lays its passes differently shows up as a divergence rather than as a local tolerance. No two
    // of the offset, the pass length and the composition's own length divide evenly, and the last
    // pass is always cut.
    val PRIMARY_RUN = 7_300.milliseconds

    // Long enough to hold every tone in a window without reaching a pass boundary, and a whole
    // number of cycles of both frequencies so neither leaks into the other's reading.
    val LOOP_WINDOW = 200.milliseconds

    // Case one: one trimmed clip, an offset that is no multiple of the pass, and a track fade still
    // climbing when pass two opens.
    val LOOP_BED_TRIM = TimeRange.of(200.milliseconds, 1_900.milliseconds)
    val LOOP_BED_START = 700.milliseconds
    val TRACK_FADE = 3_000.milliseconds
    val BEFORE_BED = 300.milliseconds
    const val CASE_ONE_PASSES = 4
    val CASE_ONE_CUT = 1_500.milliseconds

    // A quarter and three quarters of the way up the fade, then the plateau, then the cut pass. The
    // two ramp readings sit in different passes, which a fade that restarted each pass gets wrong.
    val CASE_ONE_READINGS =
      listOf(
        Reading(pass = 0, into = 750.milliseconds),
        Reading(pass = 1, into = 550.milliseconds),
        Reading(pass = 2, into = 400.milliseconds),
        Reading(pass = 3, into = 1_100.milliseconds),
      )

    // Case two: two clips of one looping track, separated in the mix by the second one's volume.
    // Their lengths differ so a pass is neither of them alone.
    val LOUD_CLIP_TRIM = TimeRange.of(Duration.ZERO, 1_100.milliseconds)
    val QUIET_CLIP_TRIM = TimeRange.of(1_400.milliseconds, 2_300.milliseconds)
    const val QUIET_CLIP_VOLUME = 0.4f
    val PAIR_BED_START = 500.milliseconds
    const val CASE_TWO_PASSES = 7
    val CASE_TWO_CUT = 800.milliseconds

    // The loud clip and the quiet one inside pass two, the quiet one again a pass later, and the
    // loud one inside the cut pass. The first two are the pair the level comparison is made on, so
    // they lead the list.
    // Which clip of the track each pass is laid from, alternating until the run is covered and the
    // cut pass lands back on the first.
    val CASE_TWO_CLIPS = listOf(0, 1, 0, 1, 0, 1, 0)

    val CASE_TWO_READINGS =
      listOf(
        Reading(pass = 2, into = 500.milliseconds),
        Reading(pass = 3, into = 600.milliseconds),
        Reading(pass = 5, into = 500.milliseconds),
        Reading(pass = 6, into = 500.milliseconds),
      )

    // Case three: a looping video primary under an audio-only track that outlasts it, which is what
    // fixes the composition's length.
    val VIDEO_LOOP_TRIM = TimeRange.of(100.milliseconds, 1_600.milliseconds)
    val UNDERLAY_RUN = 5_300.milliseconds
    const val CASE_THREE_PASSES = 4
    val CASE_THREE_CUT = 800.milliseconds

    val CASE_THREE_READINGS =
      listOf(
        Reading(pass = 2, into = 400.milliseconds),
        Reading(pass = 3, into = 400.milliseconds),
      )

    // How far into a pass the two matching frames are read. The same distance into two passes is
    // the same instant of the source, so the pictures have to match. FRAME_ELSEWHERE is a second
    // instant of the source, a whole second away inside the first pass, that they both have to
    // differ from.
    val FRAME_INTO = 400.milliseconds
    val FRAME_ELSEWHERE = 1_400.milliseconds

    // Where the frame is sampled, as fractions of a 320x240 output. The colour bars across the top
    // and the block in the middle hold still between frames of the source; the digits the pattern
    // counts with sit around the middle and the one band that sweeps is near the bottom, which is
    // MOVING_BAND and the only row that can tell two instants of the source apart.
    val FRAME_ACROSS = listOf(0.2f, 0.5f, 0.8f)
    const val MOVING_BAND = 0.8f
    val FRAME_DOWN = listOf(0.2f, 0.5f, MOVING_BAND)

    // The three channels summed, out of 765. The fill is black, so a frame carrying any of the
    // pattern clears this comfortably and a frame of fill cannot.
    const val LIT = 200

    // Two encodes of one source frame differ by rounding and by what the encoder spent its bits on,
    // and by nothing like the gap between a picture and a flat colour.
    const val FRAME_TOLERANCE = 150

    const val MILLIS_PER_SECOND = 1_000

    // The samples one AAC access unit carries, divided by the rate the decode ran at to give media3
    // its own limit on how far past the plan a file may run, which is the only allowance made.
    // The clipping configuration is set in milliseconds (Media3Composition's setStartPositionMs), so
    // a clip opening part way through an access unit opens on the unit before it and that whole unit
    // reaches the muxer, and the encoder's flush rounds up what is left. Measured on the emulator:
    // the case one bed trimmed from 200ms wrote 7.348s against a 7.300s plan, and the same pass
    // length trimmed from zero wrote 7.327s, one unit shorter.
    const val AAC_UNIT_SAMPLES = 1_024

    // What the tail may carry of either source's own level and still count as silence. The measured
    // tails read under half a percent, and a pass that ran on past the plan would read most of one.
    const val SILENT_TAIL = 0.01f
  }
}
