package dev.jordond.filmstrip.media3

import androidx.test.platform.app.InstrumentationRegistry
import dev.jordond.filmstrip.CapabilitiesResult
import dev.jordond.filmstrip.ComponentRegistry
import dev.jordond.filmstrip.Filmstrip
import dev.jordond.filmstrip.edit.AudioLevel
import dev.jordond.filmstrip.edit.AudioSpec
import dev.jordond.filmstrip.edit.Clip
import dev.jordond.filmstrip.edit.EditComposition
import dev.jordond.filmstrip.edit.TimeRange
import dev.jordond.filmstrip.edit.Track
import dev.jordond.filmstrip.edit.TrackContent
import dev.jordond.filmstrip.edit.compositionOf
import dev.jordond.filmstrip.effects.BuiltInEffectResolver
import dev.jordond.filmstrip.effects.geometry.Rotate
import dev.jordond.filmstrip.effects.geometry.Scale
import dev.jordond.filmstrip.export.AdjustmentKind
import dev.jordond.filmstrip.export.ExportPath
import dev.jordond.filmstrip.export.ExportPlan
import dev.jordond.filmstrip.export.ExportSpec
import dev.jordond.filmstrip.export.ExportStatus
import dev.jordond.filmstrip.export.Verdict
import dev.jordond.filmstrip.media.MediaInfo
import dev.jordond.filmstrip.media.MediaSink
import dev.jordond.filmstrip.media.MediaSource
import dev.jordond.filmstrip.media.ProbeResult
import dev.jordond.filmstrip.media.chainedProber
import dev.jordond.filmstrip.test.ToneAnalysis.MEASURED_GAIN_TOLERANCE
import dev.jordond.filmstrip.transform.internal.ResolveResult
import dev.jordond.filmstrip.transform.internal.ResolvedComposition
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.cancelAndJoin
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.toList
import kotlinx.coroutines.launch
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.withContext
import kotlinx.coroutines.withTimeoutOrNull
import java.io.File
import kotlin.math.abs
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertIs
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue
import kotlin.time.Duration
import kotlin.time.Duration.Companion.milliseconds
import kotlin.time.Duration.Companion.minutes
import kotlin.time.Duration.Companion.seconds

/**
 * The end-to-end pass: real clips, real hardware encoders, a real file, read back with the same
 * prober a caller would use.
 *
 * Skipped when the fixtures are absent, since they are generated by host
 * ffmpeg at build time and a machine without one has nothing to export from.
 */
class AndroidExportTest {
  private val context = InstrumentationRegistry.getInstrumentation().targetContext
  private val filmstrip = Filmstrip(context) { media3Backend() }

  // The engine `filmstrip` exports through, built again here because only it can hand back the
  // lowered composition. A test that wants the gain an export applies has to read the plan's own
  // fold rather than multiply the levels a second time.
  private val components = ComponentRegistry.Builder().add(BuiltInEffectResolver()).build()
  private val engine = media3ExportEngine(chainedProber(components), components.effectResolvers)

  @Test
  fun reportsWhatTheEncodersCanDo() =
    runTest(timeout = TIMEOUT) {
      val result = filmstrip.capabilities()

      assertIs<CapabilitiesResult.Success>(result)
      assertTrue(result.capabilities.video.isNotEmpty(), "expected at least one video encoder")
    }

  @Test
  fun downscalesAClipAndWritesWhatThePlanPromised() =
    runTest(timeout = TIMEOUT) {
      val source = fixture(CLIP_A) ?: return@runTest

      val written = export(capablePlan(composition(source), ExportSpec(targetHeight = 240)))

      written.video?.displaySize?.height shouldBeCloseTo 240
      written.duration shouldBeCloseTo 2_000.milliseconds
    }

  @Test
  fun honoursAScaleEffectTheSameWayAsATargetHeight() =
    runTest(timeout = TIMEOUT) {
      val source = fixture(CLIP_A) ?: return@runTest
      val scaled = composition(Clip(source, effects = listOf(Scale(targetHeight = 240))))

      val written = export(capablePlan(scaled, ExportSpec()))

      written.video?.displaySize?.height shouldBeCloseTo 240
    }

  @Test
  fun trimsToTheRequestedWindow() =
    runTest(timeout = TIMEOUT) {
      val source = fixture(CLIP_A) ?: return@runTest
      val trimmed = composition(Clip(source, trim = TimeRange.of(500.milliseconds, 1_500.milliseconds)))

      val written = export(capablePlan(trimmed, ExportSpec(targetHeight = 240)))

      written.duration shouldBeCloseTo 1_000.milliseconds
    }

  @Test
  fun concatenatesTwoClipsOfDifferingSizes() =
    runTest(timeout = TIMEOUT) {
      val first = fixture(CLIP_A) ?: return@runTest
      val second = fixture(CLIP_B) ?: return@runTest
      val joined = EditComposition(listOf(Track(listOf(Clip(first), Clip(second)))))

      val written = export(capablePlan(joined, ExportSpec(targetHeight = 240)))

      written.duration shouldBeCloseTo 4_000.milliseconds
      written.video?.displaySize?.height shouldBeCloseTo 240
    }

  @Test
  fun removingAudioWritesNoAudioTrack() =
    runTest(timeout = TIMEOUT) {
      val source = fixture(CLIP_A) ?: return@runTest
      val silent = composition(source).withAudio(AudioSpec.Remove)

      val written = export(capablePlan(silent, ExportSpec(targetHeight = 240)))

      assertNull(written.audio, "AudioSpec.Remove must not leave an audio track behind")
    }

  // The whole point of AudioSpec.AudioOnly is a file with no video track, so an assertion that
  // only checked the audio survived would pass even if a full video track were written alongside
  // it.
  @Test
  fun audioOnlyWritesAnAudioTrackAndNoVideoTrack() =
    runTest(timeout = TIMEOUT) {
      val source = fixture(CLIP_A) ?: return@runTest
      val audioOnly = composition(source).withAudio(AudioSpec.AudioOnly)

      val plan = capablePlan(audioOnly, ExportSpec())
      val statuses = withContext(Dispatchers.Default) { filmstrip.export(plan, MediaSink.temporary()).toList() }

      assertTrue(statuses.first() is ExportStatus.Started, "the first status is always Started")
      val finished = statuses.last()
      if (finished is ExportStatus.Failure) throw AssertionError("export failed: ${finished.error.message}")
      val success = assertIs<ExportStatus.Success>(finished)

      // Read it back the way a caller would, without trusting what the encoder reported.
      val written = assertIs<ProbeResult.Success>(filmstrip.probe(success.output.asSource())).info
      val audio = assertNotNull(written.audio, "the written file has no audio track")
      assertTrue(audio.sampleRate > 0, "expected a sane sample rate, got ${audio.sampleRate}")
      assertNull(written.video, "AudioSpec.AudioOnly must not leave a video track behind")
      written.duration shouldBeCloseTo 2_000.milliseconds
    }

  /**
   * A music bed mixed under the primary, read back out of the file the encoder wrote.
   *
   * The two sources carry different tones, so a level measured in the output can be attributed to
   * one of them instead of to their sum. The bed opens late and its clip is trimmed short enough to
   * repeat inside the primary's two seconds, which is what puts a later pass under the middle of
   * the timeline where an offset that never applied and a loop that never repeated both show up.
   */
  @Test
  fun mixesALoopingBedUnderThePrimaryAtTheGainThePlanFolded() =
    runTest(timeout = TIMEOUT) {
      val primaryFile = fixtureFile(CLIP_A) ?: return@runTest
      val bedFile = fixtureFile(CLIP_BED) ?: return@runTest
      val spec = ExportSpec(targetHeight = 240)
      val edit =
        EditComposition(
          listOf(
            Track(listOf(Clip(MediaSource.of(primaryFile.path)))),
            Track(
              clips = listOf(Clip(MediaSource.of(bedFile.path), trim = TimeRange.of(Duration.ZERO, BED_PASS))),
              content = TrackContent.Audio,
              audio = AudioLevel.Volume(BED_VOLUME),
              start = BED_START,
              looping = true,
            ),
          ),
        )

      val lowered = lowered(edit, spec)
      val primaryClip = lowered.tracks[0].clips.single()
      val bedClip = lowered.tracks[1].clips.single()
      val tones = sourceTones(primaryFile, bedFile)

      val written = decodeAudio(exportedFile(capablePlan(edit, spec)))

      assertTrue(
        written.duration >= MIDDLE_AT + WINDOW,
        "the decode ran out at ${written.duration}, before the window this measures",
      )

      // Before the bed opens the plan has it silent, which is what a track that ignored its start
      // breaks.
      val early = EARLY_AT + WINDOW / 2
      val beforeStart = written.bedGainAt(early, WINDOW, tones, primaryClip.gain.gainAt(early))
      assertTrue(
        beforeStart <= MEASURED_GAIN_TOLERANCE,
        "the bed plays at $beforeStart before it starts, so the start never applied",
      )

      // The middle of the timeline, inside a pass the bed only reaches by repeating. Passes run
      // back to back from BED_START, so where this window falls inside one is the elapsed time
      // wrapped by the pass length, and the leading gap is no part of it.
      val middle = MIDDLE_AT + WINDOW / 2
      val intoPass = ((middle - BED_START).inWholeMilliseconds % BED_PASS.inWholeMilliseconds).milliseconds
      val measured = written.bedGainAt(middle, WINDOW, tones, primaryClip.gain.gainAt(middle))
      val expected = bedClip.gain.gainAt(intoPass)
      assertTrue(
        abs(measured - expected) <= MEASURED_GAIN_TOLERANCE,
        "the bed plays at $measured a loop pass past its own end, where the plan folded $expected",
      )
    }

  /**
   * A fade on the bed, read off the written file at points across the ramp rather than at its ends.
   *
   * Written through the DSL, which is where a looping track drops a fade out for want of an end to
   * anchor it to, so the ramp under test is the fade in. Each point is compared against the curve
   * the planner folded at the same instant. A midpoint on its own would not be enough, since a
   * symmetric ramp reads the same at its centre whichever way it runs.
   */
  @Test
  fun fadesTheBedInAlongTheCurveThePlanFolded() =
    runTest(timeout = TIMEOUT) {
      val primaryFile = fixtureFile(CLIP_A) ?: return@runTest
      val bedFile = fixtureFile(CLIP_BED) ?: return@runTest
      val spec = ExportSpec(targetHeight = 240)
      val edit =
        compositionOf {
          clip(MediaSource.of(primaryFile.path))
          track(TrackContent.Audio) {
            clip(MediaSource.of(bedFile.path)) { trim(Duration.ZERO, FADE_PASS) }
            fadeIn(FADE_LENGTH)
            startAt(BED_START)
            looping()
          }
        }

      val lowered = lowered(edit, spec)
      val primaryClip = lowered.tracks[0].clips.single()
      val bedClip = lowered.tracks[1].clips.single()
      val tones = sourceTones(primaryFile, bedFile)

      val written = decodeAudio(exportedFile(capablePlan(edit, spec)))

      assertTrue(
        written.duration >= BED_START + RAMP_AT.last() + RAMP_WINDOW,
        "the decode ran out at ${written.duration}, before the ramp this measures",
      )

      // The bed's first pass, so what is read is the fade itself rather than whatever a repeat does
      // with the processor's sample counter.
      RAMP_AT.forEach { inClip ->
        val at = BED_START + inClip
        val measured = written.bedGainAt(at, RAMP_WINDOW, tones, primaryClip.gain.gainAt(at))
        val expected = bedClip.gain.gainAt(inClip)
        assertTrue(
          abs(measured - expected) <= MEASURED_GAIN_TOLERANCE,
          "the bed plays at $measured $inClip into its pass, where the plan folded $expected",
        )
      }
    }

  // The top of the encoder's range, which nothing else here reaches. A phone that cannot do 2160
  // has to say so through the plan, never by writing something smaller in silence.
  @Test
  fun exportsAtFourKOrReportsTheClamp() =
    runTest(timeout = TIMEOUT) {
      val source = fixture(CLIP_LONG) ?: return@runTest
      // A software encoder will accept a 4K request and then write whatever it feels like, so the
      // claim below is about hardware. The emulator is the case this skips.
      if (!hasHardwareEncoder()) return@runTest

      val verdict = filmstrip.plan(composition(source), ExportSpec(targetHeight = 2_160))

      val plan =
        when (verdict) {
          is Verdict.Capable -> {
            verdict.plan
          }
          is Verdict.Degraded -> {
            assertTrue(
              verdict.adjustments.any { it.kind == AdjustmentKind.ResolutionClamped },
              "4K was refused for a reason other than the resolution: ${verdict.adjustments.map { it.message }}",
            )
            verdict.plan
          }
          is Verdict.Incapable -> {
            throw AssertionError("refused: ${verdict.reasons.map { it.message }}")
          }
        }

      // Whatever the plan settled on is what has to come out, so a clamp is honoured and not
      // merely announced.
      val written = export(plan)
      written.video?.displaySize?.height shouldBeCloseTo plan.output.size.height
    }

  @Test
  fun cancellingLeavesNoPartialFile() =
    runTest(timeout = TIMEOUT) {
      val source = fixture(CLIP_LONG) ?: return@runTest
      // Not the cache. A destination the caller named is the one the guarantee is about, and an
      // intermediate under cacheDir would be swept up whether or not the guarantee holds.
      val output = File(context.filesDir, "cancelled.mp4")
      output.delete()

      val plan = capablePlan(composition(source), ExportSpec(targetHeight = 360))
      // Real time, not the test scheduler's: the point is to stop an export that is under way.
      // Cancelled on Started, not after a fixed window, since a hardware encode outruns
      // any window worth waiting for and a run that finished first would be checking that a
      // successful export keeps its file, which is the opposite claim.
      withContext(Dispatchers.Default) {
        val started = CompletableDeferred<Unit>()
        val job =
          launch {
            filmstrip.export(plan, MediaSink.of(output.path)).collect {
              if (it is ExportStatus.Started) started.complete(Unit)
            }
          }
        started.await()
        // A path sink is written to directly, so there is a real file to remove. Waiting for it to
        // turn up is what stops the assertion below passing on an export that had not opened its
        // muxer yet, which would be a claim about nothing.
        assertTrue(output.appears(), "the muxer never opened the file, so there was nothing to leave behind")
        job.cancelAndJoin()
      }

      assertTrue(!output.exists(), "a cancelled export must not leave a half-written file")
    }

  @Test
  fun carriesTheSourceRotationIntoTheOutputContainerWhenItReEncodes() =
    runTest(timeout = TIMEOUT) {
      val source = rotatedFixture() ?: return@runTest
      val rotation = assertNotNull(assertIs<ProbeResult.Success>(filmstrip.probe(source)).info.video).rotationDegrees

      val written = assertNotNull(export(capablePlan(composition(source), ExportSpec(targetHeight = 240))).video)

      assertEquals(rotation, written.rotationDegrees, "coded ${written.codedSize}, display ${written.displaySize}")
      assertTrue(
        written.codedSize.width > written.codedSize.height,
        "expected the frames left landscape, got ${written.codedSize}",
      )
    }

  @Test
  fun carriesTheSourceRotationIntoTheOutputContainerWhenItTransmuxes() =
    runTest(timeout = TIMEOUT) {
      val source = rotatedFixture() ?: return@runTest
      val rotation = assertNotNull(assertIs<ProbeResult.Success>(filmstrip.probe(source)).info.video).rotationDegrees
      val plan = capablePlan(composition(source), ExportSpec())
      assertEquals(ExportPath.Transmux, plan.path, "this export was meant to copy the streams across")

      val written = assertNotNull(export(plan).video)

      assertEquals(rotation, written.rotationDegrees, "coded ${written.codedSize}, display ${written.displaySize}")
    }

  @Test
  fun writesARotateEffectToTheContainerRatherThanTheFrames() =
    runTest(timeout = TIMEOUT) {
      val source = fixture(CLIP_A) ?: return@runTest
      val turned = composition(Clip(source, effects = listOf(Rotate(degrees = 90))))

      val written = assertNotNull(export(capablePlan(turned, ExportSpec())).video)

      // The quarter turn has to land somewhere, and it is not in the frames: they come back the
      // landscape size they went in at, with the container carrying the turn.
      assertTrue(written.rotationDegrees != 0, "the turn reached neither the frames nor the container")
      assertTrue(
        written.codedSize.width > written.codedSize.height,
        "expected the frames left landscape, got ${written.codedSize}",
      )
      assertTrue(
        written.displaySize.height > written.displaySize.width,
        "expected a portrait display, got ${written.displaySize}",
      )
    }

  /**
   * The rotated clip, checked to still carry its quarter turn before anything is asked of it.
   *
   * A fixture that lost its rotation somewhere between ffmpeg and the device would make the
   * rotation tests pass by describing a clip that was never rotated.
   */
  private suspend fun rotatedFixture(): MediaSource? {
    val source = fixture(CLIP_ROTATED) ?: return null
    val video = assertNotNull(assertIs<ProbeResult.Success>(filmstrip.probe(source)).info.video)

    assertTrue(video.rotationDegrees != 0, "the fixture arrived without its rotation")
    assertTrue(video.codedSize.width > video.codedSize.height, "the fixture's frames are not landscape")
    assertTrue(video.displaySize.height > video.displaySize.width, "the fixture does not display portrait")
    return source
  }

  /**
   * The graph an export of [composition] would run, which is where the folded gain curves live.
   *
   * A curve is indexed by its own clip's time, so a caller sampling one converts from the
   * composition timeline itself rather than being handed a number for a fixed instant.
   */
  private suspend fun lowered(
    composition: EditComposition,
    spec: ExportSpec,
  ): ResolvedComposition =
    when (val result = engine.resolve(composition, spec)) {
      is ResolveResult.Resolved -> result.composition
      is ResolveResult.Refused -> throw AssertionError("the mix would not lower: ${result.error.message}")
    }

  /**
   * The tone each fixture carries, measured rather than assumed.
   *
   * What every assertion here compares is a gain, so the level the two sines happen to be written
   * at has to divide out along with the codec's. Read past the head of the file, where an AAC
   * decoder emits its priming samples.
   */
  private fun sourceTones(
    primary: File,
    bed: File,
  ): SourceTones =
    SourceTones(
      primary = decodeAudio(primary).amplitudeOver(EARLY_AT, WINDOW, PRIMARY_HZ),
      bed = decodeAudio(bed).amplitudeOver(EARLY_AT, WINDOW, BED_HZ),
    )

  /**
   * How loud each source's own tone is before anything is done to it.
   */
  private class SourceTones(
    val primary: Float,
    val bed: Float,
  )

  /**
   * The gain the bed plays at over the [window] centred on [at], on the scale the plan folds to.
   *
   * Both tones ride the same encode, so dividing one by the other cancels whatever the codec did to
   * the absolute level and leaves the ratio the two gains stand in. [primaryGain] is what the plan
   * folded for the track being divided by, so a primary that is itself scaled cannot read as a
   * louder bed.
   *
   * A window over a linear ramp reads its mean, which for a window centred on the point being asked
   * about is the value at that point.
   */
  private fun DecodedAudio.bedGainAt(
    at: Duration,
    window: Duration,
    tones: SourceTones,
    primaryGain: Float,
  ): Float {
    val from = at - window / 2
    val bed = amplitudeOver(from, window, BED_HZ)
    val primary = amplitudeOver(from, window, PRIMARY_HZ)
    // Guards the division rather than bounding an error. The primary plays across every window
    // measured here, so one that reads nothing is a decode that stopped, not a bed that behaved.
    assertTrue(primary > tones.primary * AUDIBLE, "the primary reads $primary at $at, so nothing was decoded there")
    return bed / primary * primaryGain * (tones.primary / tones.bed)
  }

  private suspend fun exportedFile(plan: ExportPlan): File {
    val statuses = withContext(Dispatchers.Default) { filmstrip.export(plan, MediaSink.temporary()).toList() }

    val finished = statuses.last()
    if (finished is ExportStatus.Failure) throw AssertionError("export failed: ${finished.error.message}")
    return when (val output = assertIs<ExportStatus.Success>(finished).output) {
      is MediaSink.Path -> File(output.path)
      else -> throw AssertionError("a finished export resolves to a real path, and gave $output")
    }
  }

  private suspend fun capablePlan(
    composition: EditComposition,
    spec: ExportSpec,
  ) = when (val verdict = filmstrip.plan(composition, spec)) {
    is Verdict.Capable -> verdict.plan
    is Verdict.Degraded -> verdict.plan
    is Verdict.Incapable -> throw AssertionError("refused: ${verdict.reasons.map { it.message }}")
  }

  // Collected off the test scheduler, whose virtual clock would spin the backend's progress poll
  // instead of pacing it.
  private suspend fun export(plan: ExportPlan): MediaInfo {
    val statuses = withContext(Dispatchers.Default) { filmstrip.export(plan, MediaSink.temporary()).toList() }

    assertTrue(statuses.first() is ExportStatus.Started, "the first status is always Started")
    val finished = statuses.last()
    if (finished is ExportStatus.Failure) throw AssertionError("export failed: ${finished.error.message}")

    val success = assertIs<ExportStatus.Success>(finished)
    // Close, not equal. The plan measures the first encoder the codec list advertises for the MIME
    // type, media3 picks its own and clamps again to what that one accepts.
    success.info.video
      ?.displaySize
      ?.height shouldBeCloseTo plan.output.size.height
    // Read it back the way a caller would, without trusting what the encoder reported.
    return assertIs<ProbeResult.Success>(filmstrip.probe(success.output.asSource())).info.also {
      assertNotNull(it.video, "the written file has no video track")
    }
  }

  private suspend fun File.appears(): Boolean =
    withTimeoutOrNull(MUXER_OPENS) {
      while (!exists()) delay(POLL)
      true
    } ?: false

  private suspend fun hasHardwareEncoder(): Boolean =
    (filmstrip.capabilities() as? CapabilitiesResult.Success)
      ?.capabilities
      ?.video
      ?.any { it.isHardwareAccelerated == true } == true

  private fun composition(source: MediaSource) = EditComposition(listOf(Track(listOf(Clip(source)))))

  private fun composition(clip: Clip) = EditComposition(listOf(Track(listOf(clip))))

  /**
   * Copies a packaged fixture into the cache, or null when the build had no ffmpeg to make one.
   */
  private fun fixture(name: String): MediaSource? = fixtureFile(name)?.let { MediaSource.of(it.path) }

  /**
   * The same fixture as a file, for a test that reads its samples rather than editing it.
   */
  private fun fixtureFile(name: String): File? {
    val stream = javaClass.classLoader?.getResourceAsStream(name) ?: return null
    val file = File(context.cacheDir, name)
    stream.use { input -> file.outputStream().use(input::copyTo) }
    return file
  }

  private fun MediaSink.asSource(): MediaSource =
    when (this) {
      is MediaSink.Path -> MediaSource.of(path)
      is MediaSink.Uri -> MediaSource.ofUri(uri)
      is MediaSink.Temporary -> throw AssertionError("Temporary resolves to a real path on success")
    }

  private infix fun Duration.shouldBeCloseTo(expected: Duration) =
    assertTrue((this - expected).absoluteValue <= DURATION_TOLERANCE, "expected about $expected, got $this")

  private infix fun Int?.shouldBeCloseTo(expected: Int) =
    assertTrue(this != null && abs(this - expected) <= SIZE_TOLERANCE, "expected about $expected, got $this")

  private companion object {
    val TIMEOUT = 5.minutes

    const val CLIP_A = "android_export_a.mp4"
    const val CLIP_B = "android_export_b.mp4"
    const val CLIP_LONG = "android_export_long.mp4"
    const val CLIP_ROTATED = "android_export_rotated.mp4"
    const val CLIP_BED = "tone_bed_880.mp4"

    // The one frequency the bed carries and no other fixture does, against the one every other
    // fixture carries. Separating them is what lets a level in the mix be read back to a source.
    const val PRIMARY_HZ = 440
    const val BED_HZ = 880

    const val BED_VOLUME = 0.5f

    // The bed's clip, and the gap in front of it. Different lengths on purpose. A pass has to open
    // every BED_PASS once the bed has started, the way it does on the other three backends, and a
    // reading that counted the gap into the period would open one every BED_START + BED_PASS and
    // leave silence between. Equal lengths hide that, since a pass lands under MIDDLE_AT either way.
    val BED_START = 600.milliseconds
    val BED_PASS = 400.milliseconds

    // Two windows into the primary's two seconds: one in the gap before the bed opens, one in a
    // stretch the bed only covers when its passes run back to back. A period that counted the gap
    // in would be silent across the second of them. Both sit 100ms clear of a boundary, which is
    // more than the priming an AAC decoder can shift the whole run by.
    val EARLY_AT = 100.milliseconds
    val MIDDLE_AT = 1_200.milliseconds
    val WINDOW = 200.milliseconds

    // The fade test's own bed, whose pass is longer than the loop test's so the ramp has room to be
    // read across its range, with a stretch past the ramp's top to read the plateau on.
    val FADE_PASS = 1_200.milliseconds
    val FADE_LENGTH = 800.milliseconds

    // Where the ramp is read, in the bed clip's own time. Three points across it and one past its
    // top, which is what says the ramp stopped at the peak instead of climbing through it. Every
    // window sits 150ms clear of the stretch it measures.
    val RAMP_AT = listOf(200.milliseconds, 400.milliseconds, 600.milliseconds, 1_000.milliseconds)

    // Short enough to sit inside the stretch it measures, and a whole number of cycles of both
    // tones, so neither leaks into the other's reading.
    val RAMP_WINDOW = 100.milliseconds

    // The floor a window's primary tone has to clear against its own source level for the division
    // that recovers a gain to mean anything. Not an accuracy bound, which is
    // ToneAnalysis.MEASURED_GAIN_TOLERANCE and shared with the other three backends.
    const val AUDIBLE = 0.5f

    // How long the muxer gets to create the file, and how often it is looked for.
    val MUXER_OPENS = 10.seconds
    val POLL = 10.milliseconds

    // A trim lands on frame boundaries, and a container's reported duration rounds.
    val DURATION_TOLERANCE = 150.milliseconds

    // Encoders align to their own multiple, which is 2 on most and 16 on some.
    const val SIZE_TOLERANCE = 16
  }
}
