package dev.jordond.filmstrip.ffmpeg

import dev.jordond.filmstrip.CapabilitiesResult
import dev.jordond.filmstrip.Filmstrip
import dev.jordond.filmstrip.edit.AudioSpec
import dev.jordond.filmstrip.edit.TimeRange
import dev.jordond.filmstrip.edit.compositionOf
import dev.jordond.filmstrip.effect.EffectIds
import dev.jordond.filmstrip.effect.EffectSpec
import dev.jordond.filmstrip.effects.color.Brightness
import dev.jordond.filmstrip.effects.color.Contrast
import dev.jordond.filmstrip.effects.color.Saturation
import dev.jordond.filmstrip.effects.color.brightness
import dev.jordond.filmstrip.effects.color.colorMatrixOf
import dev.jordond.filmstrip.effects.color.transform
import dev.jordond.filmstrip.effects.color.transformNits
import dev.jordond.filmstrip.effects.geometry.crop
import dev.jordond.filmstrip.effects.geometry.rotate
import dev.jordond.filmstrip.effects.overlay.textOverlay
import dev.jordond.filmstrip.export.AudioCodec
import dev.jordond.filmstrip.export.ExportError
import dev.jordond.filmstrip.export.ExportPath
import dev.jordond.filmstrip.export.ExportSpec
import dev.jordond.filmstrip.export.ExportStatus
import dev.jordond.filmstrip.export.HdrMode
import dev.jordond.filmstrip.export.Verdict
import dev.jordond.filmstrip.export.VideoCodec
import dev.jordond.filmstrip.ffmpeg.internal.FFMPEG_ENCODERS
import dev.jordond.filmstrip.ffmpeg.internal.ProcessRunner
import dev.jordond.filmstrip.ffmpeg.internal.ToolchainLocator
import dev.jordond.filmstrip.ffmpeg.internal.ToolchainResult
import dev.jordond.filmstrip.ffmpeg.internal.ffmpegEncoders
import dev.jordond.filmstrip.ffmpeg.internal.toneMapRoute
import dev.jordond.filmstrip.geometry.AspectRatio
import dev.jordond.filmstrip.geometry.Fill
import dev.jordond.filmstrip.geometry.Fit
import dev.jordond.filmstrip.geometry.Size
import dev.jordond.filmstrip.media.HdrTransfer
import dev.jordond.filmstrip.media.MediaSink
import dev.jordond.filmstrip.media.MediaSource
import dev.jordond.filmstrip.media.PQ_PEAK_NITS
import dev.jordond.filmstrip.media.ProbeResult
import dev.jordond.filmstrip.media.brightnessDisplayGain
import dev.jordond.filmstrip.media.brightnessSceneGain
import dev.jordond.filmstrip.media.hlgDisplayNitsFromScene
import dev.jordond.filmstrip.media.hlgSceneFromDisplayNits
import dev.jordond.filmstrip.media.hlgSignalFromScene
import dev.jordond.filmstrip.media.nitsFromPqSignal
import dev.jordond.filmstrip.media.pqSignalFromNits
import dev.jordond.filmstrip.media.sceneFromHlgSignal
import dev.jordond.filmstrip.transform.internal.DEFAULT_HDR_LADDER
import io.kotest.matchers.shouldBe
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.cancelAndJoin
import kotlinx.coroutines.flow.toList
import kotlinx.coroutines.launch
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.withContext
import kotlinx.coroutines.withTimeoutOrNull
import java.io.File
import kotlin.math.abs
import kotlin.math.roundToInt
import kotlin.test.Test
import kotlin.test.assertIs
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue
import kotlin.time.Duration.Companion.milliseconds

/**
 * The end-to-end pass: real clips, a real ffmpeg, a real file, verified with ffprobe.
 *
 * Skipped rather than failed when there is no ffmpeg, because the fixtures are generated by the
 * same binary the export drives, so the two are available together or not at all.
 */
class FfmpegExportTest {
  private val fixtures = File(System.getProperty("filmstrip.fixtures").orEmpty())
  private val landscape = File(fixtures, "export_landscape.mp4")
  private val portrait = File(fixtures, "export_portrait.mp4")
  private val long = File(fixtures, "export_long.mp4")
  private val hdr = File(fixtures, "export_hdr.mp4")
  private val hdrHlg = File(fixtures, "export_hdr_hlg.mp4")

  private val filmstrip = Filmstrip { ffmpegBackend() }

  @Test
  fun `reports every encoder the build carries, by name`() =
    runTest(timeout = TIMEOUT) {
      if (!available()) return@runTest

      val result = filmstrip.capabilities()
      assertIs<CapabilitiesResult.Success>(result)
      val video = result.capabilities.video
      assertTrue(video.isNotEmpty(), "expected at least one video encoder")
      assertTrue(video.all { it.encoderName != null }, "every ffmpeg encoder is named")
      // Whether this holds depends on what the build carries, so the assertion reads the same
      // encoder table the probe reads rather than pinning the answer either way. The claim is about
      // the encoder an HDR export actually opens, which is the first ranked one for the codec a
      // kept grade is pinned to, so a build that carries a 10-bit encoder further down the ranking
      // is still expected to answer false.
      val reached =
        DEFAULT_HDR_LADDER.firstNotNullOfOrNull { codec -> video.firstOrNull { it.codec == codec } }
      val encodesHdr =
        FFMPEG_ENCODERS.values.flatten().any { it.name == reached?.encoderName && it.hdrPixelFormat != null }
      result.capabilities.supportsHdrEncoding shouldBe encodesHdr

      // The ranking is this backend's, so what capabilities() resolves is the table's order filtered
      // by what this build has, not whichever encoder answered the probe first.
      VideoCodec.entries.forEach { codec ->
        val ranked = codec.ffmpegEncoders().map { it.name }.filter { name -> video.any { it.encoderName == name } }
        result.capabilities.encoderFor(codec)?.encoderName shouldBe ranked.firstOrNull()
      }
    }

  // libx264 outruns h264_videotoolbox on this machine and hevc_videotoolbox outruns libx265, so the
  // two codecs resolve to opposite sides of the hardware flag. The tag matters as much as the
  // encoder: QuickTime refuses the hev1 an untagged HEVC stream is written as.
  @Test
  fun `encodes HEVC with the encoder the device ranked first`() =
    runTest(timeout = TIMEOUT) {
      if (!available()) return@runTest

      val output = File.createTempFile("filmstrip-hevc", ".mp4").also { it.delete() }
      val composition = compositionOf { clip(MediaSource.of(landscape.absolutePath)) }
      val spec = ExportSpec(targetHeight = 240, videoCodec = VideoCodec.Hevc)

      val capabilities = assertIs<CapabilitiesResult.Success>(filmstrip.capabilities()).capabilities
      val expected = assertNotNull(capabilities.encoderFor(VideoCodec.Hevc)).encoderName

      val statuses = filmstrip.export(composition, spec, MediaSink.of(output.absolutePath)).toList()
      val finished = statuses.last()
      if (finished is ExportStatus.Failure) error(finished.error.message)
      assertIs<ExportStatus.Success>(finished)

      ffprobe(output.absolutePath).endsWith("hevc aac") shouldBe true
      probeField(output.absolutePath, "codec_tag_string") shouldBe "hvc1"
      // ffmpeg writes the encoder it ran into the stream, so this is the file disagreeing with
      // capabilities() rather than the table being asked twice.
      assertTrue(
        probeStreamTag(output.absolutePath, "encoder").endsWith(expected!!),
        "the file was written by something other than $expected",
      )

      output.delete()
    }

  @Test
  fun `probes a source through ffprobe`() =
    runTest(timeout = TIMEOUT) {
      if (!available()) return@runTest

      val result = assertIs<ProbeResult.Success>(filmstrip.probe(MediaSource.of(landscape.absolutePath)))
      val video = assertNotNull(result.info.video)
      video.displaySize shouldBe Size(640, 360)
      video.frameRate!!.roundToInt() shouldBe 30
      assertNotNull(result.info.audio).sampleRate shouldBe 48_000
      assertTrue(result.info.duration in 1_800.milliseconds..2_300.milliseconds, "duration was ${result.info.duration}")
    }

  // The prober reads files, and there is nothing on the desktop that reads a container out of a
  // ByteArray without writing it down first. Core's own prober is consulted after this one and
  // declines too, so the reported failure is the one that names why.
  @Test
  fun `declines bytes it cannot open`() =
    runTest(timeout = TIMEOUT) {
      val result = filmstrip.probe(MediaSource.ofBytes(byteArrayOf(1, 2, 3)))
      val failure = assertIs<ProbeResult.Failure>(result)
      assertIs<ExportError.SourceUnreadable>(failure.error)
    }

  @Test
  fun `reports a missing toolchain rather than a missing artifact`() =
    runTest(timeout = TIMEOUT) {
      val absent =
        Filmstrip {
          ffmpegBackend(FfmpegConfig(executablePath = "/nonexistent/ffmpeg"))
        }

      val failure = assertIs<ProbeResult.Failure>(absent.probe(MediaSource.of(landscape.absolutePath)))
      assertIs<ExportError.ToolchainMissing>(failure.error)
    }

  @Test
  fun `exports two clips into one reframed file`() =
    runTest(timeout = TIMEOUT) {
      if (!available()) return@runTest

      val output = File.createTempFile("filmstrip-export", ".mp4").also { it.delete() }
      val composition =
        compositionOf {
          clip(MediaSource.of(landscape.absolutePath)) {
            trim(TimeRange.of(0.milliseconds, 1_000.milliseconds))
          }
          clip(MediaSource.of(portrait.absolutePath)) {
            trim(TimeRange.of(0.milliseconds, 1_000.milliseconds))
            effects { rotate(180) }
          }
          effects { crop(AspectRatio.Portrait) }
        }

      val spec = ExportSpec(targetHeight = 480)
      val verdict = filmstrip.plan(composition, spec)
      val plan =
        when (verdict) {
          is Verdict.Capable -> verdict.plan
          is Verdict.Degraded -> verdict.plan
          is Verdict.Incapable -> error(verdict.reasons.joinToString { it.message })
        }

      plan.output.size.height shouldBe 480
      plan.output.size.width shouldBe 268

      val statuses = filmstrip.export(plan, MediaSink.of(output.absolutePath)).toList()
      val finished = statuses.last()
      if (finished is ExportStatus.Failure) error(finished.error.message)

      assertIs<ExportStatus.Started>(statuses.first())
      assertTrue(statuses.any { it is ExportStatus.Progress }, "expected progress")

      val success = assertIs<ExportStatus.Success>(finished)
      success.info.video!!.displaySize shouldBe plan.output.size
      success.info.audio!!.sampleRate shouldBe 48_000
      // Two one second clips, laid end to end.
      assertTrue(
        success.info.duration in 1_800.milliseconds..2_300.milliseconds,
        "duration was ${success.info.duration}",
      )

      // Verified independently of the code under test.
      val probe = ffprobe(output.absolutePath)
      probe shouldBe "268x480 30/1 h264 aac"

      output.delete()
    }

  // Portrait-cropping a landscape source with Fit.Contain leaves it far short of the output
  // height, so the bars land top and bottom, wide enough that a sample near either edge sits well
  // clear of the frame's own pixels.
  @Test
  fun `writes a solid fill into the bars a taller frame leaves`() =
    runTest(timeout = TIMEOUT) {
      if (!available()) return@runTest

      val output = File.createTempFile("filmstrip-fill-solid", ".mp4").also { it.delete() }
      val composition =
        compositionOf {
          clip(MediaSource.of(landscape.absolutePath))
          effects { crop(AspectRatio.Portrait, fit = Fit.Contain) }
          fill(Fill.Solid(RED))
        }

      val verdict = filmstrip.plan(composition, ExportSpec())
      val plan =
        when (verdict) {
          is Verdict.Capable -> verdict.plan
          is Verdict.Degraded -> verdict.plan
          is Verdict.Incapable -> error(verdict.reasons.joinToString { it.message })
        }

      val finished = filmstrip.export(plan, MediaSink.of(output.absolutePath)).toList().last()
      if (finished is ExportStatus.Failure) error(finished.error.message)
      assertIs<ExportStatus.Success>(finished)

      val size = plan.output.size
      assertReddish(pixelAt(output.absolutePath, size.width / 2, 2))
      assertReddish(pixelAt(output.absolutePath, size.width / 2, size.height - 2))

      output.delete()
    }

  // A composition-scope grade must not reach a bar it was not given a colour for. Comparing the
  // dimmed export's bars against undimmed red, rather than only asserting reddish, is what
  // separates "the fill is untouched" from "nothing ran at all". The centre comparison is the
  // other half, proving the brightness did run somewhere.
  @Test
  fun `a composition brightness leaves a solid fill's bars untouched`() =
    runTest(timeout = TIMEOUT) {
      if (!available()) return@runTest

      val plain = exportedFillWithBrightness(1f) ?: return@runTest
      val dimmed = exportedFillWithBrightness(0.5f) ?: return@runTest

      assertReddish(dimmed.top)
      assertReddish(dimmed.bottom)
      assertTrue(
        dimmed.top.first > HALVED_RED_CEILING,
        "the top bar's red channel reads halved: ${dimmed.top}, against undimmed ${plain.top}",
      )
      assertTrue(
        dimmed.bottom.first > HALVED_RED_CEILING,
        "the bottom bar's red channel reads halved: ${dimmed.bottom}, against undimmed ${plain.bottom}",
      )

      val ratio = luminance(dimmed.centre).toFloat() / luminance(plain.centre).toFloat()
      assertTrue(
        ratio in HALF - SIGNAL_DRIFT..HALF + SIGNAL_DRIFT,
        "the centre read ${dimmed.centre} against ${plain.centre} undimmed, a ratio of $ratio",
      )
    }

  // The three points this test reads back: two bars far enough from the clip's own pixels to read
  // the fill cleanly, and the centre the clip itself draws.
  private class FillSample(
    val top: Triple<Int, Int, Int>,
    val bottom: Triple<Int, Int, Int>,
    val centre: Triple<Int, Int, Int>,
  )

  private suspend fun exportedFillWithBrightness(factor: Float): FillSample? {
    if (!available()) return null

    val output = File.createTempFile("filmstrip-fill-solid-brightness-$factor", ".mp4").also { it.delete() }
    val composition =
      compositionOf {
        clip(MediaSource.of(landscape.absolutePath))
        effects {
          crop(AspectRatio.Portrait, fit = Fit.Contain)
          if (factor != 1f) brightness(factor)
        }
        fill(Fill.Solid(RED))
      }

    val verdict = filmstrip.plan(composition, ExportSpec())
    val plan =
      when (verdict) {
        is Verdict.Capable -> verdict.plan
        is Verdict.Degraded -> verdict.plan
        is Verdict.Incapable -> error(verdict.reasons.joinToString { it.message })
      }

    val finished = filmstrip.export(plan, MediaSink.of(output.absolutePath)).toList().last()
    if (finished is ExportStatus.Failure) error(finished.error.message)
    assertIs<ExportStatus.Success>(finished)

    val size = plan.output.size
    return FillSample(
      top = pixelAt(output.absolutePath, size.width / 2, 2),
      bottom = pixelAt(output.absolutePath, size.width / 2, size.height - 2),
      centre = pixelAt(output.absolutePath, size.width / 2, size.height / 2),
    ).also { output.delete() }
  }

  // Halving reads as half the signal against the same frame exported untouched. An additive
  // brightness of the same size, or one that multiplied linear light, would both land well outside
  // the band.
  @Test
  fun `halving brightness halves the signal`() =
    runTest(timeout = TIMEOUT) {
      if (!available()) return@runTest

      val lit = exportedBrightness(1f) ?: return@runTest
      val dimmed = exportedBrightness(0.5f) ?: return@runTest

      val ratio = luminance(dimmed).toFloat() / luminance(lit).toFloat()
      assertTrue(
        ratio in HALF - SIGNAL_DRIFT..HALF + SIGNAL_DRIFT,
        "half brightness read $dimmed against $lit at full, a ratio of $ratio",
      )
    }

  // colorchannelmixer caps its gains at 2 and fails the whole graph above that rather than
  // clamping, so a factor past it has to lower to something else or no file is written.
  @Test
  fun `exports a factor past what a channel mixer would take`() =
    runTest(timeout = TIMEOUT) {
      if (!available()) return@runTest

      val lit = exportedBrightness(1f) ?: return@runTest
      val brightened = exportedBrightness(3f) ?: return@runTest

      assertTrue(
        luminance(brightened) > luminance(lit),
        "a 3x brightness read $brightened against $lit at full",
      )
    }

  // A brightness is one more grade, so it goes out the same way. A factor of one carries no effect
  // at all, which is the reference every other factor is read against.
  private suspend fun exportedBrightness(factor: Float): Triple<Int, Int, Int>? =
    exportedGrade("brightness-$factor", Brightness(factor).takeIf { factor != 1f })

  // A contrast is three independent lines, so it reaches the file through the per-channel table.
  // Each channel is read back against what the shared matrix says it should be, which a contrast
  // pivoting on black would miss by tens of code values.
  //
  // A factor that flattens rather than one that stretches, because the fixture is colour bars and
  // every channel of it already sits on an end of the range. Stretching those only reads back the
  // clamp, whatever matrix produced it.
  @Test
  fun `exports a contrast through the per-channel table`() =
    runTest(timeout = TIMEOUT) {
      if (!available()) return@runTest

      assertGraded(Contrast(0.5f), "contrast")
    }

  // A saturation mixes the channels, so it reaches the file through the lookup table written into
  // the scratch directory. Reading the pixel back is what proves the file was written, named and
  // found again.
  @Test
  fun `exports a saturation through the table written beside the graph`() =
    runTest(timeout = TIMEOUT) {
      if (!available()) return@runTest

      assertGraded(Saturation(0.5f), "saturation")
    }

  private suspend fun assertGraded(
    spec: EffectSpec,
    name: String,
  ) {
    val plain = exportedGrade(name, null) ?: return
    val measured = exportedGrade(name, spec) ?: return
    val expected = graded(plain, spec)

    assertTrue(
      abs(measured.first - expected.first) <= CHANNEL_DRIFT &&
        abs(measured.second - expected.second) <= CHANNEL_DRIFT &&
        abs(measured.third - expected.third) <= CHANNEL_DRIFT,
      "the graded centre read $measured against $expected from the shared matrix, on a plain $plain",
    )
  }

  // What the shared matrix says the same pixel comes out as, in the code values the readback
  // reports, so a backend that lowered a different matrix fails here rather than drifting.
  private fun graded(
    plain: Triple<Int, Int, Int>,
    spec: EffectSpec,
  ): Triple<Int, Int, Int> {
    val matrix = checkNotNull(colorMatrixOf(spec))
    val (red, green, blue) =
      matrix.transform(plain.first / FULL_SCALE, plain.second / FULL_SCALE, plain.third / FULL_SCALE)

    return Triple(
      (red * FULL_SCALE).roundToInt(),
      (green * FULL_SCALE).roundToInt(),
      (blue * FULL_SCALE).roundToInt(),
    )
  }

  private suspend fun exportedGrade(
    name: String,
    spec: EffectSpec?,
  ): Triple<Int, Int, Int>? {
    val stage = if (spec == null) "plain" else "graded"
    val output = File.createTempFile("filmstrip-$name-$stage", ".mp4").also { it.delete() }
    val composition =
      compositionOf {
        clip(MediaSource.of(landscape.absolutePath))
        if (spec != null) effects { add(spec) }
      }

    val verdict = filmstrip.plan(composition, ExportSpec())
    val plan =
      when (verdict) {
        is Verdict.Capable -> verdict.plan
        is Verdict.Degraded -> verdict.plan
        is Verdict.Incapable -> error(verdict.reasons.joinToString { it.message })
      }

    val finished = filmstrip.export(plan, MediaSink.of(output.absolutePath)).toList().last()
    if (finished is ExportStatus.Failure) error(finished.error.message)
    assertIs<ExportStatus.Success>(finished)

    val size = plan.output.size
    return pixelAt(output.absolutePath, size.width / 2, size.height / 2).also { output.delete() }
  }

  private fun luminance(pixel: Triple<Int, Int, Int>): Int = pixel.first + pixel.second + pixel.third

  // What a kept grade turns the same factor into. PQ is absolute, so the factor is read as the
  // display light ratio an SDR display would have produced and applied to the light the code value
  // decodes to. Every figure comes from the shared transfer functions, so this moves with them
  // rather than pinning a measurement taken once.
  @Test
  fun `halving brightness on a kept grade halves the light an SDR display would have shown`() =
    runTest(timeout = TIMEOUT) {
      if (!available()) return@runTest
      val capabilities = assertIs<CapabilitiesResult.Success>(filmstrip.capabilities()).capabilities
      if (!capabilities.supportsHdrEncoding) return@runTest

      val lit = exportedHdrBrightness(1f)
      val dimmed = exportedHdrBrightness(HALF)

      val expected = lit.map { code -> pqCodeScaledBy(code, brightnessDisplayGain(HALF)) }
      // Reading the factor as a bare multiply on light is the mistake this rules out. It lands
      // about twice as bright, far outside the drift a real encode leaves.
      val linear = lit.map { code -> pqCodeScaledBy(code, HALF) }

      lit.litChannels().forEach { channel ->
        assertTrue(
          abs(dimmed[channel] - expected[channel]) <= CODE_DRIFT,
          "channel $channel read ${dimmed[channel]}, expected ${expected[channel]} from $lit at full",
        )
        assertTrue(
          abs(dimmed[channel] - linear[channel]) > abs(dimmed[channel] - expected[channel]),
          "channel $channel read ${dimmed[channel]}, ${expected[channel]} from the display gain " +
            "and ${linear[channel]} from a linear one",
        )
      }
    }

  // Two dimmed exports rather than one against an untouched reference, so a channel already near
  // PQ's peak has somewhere to go. Where a factor above 1f asks for more light than the format
  // carries it clips, which is PQ's own limit and asserted as one.
  @Test
  fun `a factor above one adds light on a kept grade until the format runs out`() =
    runTest(timeout = TIMEOUT) {
      if (!available()) return@runTest
      val capabilities = assertIs<CapabilitiesResult.Success>(filmstrip.capabilities()).capabilities
      if (!capabilities.supportsHdrEncoding) return@runTest

      val lit = exportedHdrBrightness(1f)
      val brightened = exportedHdrBrightness(BRIGHTER)
      val gain = brightnessDisplayGain(BRIGHTER)

      lit.litChannels().forEach { channel ->
        val light = nitsFromPqSignal(lit[channel].toFloat() / TEN_BIT_MAX) * gain
        if (light <= PQ_PEAK_NITS * HEADROOM) {
          val expected = pqCodeScaledBy(lit[channel], gain)
          assertTrue(
            abs(brightened[channel] - expected) <= CODE_DRIFT,
            "channel $channel read ${brightened[channel]}, expected $expected from $lit at full",
          )
        } else {
          assertTrue(
            brightened[channel] >= TEN_BIT_MAX - CODE_DRIFT,
            "channel $channel asked for $light nits and read ${brightened[channel]}, short of the format's ceiling",
          )
        }
      }
    }

  // The HLG arm, where the three backends disagree about what linear means. Only the inverse OETF
  // runs here, so what is scaled is scene light and the gain has to be the one that belongs to it.
  @Test
  fun `halving brightness on a kept HLG grade halves the light an SDR display would have shown`() =
    runTest(timeout = TIMEOUT) {
      if (!available()) return@runTest
      val capabilities = assertIs<CapabilitiesResult.Success>(filmstrip.capabilities()).capabilities
      if (!capabilities.supportsHdrEncoding) return@runTest

      val lit = exportedHdrBrightness(1f, hdrHlg)
      val dimmed = exportedHdrBrightness(HALF, hdrHlg)

      val expected = lit.map { code -> hlgCodeScaledBy(code, brightnessSceneGain(HALF)) }
      // Handing HLG the display gain is the mistake this rules out. On a pipeline holding scene
      // light that darkens by a further system gamma.
      val overDimmed = lit.map { code -> hlgCodeScaledBy(code, brightnessDisplayGain(HALF)) }

      lit.litChannels().forEach { channel ->
        assertTrue(
          abs(dimmed[channel] - expected[channel]) <= CODE_DRIFT,
          "channel $channel read ${dimmed[channel]}, expected ${expected[channel]} from $lit at full",
        )
        assertTrue(
          abs(dimmed[channel] - overDimmed[channel]) > abs(dimmed[channel] - expected[channel]),
          "channel $channel read ${dimmed[channel]}, ${expected[channel]} from the scene gain " +
            "and ${overDimmed[channel]} from the display one",
        )
      }
    }

  // A contrast on a kept grade runs on the SDR signal the light decodes to, so it pivots on the
  // light mid grey makes on an SDR display rather than on the middle of PQ's range. The centre of
  // the fixture is a saturated patch, so every channel sits somewhere different on the line.
  @Test
  fun `a contrast on a kept grade pivots on the light mid grey makes`() =
    runTest(timeout = TIMEOUT) {
      if (!available()) return@runTest
      val capabilities = assertIs<CapabilitiesResult.Success>(filmstrip.capabilities()).capabilities
      if (!capabilities.supportsHdrEncoding) return@runTest

      val lit = exportedHdrGrade(Brightness(1f))
      val flattened = exportedHdrGrade(Contrast(HALF))

      val expected = pqCodesGraded(lit, Contrast(HALF))
      // Pivoting on the middle of the format's own range is the mistake this rules out. It lifts
      // every channel towards five thousand nits, far outside the drift a real encode leaves.
      val onTheFormat = lit.map { code -> pqCodeOf(HALF * pqNitsOf(code) + (1f - HALF) * PQ_PEAK_NITS / 2f) }

      lit.litChannels().forEach { channel ->
        assertGraded(flattened, expected, channel, lit)
        assertTrue(
          abs(flattened[channel] - onTheFormat[channel]) > abs(flattened[channel] - expected[channel]),
          "channel $channel read ${flattened[channel]}, ${expected[channel]} from the shared reading " +
            "and ${onTheFormat[channel]} from a pivot on the format's range",
        )
      }
    }

  // A contrast above one stretches until the format runs out. The red of the fixture's centre
  // already sits near PQ's peak, so it asks for more light than the format carries and clips
  // there, which is PQ's own limit and asserted as one. The other channels land on the reading.
  @Test
  fun `a contrast above one on a kept grade stretches until the format runs out`() =
    runTest(timeout = TIMEOUT) {
      if (!available()) return@runTest
      val capabilities = assertIs<CapabilitiesResult.Success>(filmstrip.capabilities()).capabilities
      if (!capabilities.supportsHdrEncoding) return@runTest

      val lit = exportedHdrGrade(Brightness(1f))
      val stretched = exportedHdrGrade(Contrast(BRIGHTER))
      val expected = pqCodesGraded(lit, Contrast(BRIGHTER))
      // A contrast is the same line on every channel, so the shared reference reads one channel at
      // a time with that channel's own light in all three.
      val matrix = checkNotNull(colorMatrixOf(Contrast(BRIGHTER)))

      lit.litChannels().forEach { channel ->
        // The shared reference stops at the format's peak, so a channel that landed there asked for
        // at least that much light and one below it did not.
        val nits = pqNitsOf(lit[channel])
        val asked = matrix.transformNits(nits, nits, nits, HdrTransfer.Pq)[0]
        if (asked <= PQ_PEAK_NITS * HEADROOM) {
          assertGraded(stretched, expected, channel, lit)
        } else {
          assertTrue(
            stretched[channel] >= TEN_BIT_MAX - CODE_DRIFT,
            "channel $channel asked for $asked nits and read ${stretched[channel]}, short of the format's ceiling",
          )
        }
      }
    }

  // A saturation mixes the channels, so on a grade it reaches the file through the table written
  // beside the graph, run between a decode and an encode of the transfer at sixteen bits. The
  // centre of the fixture is a saturated patch, so pulling it towards grey moves every channel.
  @Test
  fun `a saturation on a kept grade mixes the SDR signal through the table`() =
    runTest(timeout = TIMEOUT) {
      if (!available()) return@runTest
      val capabilities = assertIs<CapabilitiesResult.Success>(filmstrip.capabilities()).capabilities
      if (!capabilities.supportsHdrEncoding) return@runTest

      val lit = exportedHdrGrade(Brightness(1f))
      val desaturated = exportedHdrGrade(Saturation(HALF))
      val expected = pqCodesGraded(lit, Saturation(HALF))

      lit.litChannels().forEach { channel -> assertGraded(desaturated, expected, channel, lit) }
    }

  // The HLG arm. Only the inverse OETF runs here, so the light the line runs on comes through the
  // per-channel opto-optical transfer, and the reading goes back the same way. The table alone
  // lands within a code value of the reading on this transfer as on PQ, so the band is the
  // encoder's and the same one.
  @Test
  fun `a contrast on a kept HLG grade pivots on the light mid grey makes`() =
    runTest(timeout = TIMEOUT) {
      if (!available()) return@runTest
      val capabilities = assertIs<CapabilitiesResult.Success>(filmstrip.capabilities()).capabilities
      if (!capabilities.supportsHdrEncoding) return@runTest

      val lit = exportedHdrGrade(Brightness(1f), hdrHlg)
      val flattened = exportedHdrGrade(Contrast(HALF), hdrHlg)
      val expected = hlgCodesGraded(lit, Contrast(HALF))

      lit.litChannels().forEach { channel -> assertGraded(flattened, expected, channel, lit) }
    }

  private suspend fun exportedHdrBrightness(
    factor: Float,
    source: File = hdr,
  ): List<Int> = exportedHdrGrade(Brightness(factor), source)

  private suspend fun exportedHdrGrade(
    spec: EffectSpec,
    source: File = hdr,
  ): List<Int> {
    val output = File.createTempFile("filmstrip-hdr-${spec.id}", ".mp4").also { it.delete() }
    // Carrying an effect even where it lowers to nothing is what keeps the reference off the copy
    // path, so both runs came out of the encoder at the same geometry and the same pixel is the
    // same picture.
    val composition =
      compositionOf {
        clip(MediaSource.of(source.absolutePath))
        effects { add(spec) }
      }

    val plan = assertIs<Verdict.Capable>(filmstrip.plan(composition, ExportSpec(hdr = HdrMode.KeepHdr))).plan
    plan.path shouldBe ExportPath.Transcode
    val finished = filmstrip.export(plan, MediaSink.of(output.absolutePath)).toList().last()
    if (finished is ExportStatus.Failure) error(finished.error.message)
    assertIs<ExportStatus.Success>(finished)

    val size = plan.output.size
    return tenBitPixelAt(output.absolutePath, size.width / 2, size.height / 2).also { output.delete() }
  }

  private fun pqCodeScaledBy(
    code: Int,
    gain: Float,
  ): Int {
    val light = nitsFromPqSignal(code.toFloat() / TEN_BIT_MAX)

    return (pqSignalFromNits(light * gain) * TEN_BIT_MAX).roundToInt()
  }

  private fun hlgCodeScaledBy(
    code: Int,
    gain: Float,
  ): Int {
    val scene = sceneFromHlgSignal(code.toFloat() / TEN_BIT_MAX)

    return (hlgSignalFromScene(scene * gain) * TEN_BIT_MAX).roundToInt()
  }

  private fun assertGraded(
    measured: List<Int>,
    expected: List<Int>,
    channel: Int,
    lit: List<Int>,
  ) {
    assertTrue(
      abs(measured[channel] - expected[channel]) <= CODE_DRIFT,
      "channel $channel read ${measured[channel]}, expected ${expected[channel]} from $lit at full",
    )
  }

  // What the shared reading says the same pixel comes out as, in the ten-bit code values the
  // readback reports, so a lowering that applied the matrix somewhere else fails here rather than
  // drifting.
  private fun pqCodesGraded(
    lit: List<Int>,
    spec: EffectSpec,
  ): List<Int> {
    val matrix = checkNotNull(colorMatrixOf(spec))
    val graded = matrix.transformNits(pqNitsOf(lit[0]), pqNitsOf(lit[1]), pqNitsOf(lit[2]), HdrTransfer.Pq)

    return graded.map { pqCodeOf(it) }
  }

  private fun hlgCodesGraded(
    lit: List<Int>,
    spec: EffectSpec,
  ): List<Int> {
    val matrix = checkNotNull(colorMatrixOf(spec))
    val nits = lit.map { code -> hlgDisplayNitsFromScene(sceneFromHlgSignal(code / TEN_BIT_MAX)) }
    val graded = matrix.transformNits(nits[0], nits[1], nits[2], HdrTransfer.Hlg)

    return graded.map { (hlgSignalFromScene(hlgSceneFromDisplayNits(it)) * TEN_BIT_MAX).roundToInt() }
  }

  private fun pqNitsOf(code: Int): Float = nitsFromPqSignal(code / TEN_BIT_MAX)

  private fun pqCodeOf(nits: Float): Int = (pqSignalFromNits(nits) * TEN_BIT_MAX).roundToInt()

  /**
   * The channels of a reference read that carry enough signal to say anything.
   *
   * PQ is at its steepest near black, and the graded path costs a 4:2:0 chroma round trip that a
   * reference export with no effect never pays. On a channel sitting at black that round trip moves
   * the code value further than the effect does, so such a channel is read past rather than
   * asserted on.
   */
  private fun List<Int>.litChannels(): List<Int> =
    indices.filter { this[it] >= SIGNAL_FLOOR }.also {
      assertTrue(it.isNotEmpty(), "every channel of the reference frame read as black, so nothing was measured")
    }

  /**
   * The ten-bit red, green and blue of one pixel, read by asking ffmpeg for the planes untouched.
   *
   * An `rgb24` read would tone-map the grade away before the value could be checked, which is the
   * whole of what is under test here. gbrp10le writes green, blue and red planes in that order.
   */
  private fun tenBitPixelAt(
    path: String,
    x: Int,
    y: Int,
  ): List<Int> {
    val process =
      ProcessBuilder(
        "ffmpeg",
        "-y",
        "-hide_banner",
        "-loglevel",
        "error",
        "-i",
        path,
        "-vf",
        "crop=2:2:$x:$y,format=gbrp10le",
        "-vframes",
        "1",
        "-f",
        "rawvideo",
        "-pix_fmt",
        "gbrp10le",
        "-",
      ).start()
    val planes = process.inputStream.readNBytes(PLANE_BYTES * 3)
    process.waitFor()

    fun plane(index: Int): Int {
      val offset = index * PLANE_BYTES
      return (planes[offset].toInt() and 0xFF) or ((planes[offset + 1].toInt() and 0xFF) shl 8)
    }

    return listOf(plane(2), plane(0), plane(1))
  }

  // A blurred fill is not asserted pixel for pixel, just that the bars carry the frame's own
  // detail rather than the flat colour a solid fill would leave.
  @Test
  fun `writes a blurred fill into the bars, not a flat colour`() =
    runTest(timeout = TIMEOUT) {
      if (!available()) return@runTest

      val output = File.createTempFile("filmstrip-fill-blur", ".mp4").also { it.delete() }
      val composition =
        compositionOf {
          clip(MediaSource.of(landscape.absolutePath))
          effects { crop(AspectRatio.Portrait, fit = Fit.Contain) }
          fill(Fill.Blur)
        }

      val verdict = filmstrip.plan(composition, ExportSpec())
      // Skip rather than fail on a build with no gblur, the same way the VP9 and ALAC tests skip
      // rather than fail on a build with no encoder for them.
      if (verdict is Verdict.Incapable) return@runTest
      val plan = if (verdict is Verdict.Degraded) verdict.plan else (verdict as Verdict.Capable).plan

      val finished = filmstrip.export(plan, MediaSink.of(output.absolutePath)).toList().last()
      if (finished is ExportStatus.Failure) error(finished.error.message)
      assertIs<ExportStatus.Success>(finished)

      val size = plan.output.size
      val left = pixelAt(output.absolutePath, size.width / 4, 2)
      val right = pixelAt(output.absolutePath, size.width - size.width / 4, 2)
      assertTrue(left != right, "expected the blurred bar to vary, both points read $left")

      output.delete()
    }

  @Test
  fun `copies an untouched clip instead of re-encoding it`() =
    runTest(timeout = TIMEOUT) {
      if (!available()) return@runTest

      val output = File.createTempFile("filmstrip-copy", ".mp4").also { it.delete() }
      val composition = compositionOf { clip(MediaSource.of(landscape.absolutePath)) }

      val verdict = filmstrip.plan(composition, ExportSpec())
      val plan = assertIs<Verdict.Capable>(verdict).plan
      plan.path shouldBe ExportPath.Transmux
      plan.output.videoCodec shouldBe VideoCodec.H264
      plan.output.audioCodec shouldBe AudioCodec.Aac

      val finished = filmstrip.export(plan, MediaSink.of(output.absolutePath)).toList().last()
      if (finished is ExportStatus.Failure) error(finished.error.message)
      assertIs<ExportStatus.Success>(finished)

      // This fixture's own codec is H264, which is also the ladder's first pick, so a re-encode
      // would land on H264 too and the codec alone would not catch a silent fall back to it. File
      // size does: a copy remuxes the container without touching an encoded byte, so it lands
      // within the muxer's own padding of the source, while re-encoding writes a file of a
      // visibly different one.
      ffprobe(output.absolutePath).endsWith("h264 aac") shouldBe true
      val drift = abs(output.length() - landscape.length())
      assertTrue(
        drift <= CONTAINER_DRIFT_BYTES,
        "the copy wrote ${output.length()} bytes against the source's ${landscape.length()}",
      )

      output.delete()
    }

  // ffmpeg refuses a map that matches no stream, and a video-only source has no audio stream for
  // the copy path's `0:a` to match.
  @Test
  fun `copies a video-only clip without refusing the export over the missing audio stream`() =
    runTest(timeout = TIMEOUT) {
      if (!available()) return@runTest

      val silent = silencedCopyOf(landscape)
      val output = File.createTempFile("filmstrip-copy-silent", ".mp4").also { it.delete() }
      val composition = compositionOf { clip(MediaSource.of(silent.absolutePath)) }

      val verdict = filmstrip.plan(composition, ExportSpec())
      val plan = assertIs<Verdict.Capable>(verdict).plan
      plan.path shouldBe ExportPath.Transmux

      val finished = filmstrip.export(plan, MediaSink.of(output.absolutePath)).toList().last()
      if (finished is ExportStatus.Failure) error(finished.error.message)
      assertIs<ExportStatus.Success>(finished)

      ffprobe(output.absolutePath) shouldBe "640x360 30/1 h264"

      output.delete()
      silent.delete()
    }

  // The whole point of AudioSpec.AudioOnly is the video track it does not write. Checking that
  // audio survived would pass even if a video track rode along, so the real assertion is that
  // the written file has none.
  @Test
  fun `exports audio only with no video track`() =
    runTest(timeout = TIMEOUT) {
      if (!available()) return@runTest

      val output = File.createTempFile("filmstrip-audio-only", ".mp4").also { it.delete() }
      val composition =
        compositionOf {
          clip(MediaSource.of(landscape.absolutePath))
          audio(AudioSpec.AudioOnly)
        }

      val finished = filmstrip.export(composition, ExportSpec(), MediaSink.of(output.absolutePath)).toList().last()
      if (finished is ExportStatus.Failure) error(finished.error.message)

      val success = assertIs<ExportStatus.Success>(finished)
      assertNull(success.info.video)
      assertNotNull(success.info.audio).sampleRate shouldBe 48_000
      assertTrue(
        success.info.duration in 1_800.milliseconds..2_300.milliseconds,
        "duration was ${success.info.duration}",
      )

      // Verified independently of the code under test.
      streamTypes(output.absolutePath) shouldBe listOf("audio")

      output.delete()
    }

  // The probe looks for libvpx before allowing VP9. Nothing else in the pipeline is VP9-aware, so
  // the check is that a whole export survives it.
  @Test
  fun `exports VP9 on a build that carries libvpx`() =
    runTest(timeout = TIMEOUT) {
      if (!available()) return@runTest

      val capabilities = assertIs<CapabilitiesResult.Success>(filmstrip.capabilities()).capabilities
      if (capabilities.encoderFor(VideoCodec.Vp9) == null) return@runTest

      val output = File.createTempFile("filmstrip-vp9", ".mp4").also { it.delete() }
      val composition = compositionOf { clip(MediaSource.of(landscape.absolutePath)) }
      // Half of the fixture's 640x360, so nothing rounds and the verdict stays Capable.
      val spec = ExportSpec(targetHeight = 180, videoCodec = VideoCodec.Vp9)

      val verdict = filmstrip.plan(composition, spec)
      assertIs<Verdict.Capable>(verdict).plan.output.videoCodec shouldBe VideoCodec.Vp9

      val finished = filmstrip.export(verdict.plan, MediaSink.of(output.absolutePath)).toList().last()
      if (finished is ExportStatus.Failure) error(finished.error.message)
      assertIs<ExportStatus.Success>(finished)

      ffprobe(output.absolutePath).endsWith("vp9 aac") shouldBe true

      output.delete()
    }

  // ALAC has never had a CodecKind of its own, so the written file's audio track reads back as
  // one drift() cannot name. Proving the export still succeeds is what keeps that gap from
  // failing a file that matches the plan exactly.
  @Test
  fun `exports ALAC on a build that carries it`() =
    runTest(timeout = TIMEOUT) {
      if (!available()) return@runTest

      val capabilities = assertIs<CapabilitiesResult.Success>(filmstrip.capabilities()).capabilities
      if (capabilities.audio.none { it.codec == AudioCodec.Alac }) return@runTest

      val output = File.createTempFile("filmstrip-alac", ".mp4").also { it.delete() }
      val composition = compositionOf { clip(MediaSource.of(landscape.absolutePath)) }
      val spec = ExportSpec(targetHeight = 180, audioCodec = AudioCodec.Alac)

      val verdict = filmstrip.plan(composition, spec)
      assertIs<Verdict.Capable>(verdict).plan.output.audioCodec shouldBe AudioCodec.Alac

      val finished = filmstrip.export(verdict.plan, MediaSink.of(output.absolutePath)).toList().last()
      if (finished is ExportStatus.Failure) error(finished.error.message)
      assertIs<ExportStatus.Success>(finished)

      ffprobe(output.absolutePath).endsWith("h264 alac") shouldBe true

      output.delete()
    }

  @Test
  fun `streams progress while the encode runs`() =
    runTest(timeout = TIMEOUT) {
      if (!long.isFile) return@runTest

      val output = File.createTempFile("filmstrip-progress", ".mp4").also { it.delete() }
      val composition = compositionOf { clip(MediaSource.of(long.absolutePath)) }
      val statuses =
        filmstrip.export(composition, ExportSpec(targetHeight = 720), MediaSink.of(output.absolutePath)).toList()

      val progress = statuses.filterIsInstance<ExportStatus.Progress>()
      assertTrue(progress.size > 1, "expected more than one progress report, got ${progress.size}")
      progress.zipWithNext().forEach { (first, second) ->
        assertTrue(second.fraction >= first.fraction, "progress went backwards")
      }
      progress.last().fraction shouldBe 1f
      assertIs<ExportStatus.Success>(statuses.last())

      output.delete()
    }

  // Cancelling the collector cancels the export. ffmpeg is asked to stop with `q` rather than
  // killed, so what it has written is a readable file rather than a truncated one.
  @Test
  fun `cancelling the collector leaves a readable file`() =
    runTest(timeout = TIMEOUT) {
      if (!long.isFile) return@runTest

      val output = File.createTempFile("filmstrip-cancel", ".mp4").also { it.delete() }
      val composition = compositionOf { clip(MediaSource.of(long.absolutePath)) }

      withContext(Dispatchers.Default) {
        val flow = filmstrip.export(composition, ExportSpec(targetHeight = 720), MediaSink.of(output.absolutePath))
        val encoding = CompletableDeferred<Unit>()
        // Cancelled once a report carries encoded output rather than after a fixed wait. A runner
        // slow enough to still be starting ffmpeg at the deadline leaves a graceful stop nothing to
        // close, and the readable file this is about only exists once frames have reached the muxer.
        val collector =
          launch {
            flow.collect { status ->
              if (status is ExportStatus.Progress && status.fraction > 0f) encoding.complete(Unit)
            }
          }

        withTimeoutOrNull(ENCODE_DEADLINE) { encoding.await() }
        assertTrue(collector.isActive, "the export finished before it could be cancelled")
        collector.cancelAndJoin()
      }

      assertTrue(output.length() > 0, "nothing was written before the cancel")
      ffprobe(output.absolutePath).startsWith("1280x720") shouldBe true

      output.delete()
    }

  @Test
  fun `refuses text and offers the same edit without it`() =
    runTest(timeout = TIMEOUT) {
      if (!available()) return@runTest

      val composition =
        compositionOf {
          clip(MediaSource.of(landscape.absolutePath))
          effects { textOverlay("caption") }
        }

      val verdict = filmstrip.plan(composition, ExportSpec(targetHeight = 240))
      val incapable = assertIs<Verdict.Incapable>(verdict)
      assertIs<ExportError.UnsupportedEffect>(incapable.reasons.single())
      incapable.withoutUnsupported!!.effectOrder.none { it.spec.id == EffectIds.TEXT_OVERLAY } shouldBe true
    }

  @Test
  fun `reports a missing binary as a value`() =
    runTest(timeout = TIMEOUT) {
      val absent =
        Filmstrip {
          ffmpegBackend(FfmpegConfig(executablePath = "/nonexistent/ffmpeg"))
        }

      val result = absent.capabilities()
      val failure = assertIs<CapabilitiesResult.Failure>(result)
      val error = assertIs<ExportError.ToolchainMissing>(failure.error)
      error.tool shouldBe "ffmpeg"
      error.foundVersion shouldBe null
    }

  private fun available(): Boolean = landscape.isFile && portrait.isFile

  /**
   * Whether this build can take either tone-map route, read off the same toolchain the backend
   * gates on.
   */
  private suspend fun canToneMap(): Boolean {
    val result = ToolchainLocator(FfmpegConfig(), ProcessRunner()).toolchain()
    return result is ToolchainResult.Available && toneMapRoute(result.toolchain) != null
  }

  /**
   * A copy of [source] with its audio stream dropped, made with real ffmpeg since nothing in this
   * backend writes files of its own to derive one from.
   */
  private fun silencedCopyOf(source: File): File {
    val target = File.createTempFile("filmstrip-silent-source", ".mp4")
    ProcessBuilder(
      "ffmpeg",
      "-y",
      "-hide_banner",
      "-loglevel",
      "error",
      "-i",
      source.absolutePath,
      "-an",
      "-c",
      "copy",
      target.absolutePath,
    ).start().waitFor()
    return target
  }

  private fun probeStreamTag(
    path: String,
    tag: String,
  ): String = probeEntries(path, "stream_tags=$tag")

  private fun probeField(
    path: String,
    field: String,
  ): String = probeEntries(path, "stream=$field")

  private fun probeEntries(
    path: String,
    entries: String,
  ): String {
    val process =
      ProcessBuilder(
        "ffprobe",
        "-v",
        "error",
        "-select_streams",
        "v",
        "-show_entries",
        entries,
        "-of",
        "csv=p=0",
        path,
      ).start()
    val output = process.inputReader().readText()
    process.waitFor()
    return output.trim()
  }

  private fun streamTypes(path: String): List<String> {
    val process =
      ProcessBuilder(
        "ffprobe",
        "-v",
        "error",
        "-show_entries",
        "stream=codec_type",
        "-of",
        "csv=p=0",
        path,
      ).start()
    val output = process.inputReader().readText()
    process.waitFor()
    return output.lineSequence().filter { it.isNotBlank() }.toList()
  }

  /**
   * The RGB value of one pixel, read by asking ffmpeg itself to crop the frame down to it.
   *
   * Cropped to 2x2 rather than 1x1: `crop` rounds a size that is not a multiple of yuv420p's
   * chroma subsampling down to zero unless told otherwise, and only the first pixel is read back.
   *
   * Verified independently of the code under test, the same way [ffprobe] is.
   */
  private fun pixelAt(
    path: String,
    x: Int,
    y: Int,
  ): Triple<Int, Int, Int> {
    val process =
      ProcessBuilder(
        "ffmpeg",
        "-y",
        "-hide_banner",
        "-loglevel",
        "error",
        "-i",
        path,
        "-vf",
        "crop=2:2:$x:$y",
        "-vframes",
        "1",
        "-f",
        "rawvideo",
        "-pix_fmt",
        "rgb24",
        "-",
      ).start()
    val pixel = process.inputStream.readNBytes(3)
    process.waitFor()
    return Triple(pixel[0].toInt() and 0xFF, pixel[1].toInt() and 0xFF, pixel[2].toInt() and 0xFF)
  }

  // A flat red region survives H264 losslessly enough that only rounding at the YUV boundary is
  // expected, never a shift toward another colour.
  private fun assertReddish(pixel: Triple<Int, Int, Int>) {
    val (red, green, blue) = pixel
    assertTrue(red > 200 && green < 60 && blue < 60, "expected a red pixel, got $pixel")
  }

  // The grade is what an HDR export is for, and neither the plan nor a Success status says whether
  // it reached the file. ffprobe does.
  @Test
  fun `keeps an hdr grade through a re-encode`() =
    runTest(timeout = TIMEOUT) {
      if (!available()) return@runTest
      val capabilities = assertIs<CapabilitiesResult.Success>(filmstrip.capabilities()).capabilities
      if (!capabilities.supportsHdrEncoding) return@runTest

      val output = File.createTempFile("filmstrip-hdr", ".mp4").also { it.delete() }
      // A rotate takes the clip off the copy path, so this is the encoder writing the grade rather
      // than the muxer carrying the source's bytes across.
      val composition = compositionOf { clip(MediaSource.of(hdr.absolutePath)) { effects { rotate(90) } } }
      val spec = ExportSpec(hdr = HdrMode.KeepHdr)

      val plan = assertIs<Verdict.Capable>(filmstrip.plan(composition, spec)).plan
      plan.path shouldBe ExportPath.Transcode
      plan.output.videoCodec shouldBe VideoCodec.Hevc

      val finished = filmstrip.export(plan, MediaSink.of(output.absolutePath)).toList().last()
      if (finished is ExportStatus.Failure) error(finished.error.message)
      assertIs<ExportStatus.Success>(finished)

      colorTags(output.absolutePath) shouldBe "yuv420p10le bt2020 smpte2084 bt2020nc"

      output.delete()
    }

  // Bringing a grade down correctly wants zscale (--enable-libzimg) or libplacebo, and neither is
  // in the common prebuilt packages, so this asks the toolchain the same question the planner does
  // rather than assuming either answer.
  @Test
  fun `tone-maps an hdr grade down to rec709 when the build can`() =
    runTest(timeout = TIMEOUT) {
      if (!available()) return@runTest
      val composition = compositionOf { clip(MediaSource.of(hdr.absolutePath)) { effects { rotate(90) } } }
      val verdict = filmstrip.plan(composition, ExportSpec(hdr = HdrMode.ToneMapToSdr))

      if (!canToneMap()) {
        assertIs<Verdict.Incapable>(verdict, "a build with no zscale or libplacebo has no honest tone map to offer")
        return@runTest
      }

      val output = File.createTempFile("filmstrip-sdr", ".mp4").also { it.delete() }
      val plan = assertIs<Verdict.Capable>(verdict).plan
      val finished = filmstrip.export(plan, MediaSink.of(output.absolutePath)).toList().last()
      if (finished is ExportStatus.Failure) error(finished.error.message)
      assertIs<ExportStatus.Success>(finished)

      colorTags(output.absolutePath) shouldBe "yuv420p bt709 bt709 bt709"

      output.delete()
    }

  // A copy runs no encoder, so this holds whatever the build can encode: the grade rides across in
  // the source's own packets and the tags ride with it.
  @Test
  fun `copies an hdr clip with its grade intact`() =
    runTest(timeout = TIMEOUT) {
      if (!available()) return@runTest

      val output = File.createTempFile("filmstrip-hdr-copy", ".mp4").also { it.delete() }
      val composition = compositionOf { clip(MediaSource.of(hdr.absolutePath)) }

      val plan = assertIs<Verdict.Capable>(filmstrip.plan(composition, ExportSpec())).plan
      plan.path shouldBe ExportPath.Transmux

      val finished = filmstrip.export(plan, MediaSink.of(output.absolutePath)).toList().last()
      if (finished is ExportStatus.Failure) error(finished.error.message)
      assertIs<ExportStatus.Success>(finished)

      colorTags(output.absolutePath) shouldBe colorTags(hdr.absolutePath)

      output.delete()
    }

  /**
   * The colour tags and the pixel format, the four fields that decide whether a file is HDR.
   *
   * Reported together because a 10-bit frame with Rec.709 tags and an 8-bit frame with BT.2020 tags
   * are both wrong, and either one alone reads as a pass.
   */
  private fun colorTags(path: String): String {
    val process =
      ProcessBuilder(
        "ffprobe",
        "-v",
        "error",
        "-select_streams",
        "v:0",
        "-show_entries",
        "stream=pix_fmt,color_primaries,color_transfer,color_space",
        "-of",
        "default=noprint_wrappers=1",
        path,
      ).start()
    val output = process.inputReader().readText()
    process.waitFor()

    // ffprobe prints these in its own order rather than the order they were asked for, so they are
    // read by key and put back in one this test can pin.
    val fields =
      output
        .lineSequence()
        .mapNotNull { line -> line.split("=", limit = 2).takeIf { it.size == 2 } }
        .associate { it[0].trim() to it[1].trim() }

    return listOf("pix_fmt", "color_primaries", "color_transfer", "color_space")
      .joinToString(" ") { fields[it] ?: "unknown" }
  }

  private fun ffprobe(path: String): String {
    val process =
      ProcessBuilder(
        "ffprobe",
        "-v",
        "error",
        "-show_entries",
        "stream=codec_type,codec_name,width,height,avg_frame_rate",
        "-of",
        "default=noprint_wrappers=1",
        path,
      ).start()
    val output = process.inputReader().readText()
    process.waitFor()

    val fields =
      output
        .lineSequence()
        .mapNotNull { line -> line.split("=", limit = 2).takeIf { it.size == 2 } }
        .groupBy({ it[0].trim() }, { it[1].trim() })

    return "${fields["width"]!!.first()}x${fields["height"]!!.first()} " +
      "${fields["avg_frame_rate"]!!.first()} " +
      fields["codec_name"]!!.joinToString(" ")
  }

  private companion object {
    val TIMEOUT = kotlin.time.Duration.parse("2m")

    // Long enough for a loaded runner to open the encoder, short of the runTest timeout.
    val ENCODE_DEADLINE = kotlin.time.Duration.parse("30s")
    const val RED = 0xFFFF0000.toInt()
    const val HALF = 0.5f
    const val BRIGHTER = 1.5f

    // Comfortably above half of RED's own red channel and comfortably below assertReddish's own
    // floor, so a bar that read halved fails here rather than by accident of a bound written for a
    // different purpose.
    const val HALVED_RED_CEILING = 180

    // How far a remux may land from the source it copied. The mp4 muxer sizes its own padding, and
    // ffmpeg 6 writes a byte more of it than later builds do. A re-encode of this fixture misses by
    // tens of kilobytes, so the band separates the two readings without pinning a muxer's spelling.
    const val CONTAINER_DRIFT_BYTES = 64L

    // A 2x2 crop of one plane at two bytes a sample.
    const val PLANE_BYTES = 8
    const val TEN_BIT_MAX = 1023f

    // What a real HEVC encode and a 4:2:0 chroma round trip leave on a ten-bit code value. The two
    // readings this separates are hundreds of code values apart, so the band is generous without
    // being blind.
    const val CODE_DRIFT = 40

    // Where a ten-bit channel carries more than the fixture's own noise floor and the slop a
    // chroma round trip leaves.
    const val SIGNAL_FLOOR = 128

    // How close to PQ's peak a reading has to get to count as having hit the format's ceiling
    // rather than the effect's answer.
    const val HEADROOM = 0.9f

    // How far off half the encoder and a 4:2:0 round trip are allowed to leave the halved signal.
    // Halving linear light instead would read about three quarters of the signal, well outside
    // this, which is what makes the band worth asserting rather than a plain "darker".
    const val SIGNAL_DRIFT = 0.05f

    // What a full eight-bit channel reads as, which is what the shared matrix's zero-to-one answer
    // is scaled by.
    const val FULL_SCALE = 255f

    // SIGNAL_DRIFT's width in code values. A matrix answers per channel rather than as one signal,
    // so each channel is given the same band the halved signal gets.
    const val CHANNEL_DRIFT = (SIGNAL_DRIFT * FULL_SCALE).toInt()
  }
}
