@file:OptIn(ExperimentalWasmJsInterop::class)

package dev.jordond.filmstrip.webcodecs

import dev.jordond.filmstrip.media.MediaSource
import dev.jordond.filmstrip.webcodecs.internal.ArrayBuffer
import dev.jordond.filmstrip.webcodecs.internal.AudioSample
import dev.jordond.filmstrip.webcodecs.internal.AudioSampleSink
import dev.jordond.filmstrip.webcodecs.internal.AudioSampleSource
import dev.jordond.filmstrip.webcodecs.internal.BufferTarget
import dev.jordond.filmstrip.webcodecs.internal.EncodedPacketSink
import dev.jordond.filmstrip.webcodecs.internal.JsOptions
import dev.jordond.filmstrip.webcodecs.internal.Mp4OutputFormat
import dev.jordond.filmstrip.webcodecs.internal.Output
import dev.jordond.filmstrip.webcodecs.internal.PacketStream
import dev.jordond.filmstrip.webcodecs.internal.Quality
import dev.jordond.filmstrip.webcodecs.internal.SourceReader
import dev.jordond.filmstrip.webcodecs.internal.Uint8Array
import dev.jordond.filmstrip.webcodecs.internal.VideoSample
import dev.jordond.filmstrip.webcodecs.internal.VideoSampleSource
import dev.jordond.filmstrip.webcodecs.internal.toUint8Array
import kotlinx.coroutines.await
import kotlin.js.ExperimentalWasmJsInterop
import kotlin.math.PI
import kotlin.math.abs
import kotlin.math.sin

/**
 * A colour, as the eight-bit channels a test asserts on.
 */
internal class Rgb(
  val red: Int,
  val green: Int,
  val blue: Int,
) {
  /**
   * True when every channel is within [tolerance] of [other]. Colour survives a 4:2:0 round trip
   * approximately, never exactly.
   */
  fun isNear(
    other: Rgb,
    tolerance: Int = DEFAULT_TOLERANCE,
  ): Boolean =
    abs(red - other.red) <= tolerance &&
      abs(green - other.green) <= tolerance &&
      abs(blue - other.blue) <= tolerance

  override fun toString(): String = "rgb($red, $green, $blue)"

  companion object {
    const val DEFAULT_TOLERANCE = 24

    val Black = Rgb(0, 0, 0)
    val Red = Rgb(220, 30, 30)
    val Blue = Rgb(30, 30, 220)
    val Green = Rgb(30, 200, 30)
    val Grey = Rgb(200, 200, 200)
  }
}

/**
 * One decoded frame of an export, with its pixels in memory so a test can look at a position rather
 * than only at a dimension.
 */
internal class OutputFrame(
  val timestampUs: Double,
  val durationUs: Double,
  val width: Int,
  val height: Int,
  private val rgba: Uint8Array,
) {
  /**
   * The colour at a point given as fractions of the frame, measured from the top left the way
   * filmstrip measures everything else.
   */
  fun at(
    x: Double,
    y: Double,
  ): Rgb {
    val column = (x * width).toInt().coerceIn(0, width - 1)
    val row = (y * height).toInt().coerceIn(0, height - 1)
    val offset = (row * width + column) * RGBA_CHANNELS
    return Rgb(rgba.at(offset), rgba.at(offset + 1), rgba.at(offset + 2))
  }
}

/**
 * Muxes [frames] frames of [width] by [height] into an MP4 and hands the file back.
 *
 * Built here rather than committed, so the test media is a few kilobytes of generated bytes instead
 * of a binary in the tree. [row] paints one scanline at a time, which is all the fixtures need and
 * is what lets a test tell the top of a frame from the bottom.
 */
internal suspend fun makeClip(
  width: Int = 64,
  height: Int = 64,
  frames: Int = 12,
  frameRate: Int = 30,
  row: (frameIndex: Int, y: Int) -> Rgb,
): ByteArray {
  val target = BufferTarget()
  val output =
    Output(
      JsOptions()
        .put("format", Mp4OutputFormat())
        .put("target", target)
        .build(),
    )
  val source =
    VideoSampleSource(
      JsOptions()
        .put("codec", "avc")
        .put("fullCodecString", "avc1.42001F")
        .put("quality", Quality(JsOptions().put("bitrate", FIXTURE_BITRATE).build()))
        .put("keyFrameInterval", 1.0)
        .build(),
    )
  output.addVideoTrack(source, JsOptions().put("frameRate", frameRate).build())
  output.start().await()

  val pixels = ByteArray(width * height * RGBA_CHANNELS)
  for (index in 0 until frames) {
    for (y in 0 until height) {
      val colour = row(index, y)
      for (x in 0 until width) {
        val offset = (y * width + x) * RGBA_CHANNELS
        pixels[offset] = colour.red.toByte()
        pixels[offset + 1] = colour.green.toByte()
        pixels[offset + 2] = colour.blue.toByte()
        pixels[offset + 3] = OPAQUE
      }
    }
    val sample =
      VideoSample(
        pixels.toUint8Array(),
        JsOptions()
          .put("format", "RGBA")
          .put("codedWidth", width)
          .put("codedHeight", height)
          .put("timestamp", index.toDouble() / frameRate)
          .put("duration", 1.0 / frameRate)
          .build(),
      )
    try {
      source.add(sample).await()
    } finally {
      sample.close()
    }
  }

  output.finalize().await()
  return (target.buffer ?: error("the fixture muxer produced no buffer")).toByteArray()
}

/**
 * A solid clip, for the cases where only the timing matters.
 */
internal suspend fun makeClip(
  width: Int = 64,
  height: Int = 64,
  frames: Int = 12,
  frameRate: Int = 30,
  colour: Rgb = Rgb.Grey,
): ByteArray = makeClip(width, height, frames, frameRate) { _, _ -> colour }

/**
 * A solid clip encoded with [codec] rather than H.264. [fullCodecString] is left for mediabunny to
 * build itself, which every codec but H.264's fixtures here rely on.
 */
internal suspend fun makeClipInCodec(
  codec: String,
  width: Int = 64,
  height: Int = 64,
  frames: Int = 12,
  frameRate: Int = 30,
  colour: Rgb = Rgb.Grey,
): ByteArray {
  val target = BufferTarget()
  val output =
    Output(
      JsOptions()
        .put("format", Mp4OutputFormat())
        .put("target", target)
        .build(),
    )
  val source =
    VideoSampleSource(
      JsOptions()
        .put("codec", codec)
        .put("quality", Quality(JsOptions().put("bitrate", FIXTURE_BITRATE).build()))
        .put("keyFrameInterval", 1.0)
        .build(),
    )
  output.addVideoTrack(source, JsOptions().put("frameRate", frameRate).build())
  output.start().await()

  val pixels = ByteArray(width * height * RGBA_CHANNELS)
  for (y in 0 until height) {
    for (x in 0 until width) {
      val offset = (y * width + x) * RGBA_CHANNELS
      pixels[offset] = colour.red.toByte()
      pixels[offset + 1] = colour.green.toByte()
      pixels[offset + 2] = colour.blue.toByte()
      pixels[offset + 3] = OPAQUE
    }
  }
  for (index in 0 until frames) {
    val sample =
      VideoSample(
        pixels.toUint8Array(),
        JsOptions()
          .put("format", "RGBA")
          .put("codedWidth", width)
          .put("codedHeight", height)
          .put("timestamp", index.toDouble() / frameRate)
          .put("duration", 1.0 / frameRate)
          .build(),
      )
    try {
      source.add(sample).await()
    } finally {
      sample.close()
    }
  }

  output.finalize().await()
  return (target.buffer ?: error("the fixture muxer produced no buffer")).toByteArray()
}

/**
 * The same clip [makeClip] builds, with a short tone muxed in as an Opus audio track.
 */
internal suspend fun makeClipWithAudio(
  width: Int = 64,
  height: Int = 64,
  frames: Int = 12,
  frameRate: Int = 30,
  colour: Rgb = Rgb.Grey,
  sampleRate: Int = 48_000,
): ByteArray {
  val target = BufferTarget()
  val output =
    Output(
      JsOptions()
        .put("format", Mp4OutputFormat())
        .put("target", target)
        .build(),
    )
  val videoSource =
    VideoSampleSource(
      JsOptions()
        .put("codec", "avc")
        .put("fullCodecString", "avc1.42001F")
        .put("quality", Quality(JsOptions().put("bitrate", FIXTURE_BITRATE).build()))
        .put("keyFrameInterval", 1.0)
        .build(),
    )
  output.addVideoTrack(videoSource, JsOptions().put("frameRate", frameRate).build())
  val audioSource =
    AudioSampleSource(
      JsOptions()
        .put("codec", "opus")
        .put("quality", Quality(JsOptions().put("bitrate", FIXTURE_AUDIO_BITRATE).build()))
        .build(),
    )
  output.addAudioTrack(audioSource, JsOptions().build())
  output.start().await()

  val pixels = ByteArray(width * height * RGBA_CHANNELS)
  for (index in 0 until frames) {
    for (y in 0 until height) {
      for (x in 0 until width) {
        val offset = (y * width + x) * RGBA_CHANNELS
        pixels[offset] = colour.red.toByte()
        pixels[offset + 1] = colour.green.toByte()
        pixels[offset + 2] = colour.blue.toByte()
        pixels[offset + 3] = OPAQUE
      }
    }
    val sample =
      VideoSample(
        pixels.toUint8Array(),
        JsOptions()
          .put("format", "RGBA")
          .put("codedWidth", width)
          .put("codedHeight", height)
          .put("timestamp", index.toDouble() / frameRate)
          .put("duration", 1.0 / frameRate)
          .build(),
      )
    try {
      videoSource.add(sample).await()
    } finally {
      sample.close()
    }
  }

  val audioSeconds = frames.toDouble() / frameRate
  val audioFrames = (audioSeconds * sampleRate).toInt()
  val pcm = ByteArray(audioFrames * BYTES_PER_SAMPLE)
  for (frame in 0 until audioFrames) {
    val value = (sin(2.0 * PI * TONE_HZ * frame / sampleRate) * Short.MAX_VALUE * TONE_AMPLITUDE).toInt()
    val offset = frame * BYTES_PER_SAMPLE
    pcm[offset] = (value and BYTE_MASK).toByte()
    pcm[offset + 1] = ((value shr BYTE_BITS) and BYTE_MASK).toByte()
  }
  val audioSample =
    AudioSample(
      JsOptions()
        .put("data", pcm.toUint8Array())
        .put("format", "s16")
        .put("numberOfChannels", 1)
        .put("sampleRate", sampleRate)
        .put("timestamp", 0.0)
        .build(),
    )
  try {
    audioSource.add(audioSample).await()
  } finally {
    audioSample.close()
  }

  output.finalize().await()
  return (target.buffer ?: error("the fixture muxer produced no buffer")).toByteArray()
}

/**
 * What decoding [source]'s audio track back proved: real samples with a real duration and a peak
 * amplitude, or null when the source has no audio track at all.
 */
internal class DecodedAudio(
  val sampleCount: Int,
  val durationUs: Double,
  val peakAmplitude: Float,
)

internal suspend fun decodeAudio(source: MediaSource): DecodedAudio? {
  val reader = SourceReader.of(source) ?: error("the decoder could not open $source")
  try {
    val track = reader.audioTrack() ?: return null
    val sink = AudioSampleSink(track)
    val iterator = sink.samples(0.0, Double.POSITIVE_INFINITY)
    var count = 0
    var durationUs = 0.0
    var peak = 0f
    while (true) {
      val step = iterator.next().await()
      if (step.done) break
      val sample = step.value ?: continue
      try {
        count++
        durationUs = maxOf(durationUs, sample.microsecondTimestamp + sample.microsecondDuration)
        val buffer = sample.toAudioBuffer()
        for (channel in 0 until buffer.numberOfChannels) {
          val data = buffer.getChannelData(channel)
          for (index in 0 until data.length) {
            peak = maxOf(peak, abs(data.at(index)))
          }
        }
      } finally {
        sample.close()
      }
    }
    return DecodedAudio(count, durationUs, peak)
  } finally {
    reader.close()
  }
}

/**
 * Whether [source] carries a video track at all, asked of the container rather than of a decoder.
 *
 * [decodeFrames] fails outright on a file with no video track, so a test that means to prove one is
 * absent asks this instead.
 */
internal suspend fun hasVideoTrack(source: MediaSource): Boolean {
  val reader = SourceReader.of(source) ?: error("the decoder could not open $source")
  try {
    return reader.videoTrack() != null
  } finally {
    reader.close()
  }
}

/**
 * Every encoded video packet of [source], read without decoding them. Compares a copy's bitstream
 * against the source it was copied from, rather than only the pixels a decode would show.
 */
internal suspend fun readEncodedVideoPackets(source: MediaSource): List<ByteArray> {
  val reader = SourceReader.of(source) ?: error("the decoder could not open $source")
  try {
    val track = reader.videoTrack() ?: error("the source has no video track")
    val stream = PacketStream(EncodedPacketSink(track).packets())
    val packets = mutableListOf<ByteArray>()
    try {
      while (true) {
        val packet = stream.next() ?: break
        packets += ByteArray(packet.data.length) { packet.data.at(it).toByte() }
      }
    } finally {
      stream.close()
    }
    return packets
  } finally {
    reader.close()
  }
}

/**
 * Decodes every frame of [source] into memory. This is the reader the pixel assertions run against,
 * and it never saw the encoder that wrote the file.
 */
internal suspend fun decodeFrames(source: MediaSource): List<OutputFrame> {
  val reader = SourceReader.of(source) ?: error("the decoder could not open $source")
  try {
    val stream = reader.frames(0.0, Double.POSITIVE_INFINITY) ?: error("the decoded file has no video track")
    val frames = mutableListOf<OutputFrame>()
    try {
      while (true) {
        val sample = stream.next() ?: break
        try {
          val options = JsOptions().put("format", "RGBA").build()
          val rgba = Uint8Array(sample.allocationSize(options))
          sample.copyTo(rgba, options).await()
          frames +=
            OutputFrame(
              timestampUs = sample.microsecondTimestamp,
              durationUs = sample.microsecondDuration,
              width = sample.codedWidth,
              height = sample.codedHeight,
              rgba = rgba,
            )
        } finally {
          sample.close()
        }
      }
    } finally {
      stream.close()
    }
    return frames
  } finally {
    reader.close()
  }
}

private fun ArrayBuffer.toByteArray(): ByteArray {
  val view = Uint8Array(this)
  return ByteArray(view.length) { view.at(it).toByte() }
}

private const val RGBA_CHANNELS = 4
private const val OPAQUE = 255.toByte()
private const val FIXTURE_BITRATE = 2_000_000
private const val FIXTURE_AUDIO_BITRATE = 64_000
private const val BYTES_PER_SAMPLE = 2
private const val BYTE_BITS = 8
private const val BYTE_MASK = 0xFF
private const val TONE_HZ = 440.0
private const val TONE_AMPLITUDE = 0.2
